function suite = run_powerflow_suite()
%RUN_POWERFLOW_SUITE Run NR, GS, and both CPF variants on the IEEE 5-bus case.

pf_init_paths();

case_data = case_ieee5bus();

nr_options = struct( ...
    'max_iter', 20, ...
    'tolerance', 1e-6, ...
    'plot_results', true, ...
    'verbose', true);

gs_options = struct( ...
    'max_iter', 300, ...
    'tolerance', 1e-6, ...
    'acceleration', 1.4, ...
    'plot_results', true, ...
    'verbose', true);

cpf_options = struct( ...
    'target_bus', 5, ...
    'lambda_step', 0.05, ...
    'lambda_max', 1.5, ...
    'min_voltage', 0.65, ...
    'max_steps', 80, ...
    'tolerance', 1e-6, ...
    'plot_results', true, ...
    'verbose', true);

nr = powerflow_newton_raphson(case_data, nr_options);
gs = powerflow_gauss_seidel(case_data, gs_options);

pf_plot_convergence_comparison({nr, gs}, {'Newton-Raphson', 'Gauss-Seidel'});

cpf_ls = cpf_load_scaling(case_data, cpf_options);
cpf_pc = cpf_predictor_corrector(case_data, cpf_options);

suite = struct();
suite.case_data = case_data;
suite.newton_raphson = nr;
suite.gauss_seidel = gs;
suite.cpf_load_scaling = cpf_ls;
suite.cpf_predictor_corrector = cpf_pc;

fprintf('\n============================================================\n');
fprintf('POWER FLOW SUITE SUMMARY\n');
fprintf('============================================================\n');
fprintf('NR: converged=%d, iterations=%d, P_loss=%.6f pu\n', ...
    nr.converged, nr.iterations, nr.P_loss_total);
fprintf('GS: converged=%d, iterations=%d, P_loss=%.6f pu, max |V_GS-V_NR|=%.6e pu\n', ...
    gs.converged, gs.iterations, gs.P_loss_total, max(abs(gs.bus_voltage - nr.bus_voltage)));
fprintf('CPF load-scaling: %d solved points, last lambda=%.4f, stop="%s"\n', ...
    numel(cpf_ls.lambdas), cpf_ls.lambdas(end), cpf_ls.stop_reason);
fprintf('CPF predictor-corrector: %d solved points, last lambda=%.4f, stop="%s"\n', ...
    numel(cpf_pc.lambdas), cpf_pc.lambdas(end), cpf_pc.stop_reason);
end
