function opts = ai_supervisor_defaults(overrides)
%AI_SUPERVISOR_DEFAULTS  Default options for the AI mode-switching supervisor.
%
%   OPTS = ai.ai_supervisor_defaults() returns the full option set.
%   OPTS = ai.ai_supervisor_defaults(OVERRIDES) applies the fields of the struct
%   OVERRIDES on top of the defaults. Every field of OVERRIDES must already name
%   a default field; an unknown name is refused rather than silently ignored, so
%   a typo cannot look like a working configuration.
%
%   THIS SUPERVISOR IS A SHADOW LAYER. It never writes into
%   stability.ts_simulate_ibr_hybrid. That engine's decision contract stays
%       severity = min(1, max(0, 0.5*J_V + 0.5*J_f))
%   over J_V and J_f ONLY (+stability/agsi_reference_terms.m header). The AI
%   layer reads recorded physics and proposes a mode vector; it does not enter
%   an accepted step, a gate, or a hysteresis timer of the production run.
%
%   Trigger rules (OPTS.trigger_rule):
%     "spec"        |RoCoF| >= rocof_threshold_Hz_s  OR  min(V) <= vmin_threshold_pu
%     "production"  S >= gamma_on sustained dwell_on_s, released below gamma_off
%                   for dwell_off_s, with S = sat(0.5*J_V + 0.5*J_f)
%
%   See also ai.ai_detect_event, ai.snapshot_from_cache.

arguments
    overrides struct = struct()
end

opts = struct( ...
    ... % --- transport -----------------------------------------------------
    ... % The gateway's OpenAI-compatible route. The bare /v1 root answers 404
    ... % for this body; the /chat/completions path is the one that serves it.
    'endpoint',          "https://gateway.birdsphichitchai.dev/v1/chat/completions", ...
    ... % Measured against this gateway, not assumed: the "ocg/deepseek-v4.1-flash"
    ... % route answers HTTP 400 with {"model":"deepseek-v4.1-flash"}, i.e. the
    ... % upstream is handed a bare name it does not serve. This route answers
    ... % HTTP 200 with the same body. Switch back with one argument if that
    ... % changes: ai_supervisor(id, 'model', "ocg/deepseek-v4.1-flash")
    'model',             "thehive/deepseek-ai/deepseek-v4.1-flash", ...
    ... % A NAME of an environment variable, not a model id. It must hold the
    ... % credential, so the key never enters a version-controlled file.
    'api_key_env',       "ANTHROPIC_API_KEY", ...
    'reasoning_effort',  "high", ...
    'temperature',       0.0, ...
    'timeout_s',         30.0, ...
    'max_retries',       2, ...
    'retry_backoff_s',   0.5, ...
    ... % --- when to fire --------------------------------------------------
    'trigger_rule',      "spec", ...
    'rocof_threshold_Hz_s', 0.80, ...
    'vmin_threshold_pu',    0.90, ...
    ... % production rule reuses the engine's own bases, so the two agree
    'severity_dV_base_pu',  0.10, ...
    'severity_df_base_Hz',  0.50, ...
    'severity_f0_Hz',       60.0, ...
    'gamma_on',             0.65, ...
    'gamma_off',            0.35, ...
    'dwell_on_s',           0.10, ...
    'dwell_off_s',          1.00, ...
    ... % --- snapshot window and selection limits --------------------------
    'window_ms',         100.0, ...
    'max_gfm_buses',     2, ...
    ... % a voltage this low is "severe", which is the only case the fallback
    ... % selector is allowed to spend its second bus on
    'vmin_severe_pu',    0.80, ...
    ... % IBR ratings on the system base. +cases/scenario_ieee14_1sg_4ibr.m:105
    ... % sets ibr_Mbase = [100 100 100 100] against Sbase = 100 MVA, so every
    ... % converter is 1.0 pu here. Used ONLY by the ESCR rebuild path, i.e.
    ... % when a cache predates result.agsi_reference.
    'ibr_srated_pu',     ones(1,4), ...
    ... % --- short-circuit strength study -------------------------------------
    ... % OFF by default: ai.miescr_condition_study builds the case, solves its
    ... % equilibrium and assembles the device set, which costs seconds and has
    ... % nothing to do with a supervisory decision. Turn it on to print the
    ... % MI-ESCR-vs-damping comparison; the contract tests leave it off.
    'escr_study',        false, ...
    ... % "cigre"    interaction terms load the denominator (published form)
    ... % "numerator" interaction terms are subtracted from S_sc (may go negative)
    'escr_form',         "cigre", ...
    ... % frozen admissibility summary carrying the certified zeta per set.
    ... % Read only; a missing file leaves the damping column NaN.
    'escr_zeta_table',   fullfile('output','diagnostics', ...
                          'ieee14_gfm_lock_compare_zeta','summary.mat'), ...
    ... % --- offline / test hooks ------------------------------------------
    'cache_dir',         fullfile('output','diagnostics','ieee14_scenario_suite'), ...
    'force_fallback',    false, ...
    'verbose',           true);

fn = fieldnames(overrides);
for k = 1:numel(fn)
    if ~isfield(opts, fn{k})
        error('ai:ai_supervisor_defaults:unknownOption', ...
            'Unknown option "%s". Known options: %s', ...
            fn{k}, strjoin(fieldnames(opts), ', '));
    end
    opts.(fn{k}) = overrides.(fn{k});
end

if ~any(strcmpi(string(opts.trigger_rule), ["spec","production"]))
    error('ai:ai_supervisor_defaults:badTriggerRule', ...
        'trigger_rule must be "spec" or "production", got "%s".', ...
        string(opts.trigger_rule));
end
if opts.max_gfm_buses < 1 || opts.max_gfm_buses > 2
    error('ai:ai_supervisor_defaults:badMaxGfmBuses', ...
        ['max_gfm_buses must be 1 or 2, got %d. Above two forming converters ' ...
         'the circulating-current and power-oscillation risk that the design ' ...
         'rules bound is no longer bounded.'], opts.max_gfm_buses);
end
end
