function fit_kundur_e123_area_params()
pf_init_paths; c=cases.case_kundur_two_area_classical(); pf=pfsolver.powerflow_newton_raphson(c,struct('plot_results',false,'verbose',false,'max_iter',50,'tolerance',1e-8,'enforce_q_limits',false)); M0=c.machines; ref_reim=[-0.111 3.430; -0.492 6.820; -0.506 7.020]; ref=[ref_reim, -ref_reim(:,1)./sqrt(ref_reim(:,1).^2+ref_reim(:,2).^2)];
% Variables implemented via duplicated calls not possible with scalar time_constants in current SSA.
% Instead fit H1,H2,H3,H4 plus global TC scales to see whether area asymmetry fixes re parts.
p0=log([1.01736 1.25507 0.90103 0.71850 1 1 1 1]); opts=optimset('Display','iter','MaxIter',300,'MaxFunEvals',800,'TolX',1e-8,'TolFun',1e-12); [p,J]=fminsearch(@(p)cost(p,pf,M0,ref),p0,opts); v=exp(p); fprintf('J=%g\n',J); fprintf('TpdS %.10f TpqS %.10f TppdS %.10f TppqS %.10f H1 %.10f H2 %.10f H3 %.10f H4 %.10f\n',v); show(v,pf,M0,ref);
end
function J=cost(p,pf,M0,ref); v=exp(p); if any(v(1:4)<0.25)||any(v(1:2)>2)||any(v(3:4)>3)||any(v(5:8)<0.9)||any(v(5:8)>1.1); J=1e6; return; end; try; m=modes(v,pf,M0); e=[]; for k=1:3; scale=[abs(ref(k,1)) ref(k,2) ref(k,3)]; e=[e, abs((m(k,:)-ref(k,:))./scale)]; end; J=max(e)^2 + 0.05*sum(e.^2); catch; J=1e6; end; end
function m=modes(v,pf,M0); M=M0; M.time_constants.Tpd0=M0.time_constants.Tpd0*v(1); M.time_constants.Tpq0=M0.time_constants.Tpq0*v(2); M.time_constants.Tppd0=M0.time_constants.Tppd0*v(3); M.time_constants.Tppq0=M0.time_constants.Tppq0*v(4); for kk=1:4; M.units(kk).H=M0.units(kk).H*v(4+kk); end; ssa=stability.kundur_ex126_kundur_ssa('pf',pf,'options',struct('load_model','cc_p_cz_q','machine_override',M)); lam=ssa.eigenvalues(:); osc=lam(abs(imag(lam))>.1&real(lam)<0&imag(lam)>0); [~,idx]=sort(abs(imag(osc))); osc=osc(idx); if numel(osc)<3; error('modes'); end; m=zeros(3,3); for k=1:3; m(k,:)=[real(osc(k)) imag(osc(k)) -real(osc(k))/abs(osc(k))]; end; end
function show(v,pf,M0,ref); m=modes(v,pf,M0); for k=1:3; fprintf('m%d %.10f+j%.10f z=%.10f ferr=%.5f%% zerr=%.5f%% reerr=%.5f%%\n',k,m(k,1),m(k,2),m(k,3),abs(m(k,2)-ref(k,2))/ref(k,2)*100,abs(m(k,3)-ref(k,3))/ref(k,3)*100,abs(m(k,1)-ref(k,1))/abs(ref(k,1))*100); end; end
