function comparison = et_fcs_compare_bo(candidates, bo_policy)
%ET_FCS_COMPARE_BO  Paired exhaustive ET-FCSPS versus offline BO summary.
%   Both methods consume the identical hard-screened candidate table. ET-FCSPS
%   prediction count is every screen survivor; BO count is its frozen budget.
%   This comparison is diagnostic and does not commit either winner.

arguments
    candidates struct
    bo_policy struct
end
bo = stability.et_fcs_bo_replay(candidates,bo_policy);
comparison = struct('schema','et_fcs_bo_comparison/1.0', ...
    'classification','ASSUMED_DIAGNOSTIC_PAIRED_REPLAY', ...
    'status',bo.status,'et_fcs_candidate_count',sum([candidates.screen_pass]), ...
    'bo_evaluation_count',bo.evaluation_count,'evaluation_reduction_fraction',NaN, ...
    'et_fcs_winner_candidate_id',bo.exhaustive_winner_candidate_id, ...
    'bo_winner_candidate_id',bo.winner_candidate_id,'same_winner',bo.matches_exhaustive, ...
    'et_fcs_cost',bo.exhaustive_cost,'bo_cost',bo.winner_cost,'bo_regret',bo.regret, ...
    'bo_result',bo);
if comparison.et_fcs_candidate_count > 0
    comparison.evaluation_reduction_fraction = 1 - ...
        comparison.bo_evaluation_count/comparison.et_fcs_candidate_count;
end
end
