function policy = et_fcs_policy_ieee14()
%ET_FCS_POLICY_IEEE14  Frozen project-derived ET-FCSPS prototype policy.
%   The values are design choices fixed before closed-loop results. Existing
%   AGSI++ normalization bases motivate voltage/frequency/RoCoF/power scales;
%   they do not change AGSI++, SG/IBR equations, or case limits.
%
%   This policy is a PROTOTYPE contract, not a production-readiness claim.

policy = struct();
policy.schema = 'et_fcs_policy/1.0';
policy.classification = 'PROJECT_DERIVED_PROTOTYPE';
policy.frozen_at = '2026-08-04-before-closed-loop-comparison';
policy.rationale = struct( ...
    'prediction_horizon','0.25 s spans the 0.10 s on-dwell and immediate converter transient', ...
    'normalization','reuses AGSI++ engineering scales where applicable', ...
    'weights','constraint-first soft ranking with voltage/current dominant');

policy.prediction_horizon = 0.25;
policy.prediction_time_tol = 1e-9;
policy.allow_diagnostic_callback = false;
policy.normalization = struct( ...
    'voltage',0.10, ...       % pu, AGSI++ voltage scale
    'frequency',0.50, ...     % Hz, AGSI++ frequency scale
    'rocof',1.00, ...         % Hz/s, AGSI++ RoCoF scale
    'reserve_p',0.20, ...     % pu, active-power engineering scale
    'reserve_q',0.20, ...     % pu, matching reactive reserve scale
    'handback_p',0.20, ...
    'handback_q',0.20, ...
    'handback_i',0.10, ...
    'handback_theta',10.0);   % electrical degrees
policy.targets = struct('voltage',1.0,'frequency',60.0, ...
    'reserve_p',0.10,'reserve_q',0.10);
policy.weights = struct( ...
    'voltage',0.20, ...
    'frequency',0.15, ...
    'rocof',0.10, ...
    'reserve_p',0.10, ...
    'reserve_q',0.05, ...
    'current',0.20, ...
    'handback',0.10, ...
    'n_gfm',0.05, ...
    'n_switch',0.05);
policy.cost_quantization = 1e-10;

policy.bo = struct( ...
    'classification','ASSUMED_DIAGNOSTIC_OFFLINE_REPLAY', ...
    'budget',8, ...
    'n_initial',3, ...
    'kernel_length',1.5, ...
    'nugget',1e-8, ...
    'failure_penalty',100.0, ...
    'ei_tolerance',1e-14);
end
