function status = ibr_status_snapshot(stage,t,dae,event_context,active_indices,kcl_norm)
%IBR_STATUS_SNAPSHOT Index-derived mixed-resource runtime status.
%   Resource identity, state ranges, modes, and online flags are derived
%   from the assembled device index map. This metadata never selects a
%   device from a bus number, field order, or implicit first-device fallback.

arguments
    stage {mustBeTextScalar}
    t (1,1) double {mustBeFinite}
    dae struct
    event_context struct
    active_indices double = []
    kcl_norm (1,1) double = NaN
end

if ~isfield(dae,'devices') || ~isfield(dae,'device_offsets')
    error('stability:ibr_status_snapshot:badDae', ...
        'dae.devices and dae.device_offsets are required.');
end
if ~isfield(event_context,'hybrid_state') || ...
        ~isfield(event_context.hybrid_state,'device_modes') || ...
        ~isfield(event_context.hybrid_state,'device_online')
    error('stability:ibr_status_snapshot:badContext', ...
        'event_context.hybrid_state mode/online maps are required.');
end

nd = numel(dae.devices);
entries = repmat(entry_template(),nd,1);
for k = 1:nd
    dev = dae.devices(k);
    key = matlab.lang.makeValidName(char(dev.device_id), ...
        'ReplacementStyle','underscore');
    if ~isfield(event_context.hybrid_state.device_modes,key) || ...
            ~isfield(event_context.hybrid_state.device_online,key)
        error('stability:ibr_status_snapshot:missingDevice', ...
            'Hybrid state lacks device %s.',dev.device_id);
    end
    global_range = dae.device_offsets(k)+(1:dev.nx);
    active_global = intersect(global_range,active_indices(:)','stable');
    resource_type = char(dev.device_type);
    if isfield(dev,'capabilities') && isfield(dev.capabilities,'resource_type')
        resource_type = char(dev.capabilities.resource_type);
    end
    entries(k) = struct( ...
        'device_index',k,'device_id',char(dev.device_id), ...
        'resource_type',lower(resource_type),'bus_id',dev.bus_id, ...
        'bus_position',dev.bus_position,'mode', ...
        char(event_context.hybrid_state.device_modes.(key)), ...
        'online',logical(event_context.hybrid_state.device_online.(key)), ...
        'nx',dev.nx,'state_start',global_range(1), ...
        'state_end',global_range(end), ...
        'active_local_indices',active_global-dae.device_offsets(k), ...
        'active_global_indices',active_global, ...
        'state_names',{reshape(cellstr(string(dev.state_names)),1,[])});
end

online = [entries.online];
types = {entries.resource_type};
modes = {entries.mode};
is_sg = online & strcmpi(types,'sg');
is_gfm = online & strcmpi(modes,'gfm');
is_gfl = online & strcmpi(modes,'gfl');

status = struct( ...
    'stage',char(stage),'t',t,'n_devices',nd, ...
    'n_online',sum(online),'n_sg_online',sum(is_sg), ...
    'n_gfm',sum(is_gfm),'n_gfl',sum(is_gfl), ...
    'sg_online_indices',find(is_sg),'gfm_indices',find(is_gfm), ...
    'gfl_indices',find(is_gfl),'device_indices',1:nd, ...
    'device_ids',{{entries.device_id}},'device_modes',{modes}, ...
    'device_online',online,'device_entries',entries, ...
    'active_state_indices',active_indices(:)', ...
    'active_state_count',numel(active_indices), ...
    'total_state_count',sum([entries.nx]),'kcl_norm',kcl_norm);
end

function e = entry_template()
e = struct('device_index',0,'device_id','','resource_type','', ...
    'bus_id',NaN,'bus_position',NaN,'mode','','online',false,'nx',0, ...
    'state_start',0,'state_end',0,'active_local_indices',[], ...
    'active_global_indices',[],'state_names',{{}});
end
