function result = multicase_sssa(case_data, options)
%MULTICASE_SSSA Dispatch a case to its parameter-driven SSSA model plugin.

if nargin < 1 || isempty(case_data)
    error('multicase_sssa:caseRequired', 'case_data is required.');
end
if nargin < 2 || isempty(options), options=struct(); end

if isfield(case_data,'bus_data') && isfield(case_data,'machines') && ...
        isfield(case_data.machines,'reactances') && ...
        isfield(case_data.machines.reactances,'Xdpp')
    result=stability.synchronous_flux_ssa(case_data,options);
    result.metadata.plugin='primitive_flux_sixth_order';
elseif all(isfield(case_data,{'Ybus','V','theta','gen_buses','Xd','Xdp'}))
    lin=stability.sauer_pai_linearization(case_data);
    ng=lin.ng; ns=lin.ns;
    model=struct('x0',lin.x0,'y0',0, ...
        'f',@(x,y) zeros(ns*ng,1),'g',@(x,y) 0, ...
        'Jxx',lin.A,'Jxy',zeros(ns*ng,1), ...
        'Jyx',zeros(1,ns*ng),'Jyy',1,'free_y',1, ...
        'reduction','coi','ng',ng,'states_per_machine',ns, ...
        'angle_state_index',1,'speed_state_index',2,'inertia',lin.H, ...
        'metadata',struct('engine','stability.multimachine_ssa', ...
            'plugin','sauer_pai_two_axis_ieee_type1', ...
            'benchmark',char(case_data.name)));
    result=stability.multimachine_ssa(model);
    result.linearization=lin;
else
    error('multicase_sssa:unsupportedCase', ...
        'No SSSA model plugin recognizes this case schema.');
end
end
