function report=ne39_voltage_observation(t,vm,bus_ids,bounds)
%NE39_VOLTAGE_OBSERVATION รายงาน excursion/recovery จาก sample จริง ไม่ตั้งเกณฑ์ใหม่.
arguments
    t (1,:) double {mustBeFinite,mustBeReal}
    vm (:,:) double {mustBeFinite,mustBeReal,mustBeNonnegative}
    bus_ids (:,1) double {mustBeFinite,mustBeReal}
    bounds (1,1) struct
end
if isempty(t) || size(vm,2)~=numel(t) || size(vm,1)~=numel(bus_ids) || any(diff(t)<0)
    error('stability:ne39_voltage_observation:dimensions','sample dimensions/time ไม่ถูกต้อง');
end
validateattributes(bounds.v_min,{'numeric'},{'scalar','real','finite','positive'});
validateattributes(bounds.v_max,{'numeric'},{'scalar','real','finite','positive','>',bounds.v_min});
out=vm<bounds.v_min | vm>bounds.v_max;
report=struct('bounds_pu',[bounds.v_min bounds.v_max], ...
    'classification','PROJECT_OPERATING_REFERENCE_NOT_TRANSIENT_CERTIFICATE', ...
    'scope','SAMPLED_EXCURSIONS_LEFT_HOLD_DURATION_NOT_INTERSAMPLE_PROOF', ...
    'voltage_min_pu',min(vm,[],'all'),'voltage_max_pu',max(vm,[],'all'), ...
    'any_excursion',any(out,'all'),'final_all_in_band',~any(out(:,end)), ...
    'bus_ids',bus_ids,'bus_min_pu',min(vm,[],2),'bus_max_pu',max(vm,[],2), ...
    'outside_duration_left_hold_s',out(:,1:end-1)*diff(t)', ...
    'final_in_band_since_sample_s',NaN,'final_in_band_sampled_span_s',0, ...
    'excursions',struct('bus_id',{},'first_outside_sample_s',{}, ...
    'entry_bracket_s',{},'last_outside_sample_s',{},'recovery_sample_s',{}, ...
    'exit_bracket_s',{},'duration_left_hold_s',{},'min_pu',{},'max_pu',{}, ...
    'left_censored',{},'right_censored',{}));
if report.final_all_in_band
    last_out=find(any(out,1),1,'last');
    first_in=1; if ~isempty(last_out), first_in=last_out+1; end
    report.final_in_band_since_sample_s=t(first_in);
    report.final_in_band_sampled_span_s=t(end)-t(first_in);
end
for k=1:numel(bus_ids)
    starts=find(diff([false out(k,:)])==1);
    stops=find(diff([out(k,:) false])==-1);
    for j=1:numel(starts)
        a=starts(j); b=stops(j); recovery=NaN; exit=[t(b) NaN];
        if b<numel(t), recovery=t(b+1); exit(2)=recovery; end
        duration=sum(diff(t(a:min(b+1,numel(t)))));
        row=struct('bus_id',bus_ids(k),'first_outside_sample_s',t(a), ...
            'entry_bracket_s',[t(max(1,a-1)) t(a)],'last_outside_sample_s',t(b), ...
            'recovery_sample_s',recovery,'exit_bracket_s',exit, ...
            'duration_left_hold_s',duration,'min_pu',min(vm(k,a:b)), ...
            'max_pu',max(vm(k,a:b)),'left_censored',a==1,'right_censored',b==numel(t));
        report.excursions(end+1)=row;
    end
end
end
