function result = padiyar_model11_ssa(case_data, options)
%PADIYAR_MODEL11_SSA SSSA for Padiyar model 1.1, manual or AVR excitation.
if nargin<1 || isempty(case_data), case_data=cases.case_padiyar_two_area_4m_avr(); end
if nargin<2 || isempty(options), options=struct(); end
if ~isfield(options,'fd_eps'), options.fd_eps=1e-6; end
dae=stability.padiyar_model11_dae(case_data,options);
model=struct('x0',dae.x0,'y0',dae.y0,'f',dae.dae_f, ...
    'g',@(x,y) dae.dae_g(x,y,dae.Ynet),'fd_eps',options.fd_eps, ...
    'free_y',1:numel(dae.y0),'reduction','none', ...
    'ng',dae.ng,'states_per_machine',dae.ns, ...
    'angle_state_index',1,'speed_state_index',2, ...
    'inertia',dae.units.H,'state_names',{dae.state_names}, ...
    'metadata',struct('engine','stability.multimachine_ssa', ...
        'model','Padiyar model 1.1','excitation',dae.excitation));
result=stability.multimachine_ssa(model);
result.dae=dae; result.pf=dae.pf; result.initial_residual=dae.initial_residual;
result.excitation=dae.excitation; result.reference=case_data.reference;
shift=zeros(size(dae.x0)); shift(1:dae.ns:end)=1;
result.angle_shift_residual=norm(result.Afull*shift,inf);
end
