function options = common_options(tolerance)
%COMMON_OPTIONS Build a base solver options struct.

options = struct( ...
    'tolerance', tolerance, ...
    'plot_results', false, ...
    'verbose', false);
end
