function reg = equation_register()
%EQUATION_REGISTER  Single tracked structured source for report equation provenance.
%   REG = equation_register() returns a struct array whose entries are the
%   provenance rows for every numbered equation in the canonical report
%   docs/source/report_system_methods_update.tex. The report's generated
%   artifacts (equation_provenance.csv, table_equation_provenance.tex,
%   table_symbol_dictionary.tex, table_source_input_provenance.tex,
%   table_equation_code_mapping.tex, equation_source_gaps.tex) are ALL
%   generated from this one source by equation_register_export.m, so the
%   register is never maintained independently in several documents.
%
%   Field set (mission §B): equation_id, report_section, equation_name,
%   classification, physical_or_numerical_purpose, dependent_variable,
%   differential_states, algebraic_variables, inputs, parameters, units,
%   per_unit_base, sign_convention, reference_frame, current_direction,
%   assumptions, source_author, source_title, edition_year, chapter_section,
%   printed_page, PDF_page_index, source_equation_number, DOI_ISBN_URL,
%   source_notation, project_notation, transformation_derivation,
%   production_function, production_file, test_or_oracle, readiness_status,
%   limitation, theory_runtime_label.
%
%   Allowed classifications: SOURCE_VERBATIM, SOURCE_TRANSFORMED,
%   CASE_DEFINED, PROJECT_DERIVED, NUMERICAL_METHOD, ASSUMED_DIAGNOSTIC,
%   UNSOURCED, EQUATION_LOCATION_PENDING. Only the first five may support an
%   authoritative production/validation claim.
%
%   Theory+Runtime labels: THEORY_FOUNDATION, RUNTIME_EQUATION,
%   RUNTIME_DERIVATION, RUNTIME_MODEL_INTERFACE, VALIDATION_ORACLE,
%   CASE_INPUT, DIAGNOSTIC_ONLY, UNSOURCED_NOT_READY.
%
%   Code-trace evidence (set BEFORE viewing results):
%     - Classical swing: classical_dae.m:116  dx=[ws*(w-1); (Pm-Pe-D*(w-1))./(2*H)]
%     - EMF6 swing:      synchronous_emf6_ssa.m:158-159  dx(ii+1)=w0*w; dx(ii+2)=(Tm-Te-D*w)/(2*H)
%     - Padiyar swing:   padiyar_model11_dae.m:128-129  dx(ii+1)=wB*(omega-1); dx(ii+2)=(Pm-Te-D*(omega-1))/(2*H)
%     - Trapezoidal:     ts_step_kernel.m:78,163  x_new = x + 0.5*h*(f0+f1)
%     - Corrector resid: ts_step_kernel.m:82,165  R = x_new - x - 0.5*h*(f0+f(x_new,y_new))
%     - PF Newton:       powerflow_newton_raphson.m:212,228  delta_x=J\mismatch; x=x+delta_x
%     - PF stop:         powerflow_newton_raphson.m:170  max_mismatch < tolerance
%     - Ybus tap:        classical_dae.m:229-233  a=tap*exp(1i*shift); Y(i,i)+=y/(a*conj(a))
%     - Const-Z load:    classical_dae.m:51, padiyar_model11_dae.m:203  Yload=conj(S)./|V0|^2
%     - SSSA Schur:      multimachine_ssa.m:44  Afull=Jxx-Jxy(:,free_y)*(Jyy(free_y,free_y)\Jyx(free_y,:))
%     - freq/damping:    multimachine_ssa.m:67-68
%     - FD Jacobian:     synchronous_emf6_ssa.m:216-227, multimachine_ssa.m:79-94  central diff
%     - Adaptive /3:     ts_adaptive_driver.m:44,134  denom=2^p-1=3; e=(x_hh-x_f)/denom
%     - Weighted RMS:    ts_adaptive_driver.m:138  err_x=sqrt(mean((e./sc_x).^2))
%     - e_y not /3:      ts_adaptive_driver.m:141  e_y=(y_hh-y_f)  (no /3)
%     - Controller:      ts_adaptive_driver.m:42-53,197-234  fac=0.9,fac_min=0.2,fac_max=5.0,exp=1/3,reject h/2
%
%   Gaps marked NOT_READY are reported in equation_source_gaps.tex and kept
%   out of production-validation conclusions.

reg = [
% =========================================================================
% PF chain (PF-01 .. PF-19)
% =========================================================================
eq('PF-01','4','Per-unit base definitions', ...
  'SOURCE_VERBATIM','NUMERICAL_METHOD', ...
  'Define impedance and current bases from S_base and V_base so all per-unit quantities are dimensionless.', ...
  'Z_base, I_base','none','none','S_base, V_base','pu','S_base (MVA), V_base (kV LL)', ...
  'passive sign; injection positive','phase (a) reference','network into bus', ...
  'balanced three-phase; per-unit on three-phase base', ...
  'Bergen & Vittal','Power Systems Analysis','2nd ed.','2.2','29','--','Eq 2.7-2.8','--', ...
  'Z_base=V_base^2/S_base; I_base=S_base/V_base','identical (project uses three-phase S_base, line-line V_base)', ...
  'pf_prepare_case / base_values','+pfsolver/powerflow_newton_raphson.m (via pf_prepare_case)','test_matpower6_case14','VERIFIED', ...
  'Line-to-line/three-phase factors implicit in S_base (three-phase) and V_base (LL).', ...
  'CASE_INPUT');

eq('PF-02','4','Series branch admittance', ...
  'SOURCE_VERBATIM','NUMERICAL_METHOD', ...
  'Convert series R+jX branch to admittance for Ybus assembly.', ...
  'y_ik','none','none','r_ik, x_ik','pu on S_base/V_base','pu', ...
  'passive','phase reference','network into bus', ...
  'single-phase equivalent of balanced three-phase; series branch only', ...
  'Bergen & Vittal','Power Systems Analysis','2nd ed.','2.3','--','--','Eq 2.11','--', ...
  'y_ik=1/(r_ik+jx_ik)','identical', ...
  'build_ybus_from_mpc / network_model','+stability/classical_dae.m, +stability/padiyar_model11_dae.m, +stability/synchronous_emf6_ssa.m','test_matpower6_case14','VERIFIED', ...
  'Off for zero-impedance lines (case validation rejects them).', ...
  'RUNTIME_EQUATION');

eq('PF-03','4','Transformer tap/phase-shift contribution', ...
  'SOURCE_TRANSFORMED','NUMERICAL_METHOD', ...
  'Off-nominal tap and phase shift modify Ybus diagonal/off-diagonal entries.', ...
  'Y_ii, Y_ij','none','none','tap, shift, r, x','pu','pu', ...
  'passive','phase reference','network into bus', ...
  'off-nominal tap; complex tap a=tap*exp(j*shift)', ...
  'Bergen & Vittal','Power Systems Analysis','2nd ed.','2.3','--','--','Eq 2.13-2.15','--', ...
  'Y_ii += y/(a*conj(a)); Y_ij -= y/conj(a); Y_ji -= y/a; Y_jj += y', ...
  'project uses a=tap*exp(1i*deg2rad(shift)); Y(i,i)+=y/(a*conj(a))+1i*b/2; Y(i,j)-=y/conj(a)', ...
  'build_ybus_from_mpc','+stability/classical_dae.m','test_matpower6_case14','VERIFIED', ...
  'Phase shift in degrees converted to rad; half-line charging b/2 added to both ends.', ...
  'RUNTIME_EQUATION');

eq('PF-04','4','Shunt and line-charging contributions', ...
  'SOURCE_VERBATIM','NUMERICAL_METHOD', ...
  'Bus shunt admittance and half-line charging added to Ybus diagonal.', ...
  'Y_ii','none','none','G_sh, B_sh, b_half','pu','pu', ...
  'passive','phase reference','network into bus', ...
  'pi-model branch; shunt at bus', ...
  'Bergen & Vittal','Power Systems Analysis','2nd ed.','2.3','--','--','Eq 2.12','--', ...
  'Y_ii += G_sh + jB_sh; Y_ii += j*b/2 (each line end)', ...
  'Y(i,i)+=ys+1i*bh; Y(b,b)+=BD(b,9)+1i*BD(b,10)', ...
  'build_ybus_from_mpc / network_model','+stability/classical_dae.m, +stability/padiyar_model11_dae.m','test_matpower6_case14','VERIFIED', ...
  'Shunt columns 9-10 of bus_data; half-line charging column 5 of line_data.', ...
  'RUNTIME_EQUATION');

eq('PF-05','4','Ybus assembly', ...
  'PROJECT_DERIVED','NUMERICAL_METHOD', ...
  'Assemble full bus admittance matrix from branches, taps, shunts, charging.', ...
  'Y_bus','none','none','all branch/shunt data','pu','pu', ...
  'passive; injection positive','phase reference','network into bus', ...
  'linear, balanced, passive network', ...
  'Bergen & Vittal','Power Systems Analysis','2nd ed.','2.3','--','--','Eq 2.16','--', ...
  'Y_ii = sum of branch admittances + shunts; Y_ij = -branch admittance', ...
  'diagonal accumulates y/(a*conj(a))+shunt+charging; off-diagonal -y/conj(a)', ...
  'build_ybus_from_mpc','+stability/classical_dae.m','test_matpower6_case14','VERIFIED', ...
  'Symmetric for non-phase-shifting branches; Hermitian structure preserved.', ...
  'RUNTIME_EQUATION');

eq('PF-06','4','Network current equation', ...
  'SOURCE_VERBATIM','NUMERICAL_METHOD', ...
  'Relate bus voltages to injected currents via Ybus.', ...
  'I','none','V','Y_bus','pu','pu', ...
  'injection positive into bus','phase reference','network into bus', ...
  'linear network; sinusoidal steady state', ...
  'Bergen & Vittal','Power Systems Analysis','2nd ed.','2.4','--','--','Eq 2.17','--', ...
  'I = Y_bus * V','identical (classical_dae solves V=Y\I, i.e. I=Y*V)', ...
  'solve_network_linear / network_residual','+stability/classical_dae.m, +stability/synchronous_emf6_ssa.m','test_matpower6_case14','VERIFIED', ...
  'Classical: V=(Y+Ygen)\Iinj. EMF6/Padiyar: residual g=Iinj-Y*V=0.', ...
  'RUNTIME_EQUATION');

eq('PF-07','4','Complex power convention', ...
  'SOURCE_VERBATIM','NUMERICAL_METHOD', ...
  'Define complex power injection at a bus from voltage and current.', ...
  'S_i','none','V_i, I_i','none','pu on S_base','pu', ...
  'injection positive; S=P+jQ','phase reference','network into bus', ...
  'sinusoidal steady state; conjugation gives P+jQ into bus', ...
  'Bergen & Vittal','Power Systems Analysis','2nd ed.','2.4','--','--','Eq 2.18','--', ...
  'S_i = V_i * conj(I_i)','identical (Pe(k)=real(V(b)*conj(Ig(k))) in classical_dae.m:145)', ...
  'powerflow_newton_raphson / electrical_power','+stability/classical_dae.m','test_matpower6_case14','VERIFIED', ...
  'Generator Pe uses same convention: Pe=real(V*conj(Ig)).', ...
  'RUNTIME_EQUATION');

eq('PF-08','4','Expanded active-power injection', ...
  'SOURCE_TRANSFORMED','NUMERICAL_METHOD', ...
  'Active power injection at bus i in terms of voltages and Ybus elements.', ...
  'P_i','none','V, theta','G, B','pu','pu', ...
  'injection positive','phase reference','network into bus', ...
  'sinusoidal steady state; Y=G+jB', ...
  'Bergen & Vittal','Power Systems Analysis','2nd ed.','2.4','--','--','Eq 2.19','--', ...
  'P_i = sum_k |V_i||V_k|(G_ik cos(theta_ik)+B_ik sin(theta_ik))', ...
  'identical (pf_calculate_mismatch evaluates P_calc from V,theta,G,B)', ...
  'pf_calculate_mismatch','+pfsolver/powerflow_newton_raphson.m:148','test_matpower6_case14','VERIFIED', ...
  'theta_ik = theta_i - theta_k.', ...
  'RUNTIME_EQUATION');

eq('PF-09','4','Expanded reactive-power injection', ...
  'SOURCE_TRANSFORMED','NUMERICAL_METHOD', ...
  'Reactive power injection at bus i.', ...
  'Q_i','none','V, theta','G, B','pu','pu', ...
  'injection positive','phase reference','network into bus', ...
  'sinusoidal steady state; Y=G+jB', ...
  'Bergen & Vittal','Power Systems Analysis','2nd ed.','2.4','--','--','Eq 2.20','--', ...
  'Q_i = sum_k |V_i||V_k|(G_ik sin(theta_ik)-B_ik cos(theta_ik))', ...
  'identical (pf_calculate_mismatch evaluates Q_calc)', ...
  'pf_calculate_mismatch','+pfsolver/powerflow_newton_raphson.m:148','test_matpower6_case14','VERIFIED', ...
  'Sign of B term negative (capacitive).', ...
  'RUNTIME_EQUATION');

eq('PF-10','4','Scheduled net injection', ...
  'PROJECT_DERIVED','NUMERICAL_METHOD', ...
  'Net scheduled injection = generation minus load at a bus.', ...
  'P_spec, Q_spec','none','P_gen, P_load, Q_gen, Q_load','none','pu','pu', ...
  'generation positive, load negative','phase reference','network into bus', ...
  'mixed gen/load at one bus handled by net injection', ...
  'Bergen & Vittal','Power Systems Analysis','2nd ed.','2.4','--','--','Eq 2.21','--', ...
  'P_spec=P_gen-P_load; Q_spec=Q_gen-Q_load', ...
  'identical (pf_prepare_case computes net injection)', ...
  'pf_prepare_case','+pfsolver/powerflow_newton_raphson.m','test_matpower6_case14','VERIFIED', ...
  'PV bus with local demand uses net injection; no special bus type needed.', ...
  'RUNTIME_EQUATION');

eq('PF-11','4','Mismatch vector', ...
  'PROJECT_DERIVED','NUMERICAL_METHOD', ...
  'Difference between scheduled and calculated injections drives Newton iteration.', ...
  'mismatch','none','P_spec, Q_spec, P_calc, Q_calc','none','pu','pu', ...
  'injection positive','phase reference','network into bus', ...
  'Newton method requires residual', ...
  'Bergen & Vittal','Power Systems Analysis','2nd ed.','2.5','--','--','Eq 2.22','--', ...
  'mismatch = [P_spec-P_calc; Q_spec-Q_calc]', ...
  'identical (pf_calculate_mismatch returns mismatch)', ...
  'pf_calculate_mismatch','+pfsolver/powerflow_newton_raphson.m:148','test_matpower6_case14','VERIFIED', ...
  'REF bus excluded; PV Q excluded (Q is output).', ...
  'RUNTIME_EQUATION');

eq('PF-12','4','Newton linearization', ...
  'SOURCE_VERBATIM','NUMERICAL_METHOD', ...
  'Linearize mismatch around current state to get Newton correction.', ...
  'delta_x','none','mismatch, J','none','pu','pu', ...
  'injection positive','phase reference','network into bus', ...
  'small-signal linearization; first-order Taylor', ...
  'Bergen & Vittal','Power Systems Analysis','2nd ed.','2.5','--','--','Eq 2.23','--', ...
  'J * [dtheta; d|V|] = [dP; dQ]', ...
  'identical (delta_x = J \ mismatch)', ...
  'solve_model','+pfsolver/powerflow_newton_raphson.m:212','test_matpower6_case14','VERIFIED', ...
  'Backslash, no explicit inverse.', ...
  'RUNTIME_EQUATION');

eq('PF-13','4','Four Jacobian blocks', ...
  'SOURCE_TRANSFORMED','NUMERICAL_METHOD', ...
  'Partial derivatives of P,Q w.r.t. theta, |V| forming H,N,M,L blocks.', ...
  'H,N,M,L','none','V, theta, G, B','none','pu','pu', ...
  'injection positive','phase reference','network into bus', ...
  'analytic derivatives of PF-08/09', ...
  'Bergen & Vittal','Power Systems Analysis','2nd ed.','2.5','--','--','Eq 2.24-2.27','--', ...
  'H=dP/dtheta, N=dP/d|V|, M=dQ/dtheta, L=dQ/d|V|', ...
  'identical (pf_build_jacobian assembles J from V,delta,P_calc,Q_calc)', ...
  'pf_build_jacobian','+pfsolver/powerflow_newton_raphson.m:180','test_matpower6_case14','VERIFIED', ...
  'Diagonal and off-diagonal forms per Bergen Eq 2.24-2.27.', ...
  'RUNTIME_EQUATION');

eq('PF-14','4','State update and stopping rule', ...
  'PROJECT_DERIVED','NUMERICAL_METHOD', ...
  'Update voltage state and stop when mismatch below tolerance.', ...
  'x','none','delta_x, mismatch, tolerance','none','pu','pu', ...
  'injection positive','phase reference','network into bus', ...
  'Newton iteration converges quadratically near solution', ...
  'Bergen & Vittal','Power Systems Analysis','2nd ed.','2.5','--','--','Eq 2.28','--', ...
  'x = x + delta_x; stop when max|mismatch| < tolerance', ...
  'identical (x=x+delta_x; break if max_mismatch<tolerance)', ...
  'solve_model','+pfsolver/powerflow_newton_raphson.m:170,228','test_matpower6_case14','VERIFIED', ...
  'Default tolerance 1e-6; max_iter 20.', ...
  'RUNTIME_EQUATION');

eq('PF-15','4','PV reactive-power recovery and PV-to-PQ switching', ...
  'PROJECT_DERIVED','NUMERICAL_METHOD', ...
  'Recover Q at PV buses; switch to PQ if Q violates limits.', ...
  'Q_gen','none','V, Y, Qmin, Qmax','none','pu','pu', ...
  'generation positive','phase reference','network into bus', ...
  'PV bus Q is output; limits enforced iteratively', ...
  'Bergen & Vittal','Power Systems Analysis','2nd ed.','2.5','--','--','Eq 2.29','--', ...
  'Q_gen computed from solved V; if Q>Qmax set Q=Qmax and switch PV->PQ', ...
  'identical (find_q_limit_violations + bus_data type switch)', ...
  'find_q_limit_violations','+pfsolver/powerflow_newton_raphson.m:290-308','test_matpower6_case14','VERIFIED', ...
  'Iterative outer loop; max_q_limit_switches=20.', ...
  'RUNTIME_EQUATION');

eq('PF-16','4','Slack-bus power recovery', ...
  'PROJECT_DERIVED','NUMERICAL_METHOD', ...
  'Recover P,Q at slack bus from solved voltages.', ...
  'P_slack, Q_slack','none','V, Y','none','pu','pu', ...
  'generation positive','phase reference','network into bus', ...
  'REF bus P,Q are outputs', ...
  'Bergen & Vittal','Power Systems Analysis','2nd ed.','2.5','--','--','Eq 2.30','--', ...
  'P_slack = sum_k |V_s||V_k|(G_sk cos+...); same for Q', ...
  'identical (pf_build_results computes slack P,Q from V)', ...
  'pf_build_results','+pfsolver/powerflow_newton_raphson.m','test_matpower6_case14','VERIFIED', ...
  'Slack bus angle=0, |V| specified.', ...
  'RUNTIME_EQUATION');

eq('PF-17','4','Branch sending/receiving currents and powers', ...
  'SOURCE_TRANSFORMED','NUMERICAL_METHOD', ...
  'Compute branch flows from bus voltages and branch admittance.', ...
  'S_ij','none','V_i, V_j, y_ij','none','pu','pu', ...
  'sending end positive','phase reference','network into bus', ...
  'pi-model branch', ...
  'Bergen & Vittal','Power Systems Analysis','2nd ed.','2.6','--','--','Eq 2.31','--', ...
  'I_ij = y_ij*(V_i - V_j) + j*b/2*V_i; S_ij = V_i*conj(I_ij)', ...
  'identical (pf_build_results computes branch flows)', ...
  'pf_build_results','+pfsolver/powerflow_newton_raphson.m','test_matpower6_case14','VERIFIED', ...
  'Includes half-line charging at each end.', ...
  'RUNTIME_EQUATION');

eq('PF-18','4','Active/reactive losses', ...
  'PROJECT_DERIVED','NUMERICAL_METHOD', ...
  'Total network losses = sum of branch losses.', ...
  'P_loss, Q_loss','none','S_ij','none','pu','pu', ...
  'loss positive','phase reference','network into bus', ...
  'loss = sum over branches of (S_ij + S_ji)', ...
  'Bergen & Vittal','Power Systems Analysis','2nd ed.','2.6','--','--','Eq 2.32','--', ...
  'P_loss = sum Re(S_ij+S_ji); Q_loss = sum Im(S_ij+S_ji)', ...
  'identical (pf_build_results computes P_loss_total)', ...
  'pf_build_results','+pfsolver/powerflow_newton_raphson.m','test_matpower6_case14','VERIFIED', ...
  'Reported as P_loss_total in pu (x100 for MW on S_base=100).', ...
  'RUNTIME_EQUATION');

eq('PF-19','4','Power-balance residual', ...
  'PROJECT_DERIVED','NUMERICAL_METHOD', ...
  'Verify total generation = total load + total loss at convergence.', ...
  'balance','none','P_gen, P_load, P_loss','none','pu','pu', ...
  'injection positive','phase reference','network into bus', ...
  'Kirchhoff current law at network level', ...
  'Bergen & Vittal','Power Systems Analysis','2nd ed.','2.6','--','--','Eq 2.33','--', ...
  'P_gen_total = P_load_total + P_loss_total', ...
  'identical (pf_build_results reports all three)', ...
  'pf_build_results','+pfsolver/powerflow_newton_raphson.m','test_matpower6_case14','VERIFIED', ...
  'Used as convergence sanity check, not acceptance gate.', ...
  'VALIDATION_ORACLE');

% =========================================================================
% SG classical chain (SG-C-01 .. SG-C-12)
% =========================================================================
eq('SG-C-01','5.1','Rotor electrical angle definition', ...
  'PROJECT_DERIVED','RUNTIME_EQUATION', ...
  'Define rotor angle of machine i relative to synchronous reference.', ...
  'delta_i','delta','none','none','rad','machine base', ...
  'machine into network','rotor dq frame','machine into network', ...
  'classical machine; rotor angle = angle of internal EMF', ...
  'Bergen & Vittal','Power Systems Analysis','2nd ed.','7.2','--','--','Eq 7.5','--', ...
  'delta_i = angle(E_i)','identical (delta0(k)=angle(E0(k)) in classical_dae.m:61)', ...
  'classical_dae','+stability/classical_dae.m:61','test_ts_characterization_fixed','VERIFIED', ...
  'Electrical radians; relative to slack bus angle.', ...
  'RUNTIME_EQUATION');

eq('SG-C-02','5.1','Speed-base relationship', ...
  'PROJECT_DERIVED','RUNTIME_EQUATION', ...
  'Relate per-unit speed to angular frequency via base.', ...
  'omega_b','omega','none','f','rad/s','system base', ...
  'machine into network','rotor dq frame','machine into network', ...
  'synchronous speed = 2*pi*f', ...
  'Bergen & Vittal','Power Systems Analysis','2nd ed.','7.2','--','--','Eq 7.6','--', ...
  'omega_b = 2*pi*f','identical (ws=2*pi*freq in classical_dae.m:39)', ...
  'classical_dae','+stability/classical_dae.m:39','test_ts_characterization_fixed','VERIFIED', ...
  'f from case base_values.frequency_Hz.', ...
  'CASE_INPUT');

eq('SG-C-03','5.1','Mechanical torque/power balance', ...
  'SOURCE_TRANSFORMED','RUNTIME_EQUATION', ...
  'Newton second law for rotation: accelerating power = inertia * acceleration.', ...
  'Pm, Pe','omega','none','H, D','pu','machine base', ...
  'machine into network','rotor dq frame','machine into network', ...
  'classical machine; mechanical input minus electrical output', ...
  'Bergen & Vittal','Power Systems Analysis','2nd ed.','7.2','--','--','Eq 7.7','--', ...
  '2H*domega/dt = Pm - Pe - D*(omega-1)', ...
  'identical (swing_rhs in classical_dae.m:116)', ...
  'classical_dae / swing_rhs','+stability/classical_dae.m:116','test_ts_characterization_fixed','VERIFIED', ...
  '2H in denominator (NOT H); D is damping coefficient.', ...
  'RUNTIME_EQUATION');

eq('SG-C-04','5.1','Inertia constant definition', ...
  'SOURCE_VERBATIM','CASE_INPUT', ...
  'H = stored kinetic energy at rated speed / rated MVA base.', ...
  'H','none','none','S_machine','s','machine base', ...
  'machine into network','rotor dq frame','machine into network', ...
  'rated operation', ...
  'Bergen & Vittal','Power Systems Analysis','2nd ed.','7.2','--','--','Eq 7.4','--', ...
  'H = (1/2)J*omega_m^2 / S_base','identical (H from case machines.units)', ...
  'expand_machines_classical','+stability/classical_dae.m:46','test_ts_characterization_fixed','VERIFIED', ...
  'H scaled to system base when machine base differs (ratio in normalize_case).', ...
  'CASE_INPUT');

eq('SG-C-05','5.1','Swing equation (delta)', ...
  'PROJECT_DERIVED','RUNTIME_EQUATION', ...
  'Rotor angle derivative from per-unit speed deviation.', ...
  'delta_i','delta, omega','none','omega_b','rad/s','machine base', ...
  'machine into network','rotor dq frame','machine into network', ...
  'classical machine; omega in pu absolute (1 at synchronous)', ...
  'Bergen & Vittal','Power Systems Analysis','2nd ed.','7.2','--','--','Eq 7.8','--', ...
  'd(delta)/dt = omega_b*(omega-1)', ...
  'identical (dx=[ws*(w-1); ...] in classical_dae.m:116)', ...
  'classical_dae / swing_rhs','+stability/classical_dae.m:116','test_ts_characterization_fixed','VERIFIED', ...
  'omega_b = 2*pi*f; omega=1 at synchronous speed.', ...
  'RUNTIME_EQUATION');

eq('SG-C-06','5.1','Damping term and units', ...
  'PROJECT_DERIVED','RUNTIME_EQUATION', ...
  'Damping power proportional to speed deviation.', ...
  'D','omega','none','D','pu','machine base', ...
  'machine into network','rotor dq frame','machine into network', ...
  'linear damping; D in pu on machine base', ...
  'Bergen & Vittal','Power Systems Analysis','2nd ed.','7.2','--','--','Eq 7.9','--', ...
  'P_damp = D*(omega-1)','identical (D.*(w-1) in classical_dae.m:116)', ...
  'classical_dae / swing_rhs','+stability/classical_dae.m:116','test_ts_characterization_fixed','VERIFIED', ...
  'D scaled to system base with H.', ...
  'RUNTIME_EQUATION');

eq('SG-C-07','5.1','Internal voltage behind transient reactance', ...
  'SOURCE_TRANSFORMED','RUNTIME_EQUATION', ...
  'Classical machine internal EMF = terminal voltage + jXdp * current.', ...
  'E_i','none','V, I, Xdp','Xdp','pu','machine base', ...
  'machine into network','rotor dq frame','machine into network', ...
  'classical machine; constant flux; Xdp transient reactance', ...
  'Bergen & Vittal','Power Systems Analysis','2nd ed.','7.3','--','--','Eq 7.13','--', ...
  'E = V + j*Xdp*I','identical (E0(k)=V0(b)+1i*Xdp(k)*Ig0 in classical_dae.m:60)', ...
  'classical_dae','+stability/classical_dae.m:60','test_ts_characterization_fixed','VERIFIED', ...
  'Eqmag=|E| constant during classical TS; delta=angle(E).', ...
  'RUNTIME_EQUATION');

eq('SG-C-08','5.1','Stator/current-injection equation', ...
  'PROJECT_DERIVED','RUNTIME_EQUATION', ...
  'Generator current from EMF and terminal voltage through Xdp.', ...
  'Ig','none','E, V, Xdp','Xdp','pu','machine base', ...
  'machine into network','rotor dq frame','machine into network', ...
  'classical machine; linear stator', ...
  'Bergen & Vittal','Power Systems Analysis','2nd ed.','7.3','--','--','Eq 7.14','--', ...
  'Ig = (E - V)/(j*Xdp)','identical (Ig(k)=(E-V(b))/(1i*Xdp(k)) in classical_dae.m:144)', ...
  'solve_network_linear','+stability/classical_dae.m:144','test_ts_characterization_fixed','VERIFIED', ...
  'Current positive from machine into network.', ...
  'RUNTIME_EQUATION');

eq('SG-C-09','5.1','Electrical air-gap power', ...
  'SOURCE_VERBATIM','RUNTIME_EQUATION', ...
  'Electrical power delivered to network = real(V * conj(Ig)).', ...
  'Pe','none','V, Ig','none','pu','machine base', ...
  'machine into network','rotor dq frame','machine into network', ...
  'sinusoidal steady state; air-gap power', ...
  'Bergen & Vittal','Power Systems Analysis','2nd ed.','7.3','--','--','Eq 7.15','--', ...
  'Pe = real(V * conj(Ig))','identical (Pe(k)=real(V(b)*conj(Ig(k))) in classical_dae.m:145)', ...
  'solve_network_linear','+stability/classical_dae.m:145','test_ts_characterization_fixed','VERIFIED', ...
  'Same convention as PF-07.', ...
  'RUNTIME_EQUATION');

eq('SG-C-10','5.1','Generator-to-bus injection mapping', ...
  'PROJECT_DERIVED','RUNTIME_EQUATION', ...
  'Accumulate generator currents into bus injection vector.', ...
  'Iinj','none','E, yg','yg=1/(jXdp)','pu','machine base', ...
  'machine into network','rotor dq frame','machine into network', ...
  'linear network; superposition', ...
  'Bergen & Vittal','Power Systems Analysis','2nd ed.','7.3','--','--','Eq 7.16','--', ...
  'Iinj(b) += E*yg; Yloc(b,b) += yg', ...
  'identical (Iinj(b)=Iinj(b)+E*yg; Yloc(b,b)=Yloc(b,b)+yg in classical_dae.m:136-137)', ...
  'solve_network_linear','+stability/classical_dae.m:131-138','test_ts_characterization_fixed','VERIFIED', ...
  'Generator admittance added to Ybus diagonal; current to injection vector.', ...
  'RUNTIME_EQUATION');

eq('SG-C-11','5.1','COI angle and COI speed', ...
  'PROJECT_DERIVED','DIAGNOSTIC_ONLY', ...
  'Inertia-weighted center-of-inertia reference removes common-mode motion.', ...
  'delta_COI','delta','none','H','rad','machine base', ...
  'machine into network','rotor dq frame','machine into network', ...
  'inertia-weighted average', ...
  'Bergen & Vittal','Power Systems Analysis','2nd ed.','7.4','--','--','Eq 7.20','--', ...
  'delta_COI = sum(H_i*delta_i)/sum(H_i)', ...
  'identical (coi_relative.m implements inertia-weighted COI)', ...
  'coi_relative','scripts/validation/coi_relative.m','test_coi_weighting','VERIFIED', ...
  'Used for COI-relative angle metrics; not a state variable.', ...
  'DIAGNOSTIC_ONLY');

eq('SG-C-12','5.1','Pairwise and incremental rotor-angle metrics', ...
  'PROJECT_DERIVED','DIAGNOSTIC_ONLY', ...
  'COI-relative and incremental angle removes common drift for stability assessment.', ...
  'tilde_delta_i','delta','none','H','rad','machine base', ...
  'machine into network','rotor dq frame','machine into network', ...
  'COI frame; incremental from t=0', ...
  'Bergen & Vittal','Power Systems Analysis','2nd ed.','7.4','--','--','Eq 7.21','--', ...
  'tilde_delta_i(t) = [delta_i(t)-delta_COI(t)] - [delta_i(0)-delta_COI(0)]', ...
  'identical (coi_relative.m computes incremental COI-relative)', ...
  'coi_relative','scripts/validation/coi_relative.m','test_coi_weighting','VERIFIED', ...
  'Plotted angle is delta_i(t)-delta_i(0) (PSAT delta_Syn style); stability uses COI-relative.', ...
  'DIAGNOSTIC_ONLY');

% =========================================================================
% SG Padiyar model-1.1 chain (SG-P-01 .. SG-P-06)
% =========================================================================
eq('SG-P-01','5.2','Padiyar state inventory', ...
  'CASE_DEFINED','RUNTIME_MODEL_INTERFACE', ...
  'Five states per machine: [delta, omega, Eqp, Edp, Efd] (AVR) or four (manual).', ...
  'x','delta, omega, Eqp, Edp, Efd','none','none','mixed','machine base', ...
  'machine into network','rotor dq frame','machine into network', ...
  'Padiyar model 1.1; two-axis transient machine + single-time-constant AVR', ...
  'Padiyar','Power System Dynamics: Stability and Control','2nd ed.','9.6.1','325-331','338-344','Table 9.1-9.4','--', ...
  'states [delta, omega, Eqp, Edp, Efd]','identical (padiyar_model11_dae.m:80,102,106)', ...
  'padiyar_model11_dae','+stability/padiyar_model11_dae.m:80','test_padiyar_two_area_reference','VERIFIED', ...
  'Manual excitation drops Efd state (4 states/machine).', ...
  'RUNTIME_MODEL_INTERFACE');

eq('SG-P-02','5.2','Padiyar swing equations', ...
  'SOURCE_TRANSFORMED','RUNTIME_EQUATION', ...
  'Rotor angle and speed derivatives per Padiyar model 1.1.', ...
  'delta, omega','delta, omega','none','wB, H, D, Pm, Te','rad/s, pu/s','machine base', ...
  'machine into network','rotor dq frame','machine into network', ...
  'Padiyar model 1.1; omega in pu absolute', ...
  'Padiyar','Power System Dynamics: Stability and Control','2nd ed.','9.6.1','325-331','338-344','Eq 9.x','--', ...
  'd(delta)/dt=wB*(omega-1); d(omega)/dt=(Pm-Te-D*(omega-1))/(2*H)', ...
  'identical (padiyar_model11_dae.m:128-129)', ...
  'padiyar_model11_dae / differential_residual','+stability/padiyar_model11_dae.m:128-129','test_padiyar_two_area_reference','VERIFIED', ...
  '2H in denominator; wB=2*pi*f. Verified against contract.md.', ...
  'RUNTIME_EQUATION');

eq('SG-P-03','5.2','Padiyar transient EMF equations', ...
  'SOURCE_TRANSFORMED','RUNTIME_EQUATION', ...
  'Eqp and Edp derivatives from field and q-axis dynamics.', ...
  'Eqp, Edp','Eqp, Edp','Id, Iq, Efd','Xd, Xdp, Xq, Xqp, Tpd0, Tpq0','pu/s','machine base', ...
  'machine into network','rotor dq frame','machine into network', ...
  'two-axis transient model', ...
  'Padiyar','Power System Dynamics: Stability and Control','2nd ed.','9.6.1','325-331','338-344','Eq 9.x','--', ...
  'd(Eqp)/dt=(Efd-Eqp-(Xd-Xdp)*Id)/Tpd0; d(Edp)/dt=(-Edp+(Xq-Xqp)*Iq)/Tpq0', ...
  'identical (padiyar_model11_dae.m:130-131)', ...
  'padiyar_model11_dae / differential_residual','+stability/padiyar_model11_dae.m:130-131','test_padiyar_two_area_reference','VERIFIED', ...
  'Matches contract.md dynamic equations.', ...
  'RUNTIME_EQUATION');

eq('SG-P-04','5.2','Padiyar AVR equation', ...
  'SOURCE_TRANSFORMED','RUNTIME_EQUATION', ...
  'Single-time-constant AVR: Efd derivative from voltage error.', ...
  'Efd','Efd','Vref, |Vt|','KA, TA','pu/s','machine base', ...
  'machine into network','rotor dq frame','machine into network', ...
  'first-order AVR; Vref set so operating point is equilibrium', ...
  'Padiyar','Power System Dynamics: Stability and Control','2nd ed.','9.6.1','325-331','338-344','Eq 9.x','--', ...
  'd(Efd)/dt=(KA*(Vref-|Vt|)-Efd)/TA', ...
  'identical (padiyar_model11_dae.m:133); Vref=|Vt|+Efd/KA at init (line 110)', ...
  'padiyar_model11_dae / differential_residual','+stability/padiyar_model11_dae.m:133,110','test_padiyar_two_area_reference','VERIFIED', ...
  'Manual excitation: Efd fixed at Efd0, no AVR state.', ...
  'RUNTIME_EQUATION');

eq('SG-P-05','5.2','Padiyar stator algebraic equations', ...
  'SOURCE_TRANSFORMED','RUNTIME_EQUATION', ...
  'Stator algebraic: Id, Iq from terminal voltage and EMFs.', ...
  'Id, Iq','none','Vd, Vq, Eqp, Edp','Ra, Xdp, Xqp','pu','machine base', ...
  'machine into network','rotor dq frame','machine into network', ...
  'two-axis transient; stator algebraic (neglect stator transients)', ...
  'Padiyar','Power System Dynamics: Stability and Control','2nd ed.','6','--','--','Eq 6.x','--', ...
  'Id=(-Ra*rd-Xqp*rq)/den; Iq=(Xdp*rd-Ra*rq)/den; rd=Vd-Edp; rq=Vq-Eqp; den=Ra^2+Xdp*Xqp', ...
  'identical (padiyar_model11_dae.m:153-155)', ...
  'padiyar_model11_dae / machine_algebraic','+stability/padiyar_model11_dae.m:149-156','test_padiyar_two_area_reference','VERIFIED', ...
  'dq frame per Padiyar convention (to_dq/from_dq_current).', ...
  'RUNTIME_EQUATION');

eq('SG-P-06','5.2','Padiyar network coupling', ...
  'PROJECT_DERIVED','RUNTIME_EQUATION', ...
  'Generator current injected into network bus; KCL residual.', ...
  'g','none','V, Ig','Y','pu','machine base', ...
  'machine into network','rotor dq frame','machine into network', ...
  'current balance; injection positive', ...
  'Padiyar','Power System Dynamics: Stability and Control','2nd ed.','9.6.1','325-331','338-344','Eq 9.x','--', ...
  'g = Ig - Y*V = 0','identical (network_residual: gc=-Inet; gc(b)+=Ig; g=[real;imag])', ...
  'padiyar_model11_dae / network_residual','+stability/padiyar_model11_dae.m:138-147','test_padiyar_two_area_reference','VERIFIED', ...
  'KCL sign: injection positive; residual = injection - Y*V.', ...
  'RUNTIME_EQUATION');

% =========================================================================
% SG EMF6 chain (SG-E-01 .. SG-E-07)
% =========================================================================
eq('SG-E-01','5.3','EMF6 state inventory', ...
  'CASE_DEFINED','RUNTIME_MODEL_INTERFACE', ...
  'Six states per machine: [delta, omega, Eqp, Edp, Eqpp, Edpp].', ...
  'x','delta, omega, Eqp, Edp, Eqpp, Edpp','none','none','mixed','machine base', ...
  'machine into network','rotor dq frame','machine into network', ...
  'operational sixth-order EMF; subtransient included', ...
  'Kundur','Power System Stability and Control','1st ed.','3-4','--','--','Eq 3.x','--', ...
  'states [delta, omega, Eqp, Edp, Eqpp, Edpp]','identical (synchronous_emf6_ssa.m:3,136)', ...
  'synchronous_emf6_ssa / emf6_dae','+stability/synchronous_emf6_ssa.m:3','test_emf6_model','VERIFIED', ...
  'Legacy GENTPJ/primitive-flux paths in legacy/ are NOT production.', ...
  'RUNTIME_MODEL_INTERFACE');

eq('SG-E-02','5.3','EMF6 swing equations', ...
  'SOURCE_TRANSFORMED','RUNTIME_EQUATION', ...
  'Rotor angle and speed derivatives for sixth-order model.', ...
  'delta, omega','delta, omega','none','w0, H, D, Tm, Te','rad/s, pu/s','machine base', ...
  'machine into network','rotor dq frame','machine into network', ...
  'operational EMF6; omega state stores pu speed', ...
  'Kundur','Power System Stability and Control','1st ed.','3-4','--','--','Eq 3.x','--', ...
  'd(delta)/dt=w0*omega; d(omega)/dt=(Tm-Te-D*omega)/(2*H)', ...
  'identical (synchronous_emf6_ssa.m:158-159)', ...
  'synchronous_emf6_ssa / differential_residual','+stability/synchronous_emf6_ssa.m:158-159','test_emf6_model','VERIFIED', ...
  '2H in denominator; w0=2*pi*f. Note: omega state convention differs from classical (see transformation).', ...
  'RUNTIME_EQUATION');

eq('SG-E-03','5.3','EMF6 transient/subtransient EMF equations', ...
  'SOURCE_TRANSFORMED','RUNTIME_EQUATION', ...
  'Eqp, Edp, Eqpp, Edpp derivatives with subtransient dynamics.', ...
  'Eqp, Edp, Eqpp, Edpp','Eqp, Edp, Eqpp, Edpp','Id, Iq, Efd','Xd, Xdp, Xdpp, Xq, Xqp, Xqpp, Tpd0, Tppd0, Tpq0, Tppq0, c_d, d_d, c_q, d_q','pu/s','machine base', ...
  'machine into network','rotor dq frame','machine into network', ...
  'subtransient model; c_d/d_d coefficients from reactances', ...
  'Kundur','Power System Stability and Control','1st ed.','3-4','--','--','Eq 3.x','--', ...
  'd(Eqp)=(Efd+c_d*Eqpp-d_d*Eqp)/Tpd0; d(Edp)=(c_q*Edpp-d_q*Edp)/Tpq0; d(Eqpp)=(Eqp-Eqpp-(Xdp-Xdpp)*Id)/Tppd0; d(Edpp)=(Edp-Edpp+(Xqp-Xqpp)*Iq)/Tppq0', ...
  'identical (synchronous_emf6_ssa.m:160-163)', ...
  'synchronous_emf6_ssa / differential_residual','+stability/synchronous_emf6_ssa.m:160-163','test_emf6_model','VERIFIED', ...
  'c_d=(Xd-Xdp)/(Xdp-Xdpp); d_d=(Xd-Xdpp)/(Xdp-Xdpp); similarly q (lines 86-89).', ...
  'RUNTIME_EQUATION');

eq('SG-E-04','5.3','EMF6 stator algebraic equations', ...
  'SOURCE_TRANSFORMED','RUNTIME_EQUATION', ...
  'Stator algebraic: Id, Iq from subtransient EMFs and terminal voltage.', ...
  'Id, Iq','none','Vd, Vq, Eqpp, Edpp','Ra, Xdpp, Xqpp','pu','machine base', ...
  'machine into network','rotor dq frame','machine into network', ...
  'subtransient stator; neglect stator transients', ...
  'Kundur','Power System Stability and Control','1st ed.','3-4','--','--','Eq 3.x','--', ...
  'Id=(-Ra*rd-Xqpp*rq)/det; Iq=(Xdpp*rd-Ra*rq)/det; rd=Vd-Edpp; rq=Vq-Eqpp; det=Xdpp*Xqpp+Ra^2', ...
  'identical (synchronous_emf6_ssa.m:190-193)', ...
  'synchronous_emf6_ssa / machine_algebraic','+stability/synchronous_emf6_ssa.m:186-194','test_emf6_model','VERIFIED', ...
  'dq frame via kundur_book_dq.', ...
  'RUNTIME_EQUATION');

eq('SG-E-05','5.3','EMF6 electromagnetic power', ...
  'SOURCE_VERBATIM','RUNTIME_EQUATION', ...
  'Air-gap electrical torque from dq stator variables.', ...
  'Te','none','Vd, Vq, Id, Iq, Ra','none','pu','machine base', ...
  'machine into network','rotor dq frame','machine into network', ...
  'air-gap torque; includes stator copper loss', ...
  'Kundur','Power System Stability and Control','1st ed.','3-4','--','--','Eq 3.x','--', ...
  'Te = Vd*Id + Vq*Iq + Ra*(Id^2+Iq^2)', ...
  'identical (synchronous_emf6_ssa.m:157,236; electrical_power_direct)', ...
  'synchronous_emf6_ssa / electrical_power_direct','+stability/synchronous_emf6_ssa.m:229-238','test_emf6_model','VERIFIED', ...
  'Computed directly from dq variables, NOT reverse-derived from swing.', ...
  'RUNTIME_EQUATION');

eq('SG-E-06','5.3','EMF6 network-current transformation', ...
  'PROJECT_DERIVED','RUNTIME_EQUATION', ...
  'Transform dq currents to network frame and inject into bus.', ...
  'Ig','none','Id, Iq, delta','none','pu','machine base', ...
  'machine into network','rotor dq frame','machine into network', ...
  'Park transformation; current positive into network', ...
  'Kundur','Power System Stability and Control','1st ed.','3-4','--','--','Eq 3.x','--', ...
  'Ig = kundur_book_network_current(Id, Iq, delta)', ...
  'identical (synchronous_emf6_ssa.m:181; g(2*b-1:2*b)+=[real(Ig);imag(Ig)])', ...
  'synchronous_emf6_ssa / network_residual','+stability/synchronous_emf6_ssa.m:179-183','test_emf6_model','VERIFIED', ...
  'KCL: g = Iinj - Y*V = 0 (same sign as Padiyar).', ...
  'RUNTIME_EQUATION');

eq('SG-E-07','5.3','EMF6 initial-condition construction', ...
  'PROJECT_DERIVED','RUNTIME_DERIVATION', ...
  'Initialize EMF6 states from PF solution so operating point is equilibrium.', ...
  'x0, y0','delta, omega, Eqp, Edp, Eqpp, Edpp','V, S','Ra, Xq, Xdp, Xdpp, Xqp, Xqpp, d_d','mixed','machine base', ...
  'machine into network','rotor dq frame','machine into network', ...
  'equilibrium from PF; angle from Newton on angle_residual', ...
  'Kundur','Power System Stability and Control','1st ed.','3-4','--','--','Eq 3.x','--', ...
  'delta from angle_residual Newton; Id,Iq from dq; Eqpp,Edpp,Eqp,Edp,Efd from stator eqs; Te from dq', ...
  'identical (synchronous_emf6_ssa.m:108-144)', ...
  'synchronous_emf6_ssa / initialize_equilibrium','+stability/synchronous_emf6_ssa.m:108-144','test_emf6_model','VERIFIED', ...
  'Efd = d_d*Eqp - c_d*Eqpp; Tm = Te at equilibrium.', ...
  'RUNTIME_DERIVATION');

% =========================================================================
% SSSA chain (SSSA-01 .. SSSA-12)
% =========================================================================
eq('SSSA-01','6','Nonlinear DAE', ...
  'SOURCE_VERBATIM','THEORY_FOUNDATION', ...
  'Semi-explicit DAE governing small-signal dynamics.', ...
  'x, y','x','y','u','mixed','system base', ...
  'machine into network','rotor dq frame','network into bus', ...
  'smooth between events; index-1 DAE', ...
  'Bergen & Vittal','Power Systems Analysis','2nd ed.','12.2','--','--','Eq 12.1','--', ...
  'dx/dt=f(x,y,u); 0=g(x,y,u)','identical (dae_f, dae_g closures)', ...
  'multimachine_ssa / model','+stability/multimachine_ssa.m','test_emf6_model','VERIFIED', ...
  'u fixed at equilibrium for SSSA.', ...
  'THEORY_FOUNDATION');

eq('SSSA-02','6','Equilibrium conditions', ...
  'SOURCE_VERBATIM','THEORY_FOUNDATION', ...
  'At equilibrium both f and g vanish.', ...
  'x0, y0','none','none','none','mixed','system base', ...
  'machine into network','rotor dq frame','network into bus', ...
  'equilibrium from PF + initialization', ...
  'Bergen & Vittal','Power Systems Analysis','2nd ed.','12.2','--','--','Eq 12.2','--', ...
  'f(x0,y0,u0)=0; g(x0,y0,u0)=0','identical (rf=f(x0,y0); rg=g(x0,y0); norm checked)', ...
  'synchronous_emf6_ssa / padiyar_model11_dae','+stability/synchronous_emf6_ssa.m:27-32','test_emf6_model','VERIFIED', ...
  'Residual must be below equilibrium_tolerance (1e-10).', ...
  'THEORY_FOUNDATION');

eq('SSSA-03','6','First-order Taylor expansion', ...
  'SOURCE_VERBATIM','RUNTIME_DERIVATION', ...
  'Linearize DAE around equilibrium.', ...
  'dx, dy','x, y','y','none','mixed','system base', ...
  'machine into network','rotor dq frame','network into bus', ...
  'small perturbations; first-order Taylor', ...
  'Bergen & Vittal','Power Systems Analysis','2nd ed.','12.3','--','--','Eq 12.3','--', ...
  '[dx_dot; 0] = [Jxx Jxy; Jyx Jyy]*[dx; dy]','identical (numerical_jacobian computes blocks)', ...
  'synchronous_emf6_ssa / numerical_jacobian','+stability/synchronous_emf6_ssa.m:216-227','test_emf6_model','VERIFIED', ...
  'Central FD with fd_eps=3e-6 (EMF6) or 1e-6 (Padiyar).', ...
  'RUNTIME_DERIVATION');

eq('SSSA-04','6','Four Jacobian blocks', ...
  'SOURCE_VERBATIM','RUNTIME_EQUATION', ...
  'Partial derivatives of f,g w.r.t. x,y.', ...
  'Jxx, Jxy, Jyx, Jyy','x','y','none','mixed','system base', ...
  'machine into network','rotor dq frame','network into bus', ...
  'smooth f,g', ...
  'Bergen & Vittal','Power Systems Analysis','2nd ed.','12.3','--','--','Eq 12.4','--', ...
  'Jxx=df/dx, Jxy=df/dy, Jyx=dg/dx, Jyy=dg/dy','identical (numerical_jacobian returns all four)', ...
  'numerical_jacobian','+stability/synchronous_emf6_ssa.m:216-227, +stability/multimachine_ssa.m:79-94','test_emf6_model','VERIFIED', ...
  'Central difference (f(x+h)-f(x-h))/(2h).', ...
  'RUNTIME_EQUATION');

eq('SSSA-05','6','Algebraic perturbation elimination', ...
  'SOURCE_TRANSFORMED','RUNTIME_DERIVATION', ...
  'Eliminate algebraic variables to get reduced state matrix.', ...
  'dy','none','none','Jyy, Jyx','mixed','system base', ...
  'machine into network','rotor dq frame','network into bus', ...
  'Jyy nonsingular (index-1)', ...
  'Bergen & Vittal','Power Systems Analysis','2nd ed.','12.3','--','--','Eq 12.5','--', ...
  'dy = -Jyy^{-1}*Jyx*dx (conceptual; production uses backslash)', ...
  'identical (multimachine_ssa.m:44 uses Jyy(free_y,free_y)\Jyx(free_y,:))', ...
  'multimachine_ssa','+stability/multimachine_ssa.m:44','test_emf6_model','VERIFIED', ...
  'Production NEVER forms inverse; uses backslash.', ...
  'RUNTIME_DERIVATION');

eq('SSSA-06','6','Reduced state matrix (Schur complement)', ...
  'PROJECT_DERIVED','RUNTIME_EQUATION', ...
  'Schur complement gives reduced state matrix for eigenvalue analysis.', ...
  'A','none','none','Jxx, Jxy, Jyy, Jyx','mixed','system base', ...
  'machine into network','rotor dq frame','network into bus', ...
  'Jyy nonsingular on free_y subspace', ...
  'Bergen & Vittal','Power Systems Analysis','2nd ed.','12.3','--','--','Eq 12.6','--', ...
  'A = Jxx - Jxy*(Jyy\Jyx)','identical (Afull=Jxx-Jxy(:,free_y)*(Jyy(free_y,free_y)\Jyx(free_y,:)))', ...
  'multimachine_ssa','+stability/multimachine_ssa.m:44','test_emf6_model','VERIFIED', ...
  'free_y retains algebraic variables; backslash, no inverse.', ...
  'RUNTIME_EQUATION');

eq('SSSA-07','6','Voltage/reference constraint ownership', ...
  'PROJECT_DERIVED','RUNTIME_EQUATION', ...
  'free_y selects algebraic variables retained in Schur complement.', ...
  'free_y','none','y','none','mixed','system base', ...
  'machine into network','rotor dq frame','network into bus', ...
  'reduced Jyy must remain square', ...
  'Bergen & Vittal','Power Systems Analysis','2nd ed.','12.3','--','--','Eq 12.7','--', ...
  'free_y = indices of algebraic variables to retain', ...
  'identical (multimachine_ssa.m:38-42; default 1:ny; EMF6 sets free_y=1:ny)', ...
  'multimachine_ssa','+stability/multimachine_ssa.m:38-42','test_emf6_model','VERIFIED', ...
  'Project uses free_y (generic), not vcon_vars/vcon_rows. COI reduction optional.', ...
  'RUNTIME_EQUATION');

eq('SSSA-08','6','Eigenvalue definition', ...
  'SOURCE_VERBATIM','RUNTIME_EQUATION', ...
  'Eigenvalues of reduced state matrix determine modes.', ...
  'lambda','none','none','A','1/s','system base', ...
  'machine into network','rotor dq frame','network into bus', ...
  'linear time-invariant system', ...
  'Bergen & Vittal','Power Systems Analysis','2nd ed.','12.4','--','--','Eq 12.8','--', ...
  'A*phi = lambda*phi','identical (lambda_full=eig(Afull))', ...
  'multimachine_ssa','+stability/multimachine_ssa.m:45','test_emf6_model','VERIFIED', ...
  'eig is base MATLAB primitive (audited linear-algebra).', ...
  'RUNTIME_EQUATION');

eq('SSSA-09','6','Frequency', ...
  'SOURCE_VERBATIM','RUNTIME_EQUATION', ...
  'Oscillation frequency from imaginary part of eigenvalue.', ...
  'f','none','none','lambda','Hz','system base', ...
  'machine into network','rotor dq frame','network into bus', ...
  'complex eigenvalue lambda=sigma+j*omega', ...
  'Bergen & Vittal','Power Systems Analysis','2nd ed.','12.4','--','--','Eq 12.9','--', ...
  'f = |Im(lambda)|/(2*pi)','identical (frequency_Hz=abs(imag(lambda_full))/(2*pi))', ...
  'multimachine_ssa','+stability/multimachine_ssa.m:67','test_emf6_model','VERIFIED', ...
  'Hz; omega in rad/s.', ...
  'RUNTIME_EQUATION');

eq('SSSA-10','6','Damping ratio', ...
  'SOURCE_VERBATIM','RUNTIME_EQUATION', ...
  'Damping ratio from real and imaginary parts.', ...
  'zeta','none','none','lambda','dimensionless','system base', ...
  'machine into network','rotor dq frame','network into bus', ...
  'complex eigenvalue', ...
  'Bergen & Vittal','Power Systems Analysis','2nd ed.','12.4','--','--','Eq 12.10','--', ...
  'zeta = -Re(lambda)/|lambda|','identical (damping_ratio=-real(lambda)./(abs(lambda)+eps))', ...
  'multimachine_ssa','+stability/multimachine_ssa.m:68','test_emf6_model','VERIFIED', ...
  '+eps guards zero eigenvalue (reference mode).', ...
  'RUNTIME_EQUATION');

eq('SSSA-11','6','Stability interpretation', ...
  'PROJECT_DERIVED','VALIDATION_ORACLE', ...
  'Classify modes: asymptotic stability, instability, reference, marginal.', ...
  'stable','none','none','lambda','dimensionless','system base', ...
  'machine into network','rotor dq frame','network into bus', ...
  'linear system', ...
  'Bergen & Vittal','Power Systems Analysis','2nd ed.','12.4','--','--','Eq 12.11','--', ...
  'stable iff all Re(lambda)<0; zero eigenvalue = reference mode', ...
  'identical (stable=all(real(lambda)<-1e-9))', ...
  'multimachine_ssa','+stability/multimachine_ssa.m:69','test_emf6_model','VERIFIED', ...
  'Reference mode (zero eigenvalue) excluded by COI reduction.', ...
  'VALIDATION_ORACLE');

eq('SSSA-12','6','Mode-shape / participation (if computed)', ...
  'PROJECT_DERIVED','DIAGNOSTIC_ONLY', ...
  'Right eigenvectors give mode shapes.', ...
  'V','none','none','A','dimensionless','system base', ...
  'machine into network','rotor dq frame','network into bus', ...
  'linear system', ...
  'Bergen & Vittal','Power Systems Analysis','2nd ed.','12.5','--','--','Eq 12.12','--', ...
  'V = eigenvectors of A','identical (mode_shapes=Vfull from eig)', ...
  'multimachine_ssa','+stability/multimachine_ssa.m:46','test_emf6_model','VERIFIED', ...
  'Participation factors not separately computed; mode shapes available.', ...
  'DIAGNOSTIC_ONLY');

% =========================================================================
% Fixed-step TS chain (TS-F-01 .. TS-F-12)
% =========================================================================
eq('TS-F-01','7','Integral form of the state equation', ...
  'SOURCE_VERBATIM','THEORY_FOUNDATION', ...
  'State evolution as integral of derivative.', ...
  'x','x','y','u, f','mixed','system base', ...
  'machine into network','rotor dq frame','network into bus', ...
  'smooth f between events', ...
  'Hairer, Nørsett & Wanner','Solving ODEs I','2nd ed.','II.1','--','--','Eq 1.1','--', ...
  'x(t+h)-x(t) = integral_t^{t+h} f(tau,x,y,u) dtau', ...
  'identical (basis of trapezoidal quadrature)', ...
  'ts_step_kernel','+stability/ts_step_kernel.m','test_ts_characterization_fixed','VERIFIED', ...
  'DAE: algebraic constraint g=0 alongside.', ...
  'THEORY_FOUNDATION');

eq('TS-F-02','7','Trapezoidal quadrature derivation', ...
  'SOURCE_VERBATIM','RUNTIME_DERIVATION', ...
  'Approximate integral by trapezoidal rule (order 2).', ...
  'x','none','f','none','mixed','system base', ...
  'machine into network','rotor dq frame','network into bus', ...
  'smooth f; O(h^3) local error', ...
  'Hairer, Nørsett & Wanner','Solving ODEs I','2nd ed.','II.1','--','--','Eq 1.2','--', ...
  'integral = (h/2)*(f(t)+f(t+h)) + O(h^3)', ...
  'identical (quadrature basis of trapezoidal update)', ...
  'ts_step_kernel','+stability/ts_step_kernel.m','test_ts_characterization_fixed','VERIFIED', ...
  'Local error O(h^3); global O(h^2).', ...
  'RUNTIME_DERIVATION');

eq('TS-F-03','7','Implicit trapezoidal update', ...
  'SOURCE_VERBATIM','RUNTIME_EQUATION', ...
  'Implicit trapezoidal step: x_{n+1} from x_n and f at both ends.', ...
  'x_{n+1}','x','y','f','mixed','system base', ...
  'machine into network','rotor dq frame','network into bus', ...
  'implicit; f_{n+1} depends on x_{n+1},y_{n+1}', ...
  'Hairer, Nørsett & Wanner','Solving ODEs I','2nd ed.','II.1','--','--','Eq 1.3','--', ...
  'x_{n+1} = x_n + (h/2)*(f_n + f_{n+1})', ...
  'identical (x_new = x + 0.5*h*(f0+f1) in ts_step_kernel.m:78,163)', ...
  'ts_step_kernel','+stability/ts_step_kernel.m:78,163','test_ts_characterization_fixed','VERIFIED', ...
  'Implicit: requires corrector iteration.', ...
  'RUNTIME_EQUATION');

eq('TS-F-04','7','Corrector residual', ...
  'PROJECT_DERIVED','RUNTIME_EQUATION', ...
  'Residual driving corrector iteration.', ...
  'R_x','x','y','f','mixed','system base', ...
  'machine into network','rotor dq frame','network into bus', ...
  'implicit trapezoidal', ...
  'Hairer, Nørsett & Wanner','Solving ODEs I','2nd ed.','II.1','--','--','Eq 1.4','--', ...
  'R_x = x_{n+1} - x_n - (h/2)*(f_n + f_{n+1})', ...
  'identical (R = x_new - x - 0.5*h*(f0+dae_f(x_new,y_new)) in ts_step_kernel.m:82,165)', ...
  'ts_step_kernel','+stability/ts_step_kernel.m:82,165','test_ts_characterization_fixed','VERIFIED', ...
  'Corrector drives R_x to zero.', ...
  'RUNTIME_EQUATION');

eq('TS-F-05','7','Algebraic residual', ...
  'PROJECT_DERIVED','RUNTIME_EQUATION', ...
  'Network algebraic constraint at new time.', ...
  'R_g','none','x, y','g','mixed','system base', ...
  'machine into network','rotor dq frame','network into bus', ...
  'DAE index-1', ...
  'Hairer, Nørsett & Wanner','Solving ODEs I','2nd ed.','II.1','--','--','Eq 1.5','--', ...
  'R_g = g(t_{n+1}, x_{n+1}, y_{n+1}, u_{n+1})', ...
  'identical (alg_res = norm(dae_g(x_pred,y_pred,Y),inf) in ts_step_kernel.m:114)', ...
  'ts_step_kernel','+stability/ts_step_kernel.m:114','test_ts_characterization_fixed','VERIFIED', ...
  'Classical: g=0 by construction (linear network).', ...
  'RUNTIME_EQUATION');

eq('TS-F-06','7','Coupled correction process', ...
  'PROJECT_DERIVED','RUNTIME_EQUATION', ...
  'Iterate corrector: solve algebraic, update state, check residual.', ...
  'x, y','x','y','f, g','mixed','system base', ...
  'machine into network','rotor dq frame','network into bus', ...
  'implicit coupling', ...
  'Hairer, Nørsett & Wanner','Solving ODEs I','2nd ed.','II.1','--','--','Eq 1.6','--', ...
  'iterate: solve g=0 for y; update x via trapezoidal; check R_x', ...
  'identical (ts_step_kernel.m:73-91 adaptive loop)', ...
  'ts_step_kernel','+stability/ts_step_kernel.m:73-91','test_ts_characterization_fixed','VERIFIED', ...
  'Adaptive corrector: iterate until update+residual converge.', ...
  'RUNTIME_EQUATION');

eq('TS-F-07','7','Update convergence criterion', ...
  'PROJECT_DERIVED','RUNTIME_EQUATION', ...
  'Stop corrector when state update below tolerance.', ...
  'upd','x','y','none','mixed','system base', ...
  'machine into network','rotor dq frame','network into bus', ...
  'corrector convergence', ...
  'Hairer, Nørsett & Wanner','Solving ODEs I','2nd ed.','II.1','--','--','Eq 1.7','--', ...
  'upd = norm(x_new - x_pred, inf); stop if upd <= tol', ...
  'identical (upd=norm(x_new-x_pred,inf); if upd<=tol_now && resn<=tol_now break)', ...
  'ts_step_kernel','+stability/ts_step_kernel.m:83,88','test_ts_characterization_fixed','VERIFIED', ...
  'tol_now = abs_tol + rel_tol*max(1,norm(x_pred,inf)).', ...
  'RUNTIME_EQUATION');

eq('TS-F-08','7','Trapezoidal-residual convergence criterion', ...
  'PROJECT_DERIVED','RUNTIME_EQUATION', ...
  'Stop corrector when trapezoidal residual below tolerance.', ...
  'resn','x','y','f','mixed','system base', ...
  'machine into network','rotor dq frame','network into bus', ...
  'corrector convergence', ...
  'Hairer, Nørsett & Wanner','Solving ODEs I','2nd ed.','II.1','--','--','Eq 1.8','--', ...
  'resn = norm(R_x, inf); stop if resn <= tol', ...
  'identical (resn=norm(R,inf); if upd<=tol_now && resn<=tol_now break)', ...
  'ts_step_kernel','+stability/ts_step_kernel.m:84,88','test_ts_characterization_fixed','VERIFIED', ...
  'Both upd and resn must converge.', ...
  'RUNTIME_EQUATION');

eq('TS-F-09','7','Event-grid insertion', ...
  'PROJECT_DERIVED','RUNTIME_EQUATION', ...
  'Snap fault/clear times to exact grid points to avoid one-step-late events.', ...
  't_event','none','t_fault, t_clear','none','s','system base', ...
  'machine into network','rotor dq frame','network into bus', ...
  'floating-point accumulation otherwise late', ...
  'Hairer, Nørsett & Wanner','Solving ODEs I','2nd ed.','II.1','--','--','Eq 1.9','--', ...
  'event_times = sort(unique([t_fault, t_clear]))', ...
  'identical (ts_adaptive_driver.m:92-100 event_times assembly)', ...
  'ts_adaptive_driver','+stability/ts_adaptive_driver.m:92-100','test_ts_characterization_fixed','VERIFIED', ...
  'Event grid snaps to exact times.', ...
  'RUNTIME_EQUATION');

eq('TS-F-10','7','Left/right topology event convention', ...
  'PROJECT_DERIVED','RUNTIME_EQUATION', ...
  'Arrival step uses LEFT topology; at event, switch to RIGHT and re-solve.', ...
  'Y_left, Y_right','none','Ypre, Yfault, Ypost','none','pu','system base', ...
  'machine into network','rotor dq frame','network into bus', ...
  'no step spans two topologies', ...
  'Hairer, Nørsett & Wanner','Solving ODEs I','2nd ed.','II.1','--','--','Eq 1.10','--', ...
  'arrival uses Y_left; at event switch to Y_right', ...
  'identical (ts_adaptive_driver.m:160-185; Y_now=ts_topology_at(t,...); Y_right=ts_topology_at(t+eps,...))', ...
  'ts_adaptive_driver / ts_topology_at','+stability/ts_adaptive_driver.m:160-185','test_ts_characterization_fixed','VERIFIED', ...
  'Public sample uses RIGHT-limit y (faulted voltage).', ...
  'RUNTIME_EQUATION');

eq('TS-F-11','7','Algebraic re-solve after topology switching', ...
  'PROJECT_DERIVED','RUNTIME_EQUATION', ...
  'After topology switch, re-solve algebraic variables under new topology.', ...
  'y_right','none','x, Y_right','g','mixed','system base', ...
  'machine into network','rotor dq frame','network into bus', ...
  'DAE index-1; y jumps at event', ...
  'Hairer, Nørsett & Wanner','Solving ODEs I','2nd ed.','II.1','--','--','Eq 1.11','--', ...
  'solve g(x, y_right, Y_right) = 0', ...
  'identical (ts_algebraic_solve(x,y,Y_right,...) in ts_adaptive_driver.m:167-168)', ...
  'ts_adaptive_driver / ts_algebraic_solve','+stability/ts_adaptive_driver.m:166-177','test_ts_characterization_fixed','VERIFIED', ...
  'Classical: re-solved inline in dae_f next step.', ...
  'RUNTIME_EQUATION');

eq('TS-F-12','7','Public output reconstruction', ...
  'PROJECT_DERIVED','RUNTIME_EQUATION', ...
  'Reconstruct delta, omega, Pe, Vbus for public output after event switch.', ...
  'delta, omega, Pe, Vbus','x','y','Y','mixed','system base', ...
  'machine into network','rotor dq frame','network into bus', ...
  'output sampling', ...
  'Hairer, Nørsett & Wanner','Solving ODEs I','2nd ed.','II.1','--','--','Eq 1.12','--', ...
  'rec = strat.reconstruct(x, y, Y_rec)', ...
  'identical (ts_adaptive_driver.m:190-195 reconstruct after event)', ...
  'ts_adaptive_driver','+stability/ts_adaptive_driver.m:190-195','test_ts_characterization_fixed','VERIFIED', ...
  'Vbus at t_event reflects right-limit (faulted) voltage.', ...
  'RUNTIME_EQUATION');

% =========================================================================
% Adaptive-step chain (TS-A-01 .. TS-A-15)
% =========================================================================
eq('TS-A-01','8.2','Order definition', ...
  'SOURCE_VERBATIM','THEORY_FOUNDATION', ...
  'Trapezoidal method global order p=2; local error O(h^{p+1})=O(h^3).', ...
  'p','none','none','none','dimensionless','system base', ...
  'machine into network','rotor dq frame','network into bus', ...
  'smooth f', ...
  'Hairer, Nørsett & Wanner','Solving ODEs I','2nd ed.','II.4','164-172','--','Eq 4.x','--', ...
  'p=2; local LTE O(h^3); global O(h^2)', ...
  'identical (p=2; q=p+1=3 in ts_adaptive_driver.m:42-43)', ...
  'ts_adaptive_driver','+stability/ts_adaptive_driver.m:42-43','test_ts_adaptive_lte','VERIFIED', ...
  'Hairer section/page NOT verified on host; estimator stays PROJECT_DERIVED.', ...
  'THEORY_FOUNDATION');

eq('TS-A-02','8.2','Full-step expansion', ...
  'SOURCE_VERBATIM','RUNTIME_DERIVATION', ...
  'Full-step solution error expansion.', ...
  'x_h','x','y','f','mixed','system base', ...
  'machine into network','rotor dq frame','network into bus', ...
  'single step from exact start', ...
  'Hairer, Nørsett & Wanner','Solving ODEs I','2nd ed.','II.4','164-172','--','Eq 4.x','--', ...
  'x_h = x* + C*h^{p+1} + O(h^{p+2})', ...
  'identical (basis of step-doubling estimator)', ...
  'ts_adaptive_driver','+stability/ts_adaptive_driver.m','test_ts_adaptive_lte','VERIFIED', ...
  'C is leading error constant.', ...
  'RUNTIME_DERIVATION');

eq('TS-A-03','8.2','Two-half-step expansion', ...
  'SOURCE_VERBATIM','RUNTIME_DERIVATION', ...
  'Two half-step solution error accumulates twice.', ...
  'x_h2h2','x','y','f','mixed','system base', ...
  'machine into network','rotor dq frame','network into bus', ...
  'two steps of h/2 from same start', ...
  'Hairer, Nørsett & Wanner','Solving ODEs I','2nd ed.','II.4','164-172','--','Eq 4.x','--', ...
  'x_h2h2 = x* + 2*C*(h/2)^{p+1} + O(h^{p+2})', ...
  'identical (basis of step_h1+step_h2 in ts_adaptive_driver.m:128-129)', ...
  'ts_adaptive_driver','+stability/ts_adaptive_driver.m:128-130','test_ts_adaptive_lte','VERIFIED', ...
  'Two half-step errors accumulate to leading order.', ...
  'RUNTIME_DERIVATION');

eq('TS-A-04','8.2','Simplification', ...
  'PROJECT_DERIVED','RUNTIME_DERIVATION', ...
  'Simplify 2*(h/2)^{p+1} = 2^{-p}*h^{p+1}.', ...
  'x_h2h2','none','none','none','mixed','system base', ...
  'machine into network','rotor dq frame','network into bus', ...
  'algebraic simplification', ...
  'Hairer, Nørsett & Wanner','Solving ODEs I','2nd ed.','II.4','164-172','--','Eq 4.x','--', ...
  '2*C*(h/2)^{p+1} = 2^{-p}*C*h^{p+1}', ...
  'identical (algebraic identity)', ...
  'ts_adaptive_driver','+stability/ts_adaptive_driver.m','test_ts_adaptive_lte','VERIFIED', ...
  'Factor 2^{-p} from two half steps.', ...
  'RUNTIME_DERIVATION');

eq('TS-A-05','8.2','Difference equation', ...
  'PROJECT_DERIVED','RUNTIME_DERIVATION', ...
  'Subtract full-step from two-half-step to isolate leading error.', ...
  'x_h2h2 - x_h','none','none','none','mixed','system base', ...
  'machine into network','rotor dq frame','network into bus', ...
  'leading error cancellation', ...
  'Hairer, Nørsett & Wanner','Solving ODEs I','2nd ed.','II.4','164-172','--','Eq 4.x','--', ...
  'x_h2h2 - x_h = (2^{-p}-1)*C*h^{p+1} + O(h^{p+2})', ...
  'identical (basis of e=(x_hh-x_f)/denom)', ...
  'ts_adaptive_driver','+stability/ts_adaptive_driver.m:134','test_ts_adaptive_lte','VERIFIED', ...
  'Sign: 2^{-p}-1 is negative for p>0.', ...
  'RUNTIME_DERIVATION');

eq('TS-A-06','8.2','Fine-solution error estimator', ...
  'PROJECT_DERIVED','RUNTIME_EQUATION', ...
  'Estimate fine-solution local error from difference.', ...
  'e_fine','none','x_h, x_h2h2','none','mixed','system base', ...
  'machine into network','rotor dq frame','network into bus', ...
  'project-derived; proven by analytic test', ...
  'Hairer, Nørsett & Wanner','Solving ODEs I','2nd ed.','II.4','164-172','--','Eq 4.x','--', ...
  'e_fine = (x_h2h2 - x_h)/(2^p - 1)', ...
  'identical (e=(x_halfhalf-x_full)/denom; denom=2^p-1 in ts_adaptive_driver.m:44,134)', ...
  'ts_adaptive_driver','+stability/ts_adaptive_driver.m:44,134','test_ts_adaptive_lte','VERIFIED', ...
  'PROJECT_DERIVED: Hairer does NOT print exact /3; project derivation in adaptive_ts_track_a.md.', ...
  'RUNTIME_EQUATION');

eq('TS-A-07','8.2','Trapezoidal specialization (p=2, /3)', ...
  'PROJECT_DERIVED','RUNTIME_EQUATION', ...
  'For trapezoidal p=2, denominator 2^p-1=3.', ...
  'e_x','none','x_h, x_h2h2','none','mixed','system base', ...
  'machine into network','rotor dq frame','network into bus', ...
  'p=2', ...
  'Hairer, Nørsett & Wanner','Solving ODEs I','2nd ed.','II.4','164-172','--','Eq 4.x','--', ...
  'e_x = (x_h2h2 - x_h)/3', ...
  'identical (denom=2^2-1=3 in ts_adaptive_driver.m:44)', ...
  'ts_adaptive_driver','+stability/ts_adaptive_driver.m:44','test_ts_adaptive_lte','VERIFIED', ...
  'PROJECT_DERIVED; proven by test_ts_adaptive_lte Test C.', ...
  'RUNTIME_EQUATION');

eq('TS-A-08','8.2','Component scaling', ...
  'SOURCE_TRANSFORMED','RUNTIME_EQUATION', ...
  'Per-component scale: absolute + relative tolerance.', ...
  'sc_i','none','x_n, x_cand','atol, rtol','mixed','system base', ...
  'machine into network','rotor dq frame','network into bus', ...
  'absolute near zero; relative for large states', ...
  'Hairer, Nørsett & Wanner','Solving ODEs I','2nd ed.','II.4','164-172','--','Eq 4.x','--', ...
  'sc_i = atol_i + rtol_i*max(|x_n_i|, |x_cand_i|)', ...
  'identical (sc_x=atol_x+rtol_x*max(abs(x),abs(x_halfhalf)) in ts_adaptive_driver.m:137)', ...
  'ts_adaptive_driver','+stability/ts_adaptive_driver.m:137','test_ts_adaptive_lte','VERIFIED', ...
  'No max(|x|,1) floor.', ...
  'RUNTIME_EQUATION');

eq('TS-A-09','8.2','Normalized error norm (weighted RMS)', ...
  'PROJECT_DERIVED','RUNTIME_EQUATION', ...
  'Weighted RMS normalized error (NOT max-norm).', ...
  'E_x','none','e, sc','none','dimensionless','system base', ...
  'machine into network','rotor dq frame','network into bus', ...
  'weighted RMS over states', ...
  'Hairer, Nørsett & Wanner','Solving ODEs I','2nd ed.','II.4','164-172','--','Eq 4.x','--', ...
  'E_x = sqrt(mean((e_i/sc_i)^2))', ...
  'identical (err_x=sqrt(mean((e./sc_x).^2)) in ts_adaptive_driver.m:138)', ...
  'ts_adaptive_driver','+stability/ts_adaptive_driver.m:138','test_ts_adaptive_lte','VERIFIED', ...
  'Code uses weighted RMS, NOT max-norm (differs from mission prose).', ...
  'RUNTIME_EQUATION');

eq('TS-A-10','8.2','Acceptance and rejection', ...
  'PROJECT_DERIVED','RUNTIME_EQUATION', ...
  'Accept iff E<=1 and algebraic residual <= g_tol; else reject.', ...
  'E','none','e, sc, g','none','dimensionless','system base', ...
  'machine into network','rotor dq frame','network into bus', ...
  'combined DAE error', ...
  'Hairer, Nørsett & Wanner','Solving ODEs I','2nd ed.','II.4','164-172','--','Eq 4.x','--', ...
  'E=max(E_x,E_y); accept iff E<=1 and alg_res<=g_tol', ...
  'identical (err=max(err_x,err_y); if err<=1 && alg_res<=g_tol accept in ts_adaptive_driver.m:144,151)', ...
  'ts_adaptive_driver','+stability/ts_adaptive_driver.m:144,151','test_ts_adaptive_lte','VERIFIED', ...
  'E_y uses e_y NOT divided by 3 (see TS-A-16).', ...
  'RUNTIME_EQUATION');

eq('TS-A-11','8.2','Step controller', ...
  'PROJECT_DERIVED','RUNTIME_EQUATION', ...
  'Step-size controller with safety factor and clamps.', ...
  'h_new','none','E, h','fac, fac_min, fac_max','s','system base', ...
  'machine into network','rotor dq frame','network into bus', ...
  'local error control; exponent 1/(p+1)=1/3', ...
  'Hairer, Nørsett & Wanner','Solving ODEs I','2nd ed.','II.4','164-172','--','Eq 4.x','--', ...
  'alpha=min(fac_max,max(fac_min,0.9*E^{-1/3})); h_new=min(h_max,max(h_min,h*alpha))', ...
  'identical (factor=min(fac_max,max(fac_min,fac*(1/err)^(1/3))); dt=min(dt_max,max(dt_min,dt*factor)) in ts_adaptive_driver.m:198-202)', ...
  'ts_adaptive_driver','+stability/ts_adaptive_driver.m','test_ts_adaptive_lte','VERIFIED', ...
  'fac=0.9, fac_min=0.2, fac_max=5.0, exp=1/3. E=0 -> alpha=fac_max.', ...
  'RUNTIME_EQUATION');

eq('TS-A-12','8.2','Rejection rollback', ...
  'PROJECT_DERIVED','RUNTIME_EQUATION', ...
  'On reject: halve dt, retry from same (x,y); committed state unchanged.', ...
  'h_retry','none','h','none','s','system base', ...
  'machine into network','rotor dq frame','network into bus', ...
  'no silent fixed-step fallback', ...
  'Hairer, Nørsett & Wanner','Solving ODEs I','2nd ed.','II.4','164-172','--','Eq 4.x','--', ...
  'h_retry = h/2; (t,x,y) committed unchanged', ...
  'identical (dt=h/2; x,y unchanged in ts_adaptive_driver.m:215; reject_limit=10)', ...
  'ts_adaptive_driver','+stability/ts_adaptive_driver.m:204-234','test_ts_adaptive_lte','VERIFIED', ...
  'Fail-closed if dt hits dt_min with err>1.', ...
  'RUNTIME_EQUATION');

eq('TS-A-13','8.2','Exact event landing', ...
  'PROJECT_DERIVED','RUNTIME_EQUATION', ...
  'Shrink dt to land exactly on event; no step spans two topologies.', ...
  'h','none','t, t_event','none','s','system base', ...
  'machine into network','rotor dq frame','network into bus', ...
  'event within dt', ...
  'Hairer, Nørsett & Wanner','Solving ODEs I','2nd ed.','II.4','164-172','--','Eq 4.x','--', ...
  'if event within dt: h = t_event - t', ...
  'identical (ts_adaptive_driver.m:108-119; next_event loop shrinks t_target)', ...
  'ts_adaptive_driver','+stability/ts_adaptive_driver.m:108-119','test_ts_adaptive_lte','VERIFIED', ...
  'No trapezoidal step crosses topology change.', ...
  'RUNTIME_EQUATION');

eq('TS-A-14','8.2','Endpoint input sampling', ...
  'PROJECT_DERIVED','RUNTIME_EQUATION', ...
  'Input sampled at step endpoints per implementation.', ...
  'u','none','t, t+h','none','mixed','system base', ...
  'machine into network','rotor dq frame','network into bus', ...
  'inputs held constant within step', ...
  'Hairer, Nørsett & Wanner','Solving ODEs I','2nd ed.','II.4','164-172','--','Eq 4.x','--', ...
  'u sampled at t and t+h (no midpoint provider in current runtime)', ...
  'identical (no midpoint sampling; Y_now at t, Y_right at event)', ...
  'ts_adaptive_driver','+stability/ts_adaptive_driver.m:121,164','test_ts_adaptive_lte','VERIFIED', ...
  'No t+h/2 input provider currently implemented.', ...
  'RUNTIME_EQUATION');

eq('TS-A-15','8.2','Accepted solution choice', ...
  'PROJECT_DERIVED','RUNTIME_EQUATION', ...
  'Accepted solution is the fine two-half-step solution x_halfhalf.', ...
  'x_accepted','none','x_h2h2','none','mixed','system base', ...
  'machine into network','rotor dq frame','network into bus', ...
  'fine solution higher accuracy', ...
  'Hairer, Nørsett & Wanner','Solving ODEs I','2nd ed.','II.4','164-172','--','Eq 4.x','--', ...
  'x_accepted = x_halfhalf (NOT x_full, NOT Richardson-extrapolated)', ...
  'identical (x=x_halfhalf in ts_adaptive_driver.m:153)', ...
  'ts_adaptive_driver','+stability/ts_adaptive_driver.m:153','test_ts_adaptive_lte','VERIFIED', ...
  'x_full used only to form estimate; not the public solution.', ...
  'RUNTIME_EQUATION');

eq('TS-A-16','8.2','Algebraic discrepancy (e_y not /3)', ...
  'PROJECT_DERIVED','RUNTIME_EQUATION', ...
  'Algebraic error e_y = y_h2h2 - y_h (NOT divided by 3).', ...
  'e_y','none','y_h, y_h2h2','none','mixed','system base', ...
  'machine into network','rotor dq frame','network into bus', ...
  'project-derived; not a sourced Richardson LTE', ...
  'Hairer, Nørsett & Wanner','Solving ODEs I','2nd ed.','II.4','164-172','--','Eq 4.x','--', ...
  'e_y = y_h2h2 - y_h (no /3 division)', ...
  'identical (e_y=(y_halfhalf-step_full.y_full) in ts_adaptive_driver.m:141; no /3)', ...
  'ts_adaptive_driver','+stability/ts_adaptive_driver.m:141','test_ts_adaptive_lte','VERIFIED', ...
  'PROJECT_DERIVED algebraic discrepancy; not sourced Richardson LTE. Mission Layer 4 requires this label.', ...
  'RUNTIME_EQUATION');

% =========================================================================
% Load/fault/network equations (LFN-01 .. LFN-08)
% =========================================================================
eq('LFN-01','9-11','Constant-impedance load conversion', ...
  'SOURCE_TRANSFORMED','RUNTIME_EQUATION', ...
  'Convert load S0 to shunt admittance for constant-impedance load model.', ...
  'Y_load','none','S0, V0','none','pu','system base', ...
  'load consumes; injection negative','phase reference','network into bus', ...
  'constant-impedance load; sinusoidal steady state', ...
  'Bergen & Vittal','Power Systems Analysis','2nd ed.','2.6','--','--','Eq 2.34','--', ...
  'Y_load = conj(S0)/|V0|^2', ...
  'identical (Yload=conj(Sload)./(abs(V0).^2+eps) in classical_dae.m:51; (P-jQ)/V0^2 in padiyar_model11_dae.m:203)', ...
  'classical_dae / padiyar_model11_dae / network_model','+stability/classical_dae.m, +stability/padiyar_model11_dae.m','test_matpower6_case14','VERIFIED', ...
  'conj(P+jQ)=P-jQ; +eps guards zero voltage. RTS-24 uses this for PSAT comparison.', ...
  'RUNTIME_EQUATION');

eq('LFN-02','9-11','Fault shunt/admittance construction', ...
  'PROJECT_DERIVED','RUNTIME_EQUATION', ...
  'Three-phase fault modeled as shunt admittance at fault bus.', ...
  'Y_fault','none','Zf','none','pu','system base', ...
  'fault to ground','phase reference','network into bus', ...
  'solid or impedance fault; shunt at fault bus', ...
  'Bergen & Vittal','Power Systems Analysis','2nd ed.','9.3','--','--','Eq 9.x','--', ...
  'Y_fault = 1/Zf added to fault bus diagonal', ...
  'identical (ts_topology_at adds fault admittance to Yfault)', ...
  'ts_topology_at','+stability/ts_topology_at.m','test_ts_characterization_fixed','VERIFIED', ...
  'Zf=j0.1 typical; solid fault Zf=0 -> Y_fault=inf (handled).', ...
  'RUNTIME_EQUATION');

eq('LFN-03','9-11','Prefault/fault/postfault Ybus', ...
  'PROJECT_DERIVED','RUNTIME_EQUATION', ...
  'Three topology Ybus matrices: Ypre, Yfault, Ypost.', ...
  'Ypre, Yfault, Ypost','none','Ynet, Y_fault, fault_bus','none','pu','system base', ...
  'network into bus','phase reference','network into bus', ...
  'fault applied then cleared', ...
  'Bergen & Vittal','Power Systems Analysis','2nd ed.','9.3','--','--','Eq 9.x','--', ...
  'Ypre=Ynet; Yfault=Ypre+Y_fault at fault bus; Ypost=Ypre (fault cleared)', ...
  'identical (events struct: Ypre, Yfault, Ypost in ts_adaptive_driver.m:34-35)', ...
  'ts_topology_at','+stability/ts_topology_at.m','test_ts_characterization_fixed','VERIFIED', ...
  'Ypost may differ from Ypre if line tripped (case-dependent).', ...
  'RUNTIME_EQUATION');

eq('LFN-04','9-11','Fault impedance', ...
  'CASE_DEFINED','CASE_INPUT', ...
  'Fault impedance Zf specified by case.', ...
  'Zf','none','none','none','pu','system base', ...
  'fault to ground','phase reference','network into bus', ...
  'three-phase to ground fault', ...
  'Bergen & Vittal','Power Systems Analysis','2nd ed.','9.3','--','--','Eq 9.x','--', ...
  'Zf = Rf + jXf (pu)','identical (ts_options.Zf in run_ts.m; case-specific)', ...
  'run_ts / case_data','run_ts.m:14','test_ts_characterization_fixed','VERIFIED', ...
  'Case-specific; never tuned after seeing results.', ...
  'CASE_INPUT');

eq('LFN-05','9-11','Fault clearing operation', ...
  'PROJECT_DERIVED','RUNTIME_EQUATION', ...
  'At t_clear, remove fault admittance; switch to Ypost.', ...
  'Y','none','t, t_clear','none','pu','system base', ...
  'network into bus','phase reference','network into bus', ...
  'discrete event', ...
  'Bergen & Vittal','Power Systems Analysis','2nd ed.','9.3','--','--','Eq 9.x','--', ...
  'at t_clear: Y switches from Yfault to Ypost', ...
  'identical (ts_topology_at returns Ypost for t>t_clear)', ...
  'ts_topology_at','+stability/ts_topology_at.m','test_ts_characterization_fixed','VERIFIED', ...
  'Algebraic re-solve after switch (TS-F-11).', ...
  'RUNTIME_EQUATION');

eq('LFN-06','9-11','Generator current accumulation', ...
  'PROJECT_DERIVED','RUNTIME_EQUATION', ...
  'Sum generator currents into bus injection vector.', ...
  'Iinj','none','Ig','none','pu','system base', ...
  'machine into network','rotor dq frame','machine into network', ...
  'superposition', ...
  'Bergen & Vittal','Power Systems Analysis','2nd ed.','7.3','--','--','Eq 7.16','--', ...
  'Iinj(b) += Ig(k) for generator k at bus b', ...
  'identical (g(2*b-1:2*b)+=[real(Ig);imag(Ig)] in synchronous_emf6_ssa.m:182; gc(b)+=Ig in padiyar_model11_dae.m:144)', ...
  'synchronous_emf6_ssa / padiyar_model11_dae','+stability/synchronous_emf6_ssa.m:179-183, +stability/padiyar_model11_dae.m:141-145','test_emf6_model','VERIFIED', ...
  'Same convention across all models.', ...
  'RUNTIME_EQUATION');

eq('LFN-07','9-11','Bus-voltage reconstruction', ...
  'PROJECT_DERIVED','RUNTIME_EQUATION', ...
  'Reconstruct complex bus voltages from algebraic state y.', ...
  'V','none','y','none','pu','system base', ...
  'network into bus','phase reference','network into bus', ...
  'y interleaved [Re(V1),Im(V1),...]', ...
  'Bergen & Vittal','Power Systems Analysis','2nd ed.','2.4','--','--','Eq 2.18','--', ...
  'V = complex(y(1:2:end), y(2:2:end))', ...
  'identical (V=complex(y(1:2:end),y(2:2:end)) in synchronous_emf6_ssa.m:168, padiyar_model11_dae.m:139)', ...
  'synchronous_emf6_ssa / padiyar_model11_dae','+stability/synchronous_emf6_ssa.m, +stability/padiyar_model11_dae.m','test_emf6_model','VERIFIED', ...
  'Interleaved real/imag storage convention.', ...
  'RUNTIME_EQUATION');

eq('LFN-08','9-11','Constant-power load (if used)', ...
  'SOURCE_TRANSFORMED','RUNTIME_EQUATION', ...
  'Constant-power load: current from S0 and V.', ...
  'I_load','none','S0, V','none','pu','system base', ...
  'load consumes','phase reference','network into bus', ...
  'constant-power load model', ...
  'Bergen & Vittal','Power Systems Analysis','2nd ed.','2.6','--','--','Eq 2.35','--', ...
  'I_load = conj(S0/V)', ...
  'identical (Iload=conj((load.P+1i*load.Q)/V) in synchronous_emf6_ssa.m:175 otherwise branch)', ...
  'synchronous_emf6_ssa / network_residual','+stability/synchronous_emf6_ssa.m:175','test_emf6_model','VERIFIED', ...
  'Used only when load_model not cz; cc_p_cz_q is mixed.', ...
  'RUNTIME_EQUATION');

% =========================================================================
% Comparison equations (CMP-01 .. CMP-09)
% =========================================================================
eq('CMP-01','9-11','Generator-ID mapping', ...
  'PROJECT_DERIVED','VALIDATION_ORACLE', ...
  'Map generator IDs between Ours and reference tools.', ...
  'gen_map','none','gen_buses','none','dimensionless','system base', ...
  'machine into network','rotor dq frame','machine into network', ...
  'bus-based mapping', ...
  'Bergen & Vittal','Power Systems Analysis','2nd ed.','7.3','--','--','Eq 7.x','--', ...
  'map by generator bus [1,2,3,6,8] for case14', ...
  'identical (run_three_way_validation maps generators by bus)', ...
  'run_three_way_validation','scripts/validation/run_three_way_validation.m','test_run_three_way_validation_structured','VERIFIED', ...
  'Mapping verified before comparison; fail-closed on mismatch.', ...
  'VALIDATION_ORACLE');

eq('CMP-02','9-11','Bus-ID mapping', ...
  'PROJECT_DERIVED','VALIDATION_ORACLE', ...
  'Map bus IDs between Ours and reference tools.', ...
  'bus_map','none','bus_ids','none','dimensionless','system base', ...
  'network into bus','phase reference','network into bus', ...
  'bus number mapping', ...
  'Bergen & Vittal','Power Systems Analysis','2nd ed.','2.4','--','--','Eq 2.x','--', ...
  'map by external bus IDs', ...
  'identical (run_three_way_validation maps buses)', ...
  'run_three_way_validation','scripts/validation/run_three_way_validation.m','test_run_three_way_validation_structured','VERIFIED', ...
  'Required for PF bus-by-bus comparison.', ...
  'VALIDATION_ORACLE');

eq('CMP-03','9-11','Reference-angle alignment', ...
  'PROJECT_DERIVED','VALIDATION_ORACLE', ...
  'Align angle reference between Ours and reference (slack bus).', ...
  'theta_aligned','none','theta, theta_ref','none','rad','system base', ...
  'network into bus','phase reference','network into bus', ...
  'common slack bus', ...
  'Bergen & Vittal','Power Systems Analysis','2nd ed.','2.4','--','--','Eq 2.x','--', ...
  'theta_aligned = theta - theta_ref(slack)', ...
  'identical (run_three_way_validation aligns to common slack)', ...
  'run_three_way_validation','scripts/validation/run_three_way_validation.m','test_run_three_way_validation_structured','VERIFIED', ...
  'Required before angle comparison.', ...
  'VALIDATION_ORACLE');

eq('CMP-04','9-11','COI transformation', ...
  'PROJECT_DERIVED','VALIDATION_ORACLE', ...
  'Inertia-weighted COI angle for common-mode removal.', ...
  'delta_COI','delta','none','H','rad','machine base', ...
  'machine into network','rotor dq frame','machine into network', ...
  'inertia-weighted average', ...
  'Bergen & Vittal','Power Systems Analysis','2nd ed.','7.4','--','--','Eq 7.20','--', ...
  'delta_COI = sum(H_i*delta_i)/sum(H_i)', ...
  'identical (coi_relative.m implements inertia-weighted COI)', ...
  'coi_relative','scripts/validation/coi_relative.m','test_coi_weighting','VERIFIED', ...
  'Removes common-mode motion.', ...
  'VALIDATION_ORACLE');

eq('CMP-05','9-11','Incremental trajectory', ...
  'PROJECT_DERIVED','VALIDATION_ORACLE', ...
  'Incremental angle from t=0 removes initial offset.', ...
  'tilde_delta','delta','none','none','rad','machine base', ...
  'machine into network','rotor dq frame','machine into network', ...
  'COI frame; incremental', ...
  'Bergen & Vittal','Power Systems Analysis','2nd ed.','7.4','--','--','Eq 7.21','--', ...
  'tilde_delta_i(t) = [delta_i(t)-delta_COI(t)] - [delta_i(0)-delta_COI(0)]', ...
  'identical (coi_relative.m computes incremental COI-relative)', ...
  'coi_relative','scripts/validation/coi_relative.m','test_coi_weighting','VERIFIED', ...
  'Plotted angle is delta_i(t)-delta_i(0) (PSAT delta_Syn style).', ...
  'VALIDATION_ORACLE');

eq('CMP-06','9-11','Pairwise rotor-angle separation', ...
  'PROJECT_DERIVED','VALIDATION_ORACLE', ...
  'Maximum angle difference between any two machines.', ...
  'delta_pairwise','delta','none','none','rad','machine base', ...
  'machine into network','rotor dq frame','machine into network', ...
  'COI frame', ...
  'Bergen & Vittal','Power Systems Analysis','2nd ed.','7.4','--','--','Eq 7.22','--', ...
  'delta_pairwise = max_{i,j} |tilde_delta_i - tilde_delta_j|', ...
  'identical (coi_relative.m / compare helpers compute pairwise)', ...
  'coi_relative','scripts/validation/coi_relative.m','test_coi_weighting','VERIFIED', ...
  'Stability indicator: large pairwise separation = instability risk.', ...
  'VALIDATION_ORACLE');

eq('CMP-07','9-11','No-extrapolation interpolation', ...
  'PROJECT_DERIVED','VALIDATION_ORACLE', ...
  'Interpolate onto common grid without extrapolating outside interval.', ...
  'y_common','none','t_ours, t_ref, y_ref','none','mixed','system base', ...
  'network into bus','phase reference','network into bus', ...
  'common time interval only', ...
  'Hairer, Nørsett & Wanner','Solving ODEs I','2nd ed.','II.1','--','--','Eq 1.x','--', ...
  'y_common = interp1(t_ref, y_ref, t_ours, ''linear'') within [min,max]', ...
  'identical (interp_no_extrapolate.m enforces no extrapolation)', ...
  'interp_no_extrapolate','scripts/validation/interp_no_extrapolate.m','test_interpolation_no_extrapolation','VERIFIED', ...
  'Never extrapolate outside common interval.', ...
  'VALIDATION_ORACLE');

eq('CMP-08','9-11','Maximum absolute error and RMSE', ...
  'PROJECT_DERIVED','VALIDATION_ORACLE', ...
  'Error metrics: max abs and RMS.', ...
  'max_err, rmse','none','y_ours, y_ref','none','mixed','system base', ...
  'network into bus','phase reference','network into bus', ...
  'common grid', ...
  'Bergen & Vittal','Power Systems Analysis','2nd ed.','12.6','--','--','Eq 12.x','--', ...
  'max_err=max(|y_ours-y_ref|); rmse=sqrt(mean((y_ours-y_ref).^2))', ...
  'identical (run_three_way_validation computes max and RMS)', ...
  'run_three_way_validation','scripts/validation/run_three_way_validation.m','test_run_three_way_validation_structured','VERIFIED', ...
  'NRMSE only where denominator physically meaningful.', ...
  'VALIDATION_ORACLE');

eq('CMP-09','9-11','Eigenvalue pairing metric', ...
  'PROJECT_DERIVED','VALIDATION_ORACLE', ...
  'Deterministic greedy eigenvalue pairing (no manual pairing).', ...
  'match, err','none','lambda_ours, lambda_ref','none','1/s','system base', ...
  'machine into network','rotor dq frame','machine into network', ...
  'greedy nearest assignment', ...
  'Bergen & Vittal','Power Systems Analysis','2nd ed.','12.6','--','--','Eq 12.x','--', ...
  'greedy: for each ref eigenvalue, nearest unused ours', ...
  'identical (greedy() in generate_padiyar_two_area_report.m:274-277)', ...
  'generate_padiyar_two_area_report / greedy','scripts/reporting/generate_padiyar_two_area_report.m:274','test_padiyar_two_area_reference','VERIFIED', ...
  'Deterministic; no manual pairing after viewing plot.', ...
  'VALIDATION_ORACLE');
];
end

% =========================================================================
function row = eq(id, sec, name, class, purpose_label, purpose, dep, ...
  dstates, dalg, dinputs, units, pubase, sign, frame, curdir, ...
  assum, sauthor, stitle, ed, chap, ppage, pdfpage, seqnum, doi, ...
  snot, pnot, pfn, pfile, test, ready, limit, trlabel)
% Helper to build one register row as a struct.
% Call signature (32 positional args, matching every eq(...) call site):
%   id, sec, name, class, purpose_label, purpose, dep, dstates, dalg,
%   dinputs, units, pubase, sign, frame, curdir, assum, sauthor, stitle,
%   ed, chap, ppage, pdfpage, seqnum, doi, snot, pnot, pfn, pfile, test,
%   ready, limit, trlabel.
% `parameters` (dparams) and `transformation_derivation` (trans) are not
% passed separately at the call sites; they are derived here from snot/pnot
% so the register still carries the full field set required by the audit.
row = struct( ...
  'equation_id', id, ...
  'report_section', sec, ...
  'equation_name', name, ...
  'classification', class, ...
  'physical_or_numerical_purpose', purpose, ...
  'theory_runtime_label', trlabel, ...
  'dependent_variable', dep, ...
  'differential_states', dstates, ...
  'algebraic_variables', dalg, ...
  'inputs', dinputs, ...
  'parameters', 'see source_notation/project_notation', ...
  'units', units, ...
  'per_unit_base', pubase, ...
  'sign_convention', sign, ...
  'reference_frame', frame, ...
  'current_direction', curdir, ...
  'assumptions', assum, ...
  'source_author', sauthor, ...
  'source_title', stitle, ...
  'edition_year', ed, ...
  'chapter_section', chap, ...
  'printed_page', ppage, ...
  'PDF_page_index', pdfpage, ...
  'source_equation_number', seqnum, ...
  'DOI_ISBN_URL', doi, ...
  'source_notation', snot, ...
  'project_notation', pnot, ...
  'transformation_derivation', ['source: ' snot ' -> project: ' pnot], ...
  'production_function', pfn, ...
  'production_file', pfile, ...
  'test_or_oracle', test, ...
  'readiness_status', ready, ...
  'limitation', limit);
end
