function equation_register_export(outdir)
%EQUATION_REGISTER_EXPORT  Generate provenance artifacts from the single register.
%   equation_register_export(OUTDIR) reads equation_register() and writes the
%   six generated artifacts into OUTDIR:
%     equation_provenance.csv
%     table_equation_provenance.tex
%     table_symbol_dictionary.tex
%     table_source_input_provenance.tex
%     table_equation_code_mapping.tex
%     equation_source_gaps.tex
%   The register is the ONE tracked structured source; these artifacts are
%   generated, never hand-maintained.

if nargin < 1 || isempty(outdir)
    outdir = fullfile(fileparts(fileparts(fileparts(mfilename('fullpath')))), ...
        'docs','source','figures','system_methods');
end
if ~exist(outdir,'dir'), mkdir(outdir); end

reg = equation_register();
n = numel(reg);

% --- equation_provenance.csv ---
fields = fieldnames(reg);
fid = fopen(fullfile(outdir,'equation_provenance.csv'),'w');
z = onCleanup(@()fclose(fid)); %#ok<NASGU>
fprintf(fid, '%s\n', strjoin(fields, ','));
for i = 1:n
    vals = cell(1,numel(fields));
    for f = 1:numel(fields)
        v = reg(i).(fields{f});
        if isnumeric(v), v = num2str(v); end
        v = strrep(v, '"', '""');
        vals{f} = ['"' v '"'];
    end
    fprintf(fid, '%s\n', strjoin(vals, ','));
end

% --- table_equation_provenance.tex ---
fid = fopen(fullfile(outdir,'table_equation_provenance.tex'),'w');
z = onCleanup(@()fclose(fid)); %#ok<NASGU>
fprintf(fid, '%% Generated by equation_register_export. Do not edit by hand.\n');
fprintf(fid, '\\begin{longtable}{rllp{3.2cm}llp{2.8cm}l}\\toprule\n');
fprintf(fid, 'ID & Sec & Name & Classification & Source & Location & Code \\\\\n');
fprintf(fid, '\\midrule\n');
for i = 1:n
    loc = reg(i).chapter_section;
    if ~strcmp(reg(i).printed_page,'--'), loc = [loc ' p.' reg(i).printed_page]; end
    fprintf(fid, '%s & %s & %s & %s & %s & %s & %s \\\\\n', ...
        reg(i).equation_id, reg(i).report_section, ...
        escape_tex(reg(i).equation_name), reg(i).classification, ...
        escape_tex(reg(i).source_author), escape_tex(loc), ...
        escape_tex(reg(i).production_function));
end
fprintf(fid, '\\bottomrule\n\\end{longtable}\n');

% --- table_symbol_dictionary.tex (unique symbols from dependent_variable + states) ---
fid = fopen(fullfile(outdir,'table_symbol_dictionary.tex'),'w');
z = onCleanup(@()fclose(fid)); %#ok<NASGU>
fprintf(fid, '%% Generated by equation_register_export. Do not edit by hand.\n');
fprintf(fid, '\\begin{longtable}{llp{4cm}ll}\\toprule\n');
fprintf(fid, 'Symbol & Equation & Meaning & Unit & PU base \\\\\n\\midrule\n');
for i = 1:n
    dv = reg(i).dependent_variable;
    if strcmp(dv,'none'), continue; end
    syms = strsplit(dv, ', ');
    for s = 1:numel(syms)
        sym = strtrim(syms{s});
        if isempty(sym), continue; end
        fprintf(fid, '$%s$ & %s & %s & %s & %s \\\\\n', ...
            escape_tex(sym), reg(i).equation_id, ...
            escape_tex(reg(i).equation_name), ...
            escape_tex(reg(i).units), escape_tex(reg(i).per_unit_base));
    end
end
fprintf(fid, '\\bottomrule\n\\end{longtable}\n');

% --- table_source_input_provenance.tex ---
fid = fopen(fullfile(outdir,'table_source_input_provenance.tex'),'w');
z = onCleanup(@()fclose(fid)); %#ok<NASGU>
fprintf(fid, '%% Generated by equation_register_export. Do not edit by hand.\n');
fprintf(fid, '\\begin{longtable}{llp{3cm}p{2.5cm}p{2.5cm}l}\\toprule\n');
fprintf(fid, 'ID & Author & Title & Edition & Chapter & Page \\\\\n\\midrule\n');
for i = 1:n
    if strcmp(reg(i).source_author,'--'), continue; end
    fprintf(fid, '%s & %s & %s & %s & %s & %s \\\\\n', ...
        reg(i).equation_id, escape_tex(reg(i).source_author), ...
        escape_tex(reg(i).source_title), escape_tex(reg(i).edition_year), ...
        escape_tex(reg(i).chapter_section), reg(i).printed_page);
end
fprintf(fid, '\\bottomrule\n\\end{longtable}\n');

% --- table_equation_code_mapping.tex ---
fid = fopen(fullfile(outdir,'table_equation_code_mapping.tex'),'w');
z = onCleanup(@()fclose(fid)); %#ok<NASGU>
fprintf(fid, '%% Generated by equation_register_export. Do not edit by hand.\n');
fprintf(fid, '\\begin{longtable}{rllp{4cm}p{3.5cm}l}\\toprule\n');
fprintf(fid, 'ID & Label & Production function & File & Test/oracle \\\\\n\\midrule\n');
for i = 1:n
    fprintf(fid, '%s & %s & %s & %s & %s \\\\\n', ...
        reg(i).equation_id, reg(i).theory_runtime_label, ...
        escape_tex(reg(i).production_function), ...
        escape_tex(reg(i).production_file), escape_tex(reg(i).test_or_oracle));
end
fprintf(fid, '\\bottomrule\n\\end{longtable}\n');

% --- equation_source_gaps.tex (NOT_READY rows + audit gaps) ---
status = equation_audit(reg);
fid = fopen(fullfile(outdir,'equation_source_gaps.tex'),'w');
z = onCleanup(@()fclose(fid)); %#ok<NASGU>
fprintf(fid, '%% Generated by equation_register_export. Do not edit by hand.\n');
fprintf(fid, '\\section*{Equation source gaps}\n\n');
fprintf(fid, '\\begin{tabular}{lll}\\toprule Equation ID & Rule & Detail \\\\\\midrule\n');
g = status.gaps;
for i = 1:numel(g)
    fprintf(fid, '%s & %s & %s \\\\\n', g(i).equation_id, g(i).rule, escape_tex(g(i).detail));
end
notready = strcmp({reg.readiness_status}, 'NOT_READY');
nr_ids = {reg(notready).equation_id};
for i = 1:numel(nr_ids)
    fprintf(fid, '%s & READINESS & equation marked NOT_READY \\\\\n', nr_ids{i});
end
fprintf(fid, '\\bottomrule\n\\end{tabular}\n\n');
fprintf(fid, '\\paragraph{Audit status.}\n');
fprintf(fid, '\\begin{tabular}{ll}\\toprule Gate & Status \\\\\\midrule\n');
fprintf(fid, 'EQUATION\\_REGISTER\\_COMPLETE & %s \\\\\n', status.EQUATION_REGISTER_COMPLETE);
fprintf(fid, 'EQUATION\\_SOURCE\\_COVERAGE & %s \\\\\n', status.EQUATION_SOURCE_COVERAGE);
fprintf(fid, 'DIMENSIONAL\\_AUDIT & %s \\\\\n', status.DIMENSIONAL_AUDIT);
fprintf(fid, 'CONVENTION\\_AUDIT & %s \\\\\n', status.CONVENTION_AUDIT);
fprintf(fid, 'CODE\\_EQUATION\\_MATCH & %s \\\\\n', status.CODE_EQUATION_MATCH);
fprintf(fid, 'PROJECT\\_DERIVED\\_PREMISES & %s \\\\\n', status.PROJECT_DERIVED_PREMISES);
fprintf(fid, 'RESULT\\_PROVENANCE\\_COMPLETE & %s \\\\\n', status.RESULT_PROVENANCE_COMPLETE);
fprintf(fid, 'DOCUMENTATION\\_EQUATION\\_PROVENANCE\\_READY & %s \\\\\n', status.DOCUMENTATION_EQUATION_PROVENANCE_READY);
fprintf(fid, '\\bottomrule\n\\end{tabular}\n');

fprintf('equation_register_export: wrote 6 artifacts to %s (%d equations, %d gaps)\n', ...
    outdir, n, numel(g));
end

function s = escape_tex(s)
s = strrep(s, '_', '\_');
s = strrep(s, '%', '\%');
s = strrep(s, '&', '\&');
s = strrep(s, '#', '\#');
end
