function out = generate_ieee14_report_scalars(opts)
%GENERATE_IEEE14_REPORT_SCALARS  Frozen run scalars as LaTeX macros.
%
%   generate_ieee14_report_scalars()
%
% Writes the \New*-prefixed macro set the switching report consumes, read from a
% stored accepted trajectory. The macro NAMES match the earlier 200-s macro file
% exactly, so the report body needs no edit to move onto a new run; only the
% \input target changes. That is the point of the indirection: prose and tables
% cannot drift from the numbers, because there is only one place the numbers live.
%
% Every value is a raw accepted quantity. Nothing is rounded to make a claim, and
% no extremum is presented as a rating: the voltage and frequency extremes are
% REPORTED results of a deliberately severe event sequence, not acceptance
% criteria, and no model was adjusted after seeing them.
%
% Powers of ten are written $a\times10^{n}$ per AGENTS.md; a programming-language
% exponent form never reaches the document.
%
% Classification: reporting only.

arguments
    opts.result_file (1,1) string = fullfile('output','diagnostics', ...
        'ieee14_gfm_lock_compare','adaptive_250s.mat')
    opts.output (1,1) string = fullfile('docs','source','figures', ...
        'switch_ieee14_decision','run_summary_v2.tex')
    opts.prefix (1,1) string = "NewRun"
end

pf_init_paths();
r = load_result(opts.result_file);
P = char(opts.prefix);

V = r.bus_voltage_magnitude;
f = r.coi_frequency_Hz(:); f = f(isfinite(f));
acc = r.accepted_residual_per_step; acc = acc(isfinite(acc));
g = struct('dV',NaN,'df',NaN,'dtheta',NaN);
if isfield(r,'last_synchronism_guard') && isstruct(r.last_synchronism_guard)
    L = r.last_synchronism_guard;
    g.dV = pick(L,'dV'); g.df = pick(L,'df'); g.dtheta = pick(L,'dtheta');
end
rel = applied_times(r,'gfm_support_release');
aug = applied_times(r,'gfm_support_augment');

d = fileparts(char(opts.output));
if ~isempty(d) && ~isfolder(d), mkdir(d); end
fid = fopen(char(opts.output),'w');
assert(fid > 0,'cannot open %s',opts.output);

src = strrep(char(opts.result_file),'\','/');
% The bit-identity claim belongs to ONE cache only -- the ideal-DC chronology
% whose re-run was gated against the delivered artifact. Emitting it for any
% other cache would be a false provenance statement, so the sentence is selected
% from the cache the values were actually read from instead of being hardcoded.
[srcdir,~,~] = fileparts(src);
[~,cachename] = fileparts(srcdir);
bitidentity_gated = strcmp(cachename,'ieee14_gfm_lock_compare');

fprintf(fid,'%% Generated by generate_ieee14_report_scalars. Do not edit.\n%%\n');
fprintf(fid,'%% PROVENANCE. Accepted values of %s.\n',src);
fprintf(fid,['%% Produced by run_ieee14_gfm_lock_comparison, whose option set is the\n' ...
             '%% flagship driver''s plus agsi_reference=true (opt-in, post-processing only).\n']);
if bitidentity_gated
    fprintf(fid,'%% That re-run was gated on being bit-identical to the delivered artifact.\n');
else
    fprintf(fid,['%% This cache is NOT bit-identical to the earlier delivered artifact, and no\n' ...
                 '%% such claim is made for it: the DC-link closure changed under\n' ...
                 '%% NUM-2026-08-20-01, so the trajectory legitimately differs. Compare it to\n' ...
                 '%% the earlier cache by outcome, never by bit-identity.\n']);
end
fprintf(fid,'%% No value here is rounded, scaled, smoothed or otherwise altered.\n%%\n');
fprintf(fid,['%% Regenerate with:  pf_init_paths; ' ...
             'generate_ieee14_report_scalars(result_file="%s")\n\n'],src);

mac(fid,P,'End',sprintf('%.3f',r.t(end)));
mac(fid,P,'VMin',sprintf('%.6f',min(V(:))));
mac(fid,P,'VMax',sprintf('%.6f',max(V(:))));
mac(fid,P,'FMin',sprintf('%.6f',min(f)));
mac(fid,P,'FMax',sprintf('%.6f',max(f)));
mac(fid,P,'Subdivision',int_or_dash(r,'subdivision_depth'));
mac(fid,P,'DomainRejects',int_or_dash(r,'domain_rejected_trials'));
mac(fid,P,'Residual',pf_tex_sci(max_or_nan(acc),digits=4,plain_range=[1 1]));
mac(fid,P,'Reclose',num_or_dash(r,'actual_reclose_time','%.3f'));
mac(fid,P,'RecloseStatus',tex_escape(char_or_dash(r,'reclose_status')));
mac(fid,P,'SyncDV',fmt_or_dash(g.dV,'%.6f'));
mac(fid,P,'SyncDF',pf_tex_sci(g.df,digits=4,plain_range=[1e-3 1e4]));
mac(fid,P,'SyncDTheta',fmt_or_dash(g.dtheta,'%.6f'));
mac(fid,P,'FirstRelease',nth_or_dash(rel,1,'%.3f'));
mac(fid,P,'ReleaseOne',nth_or_dash(rel,1,'%.3f'));
mac(fid,P,'ReleaseTwo',nth_or_dash(rel,2,'%.3f'));
mac(fid,P,'ReleaseThree',nth_or_dash(rel,3,'%.3f'));
mac(fid,P,'ReleaseFour',nth_or_dash(rel,4,'%.3f'));
mac(fid,P,'AugmentOne',nth_or_dash(aug,1,'%.3f'));
mac(fid,P,'AugmentTwo',nth_or_dash(aug,2,'%.3f'));
mac(fid,P,'AugmentThree',nth_or_dash(aug,3,'%.3f'));
mac(fid,P,'AugmentFour',nth_or_dash(aug,4,'%.3f'));
mac(fid,P,'NRelease',sprintf('%d',numel(rel)));
mac(fid,P,'NAugment',sprintf('%d',numel(aug)));
mac(fid,P,'GfmMax',sprintf('%d',gfm_max(r)));
mac(fid,P,'Samples',sprintf('%d',numel(r.t)));
mac(fid,P,'RejectedSteps',int_or_dash(r,'rejected_steps'));
mac(fid,P,'TerminalF',sprintf('%.6f',f(end)));
mac(fid,P,'TerminalVMin',sprintf('%.4f',min(V(:,end))));
mac(fid,P,'TerminalVMax',sprintf('%.4f',max(V(:,end))));
mac(fid,P,'Stepper',tex_escape(char_or_dash(r,'stepper')));
mac(fid,P,'Reselection',tex_escape(char_or_dash(r,'reselection_status')));

fclose(fid);
fprintf('wrote %s\n',opts.output);

out = struct('output',char(opts.output),'result_file',char(opts.result_file), ...
    't_end',r.t(end),'reclose',num_or_nan(r,'actual_reclose_time'), ...
    'release_times',rel,'augment_times',aug,'n_samples',numel(r.t));
end

% ==========================================================================
function mac(fid,prefix,name,value)
fprintf(fid,'\\newcommand{\\%s%s}{%s}\n',prefix,name,value);
end

function t = applied_times(r,type)
t = [];
if ~isfield(r,'event_log') || isempty(r.event_log), return; end
ty = string({r.event_log.type});
ap = false(1,numel(r.event_log));
for k = 1:numel(r.event_log)
    if isfield(r.event_log(k),'applied') && ~isempty(r.event_log(k).applied)
        ap(k) = logical(r.event_log(k).applied);
    end
end
t = sort([r.event_log(ty == string(type) & ap).t]);
end

function n = gfm_max(r)
n = 0;
if isfield(r,'device_modes_history') && ~isempty(r.device_modes_history)
    n = max(sum(strcmpi(r.device_modes_history,'gfm'),1));
end
end

function v = pick(s,name)
v = NaN;
if isfield(s,name) && ~isempty(s.(name)) && isnumeric(s.(name)) && isscalar(s.(name))
    v = double(s.(name));
end
end

function s = int_or_dash(r,name)
s = '--';
if isfield(r,name) && ~isempty(r.(name)) && isnumeric(r.(name)) && ...
        isscalar(r.(name)) && isfinite(r.(name))
    s = sprintf('%d',round(r.(name)));
end
end

function s = num_or_dash(r,name,f)
s = '--';
v = num_or_nan(r,name);
if isfinite(v), s = sprintf(f,v); end
end

function v = num_or_nan(r,name)
v = NaN;
if isfield(r,name) && ~isempty(r.(name)) && isnumeric(r.(name)) && isscalar(r.(name))
    v = double(r.(name));
end
end

function s = char_or_dash(r,name)
s = '--';
if isfield(r,name) && ~isempty(r.(name)), s = char(string(r.(name))); end
end

function s = fmt_or_dash(v,f)
if isfinite(v), s = sprintf(f,v); else, s = '--'; end
end

function s = nth_or_dash(v,k,f)
s = '--';
if numel(v) >= k && isfinite(v(k)), s = sprintf(f,v(k)); end
end

function v = max_or_nan(x)
if isempty(x), v = NaN; else, v = max(x); end
end

function s = tex_escape(x)
s = strrep(char(string(x)),'\','\textbackslash ');
s = strrep(s,'_','\_');
s = strrep(s,'%','\%');
s = strrep(s,'&','\&');
s = strrep(s,'#','\#');
end

% ==========================================================================
function r = load_result(file)
p = char(file);
if ~isfile(p)
    error('generate_ieee14_report_scalars:missingResult','No result at %s.',p);
end
S = load(p);
if isfield(S,'result'), r = S.result;
elseif isfield(S,'r'), r = S.r;
else
    error('generate_ieee14_report_scalars:badResultFile', ...
        '%s contains neither "result" nor "r".',p);
end
end
