function report_table_helpers(action, varargin)
%REPORT_TABLE_HELPERS  Shared LaTeX table writers for the report generator.
%   report_table_helpers('pf_bus', data, path, caption) writes a PF bus-by-bus
%   comparison table. All tables are generated programmatically from data;
%   no computed value is typed manually.
%
%   Actions: pf_bus, pf_summary, machine_params, fault_event, sssa_eig,
%   ts_metrics, fixed_adaptive_diag, cross_case, input_contract.

switch lower(action)
case 'pf_bus'
    write_pf_bus(varargin{:});
case 'pf_summary'
    write_pf_summary(varargin{:});
case 'machine_params'
    write_machine_params(varargin{:});
case 'fault_event'
    write_fault_event(varargin{:});
case 'sssa_eig'
    write_sssa_eig(varargin{:});
case 'ts_metrics'
    write_ts_metrics(varargin{:});
case 'fixed_adaptive_diag'
    write_fixed_adaptive_diag(varargin{:});
case 'cross_case'
    write_cross_case(varargin{:});
case 'input_contract'
    write_input_contract(varargin{:});
otherwise
    error('report_table_helpers:unknownAction','Unknown action: %s',action);
end
end

function write_pf_bus(bus_ids, vm_ours, va_ours, vm_ref, va_ref, ref_label, path)
fid = fopen(path,'w'); z = onCleanup(@()fclose(fid)); %#ok<NASGU>
fprintf(fid, '%% Generated by report_table_helpers. Do not edit by hand.\n');
fprintf(fid, '\\begin{longtable}{r rrr rrr}\\toprule\n');
fprintf(fid, '{Bus} & {$|V|_{ours}$} & {$|V|_{%s}$} & {$|\\Delta V|$} & {$\\theta_{ours}$} & {$\\theta_{%s}$} & {$|\\Delta\\theta|$} \\\\\n', ref_label, ref_label);
fprintf(fid, '{} & {(pu)} & {(pu)} & {(pu)} & {(deg)} & {(deg)} & {(deg)} \\\\ \\midrule\n');
for k = 1:numel(bus_ids)
    dV = abs(vm_ours(k) - vm_ref(k));
    dA = abs(va_ours(k) - va_ref(k));
    fprintf(fid, '%g & %.6f & %.6f & %.2e & %.6f & %.6f & %.2e \\\\\n', ...
        bus_ids(k), vm_ours(k), vm_ref(k), dV, va_ours(k), va_ref(k), dA);
end
fprintf(fid, '\\bottomrule\n\\end{longtable}\n');
end

function write_pf_summary(summary, path)
fid = fopen(path,'w'); z = onCleanup(@()fclose(fid)); %#ok<NASGU>
fprintf(fid, '%% Generated by report_table_helpers. Do not edit by hand.\n');
fprintf(fid, '\\begin{tabular}{lr}\\toprule Quantity & Value \\\\ \\midrule\n');
fns = fieldnames(summary);
for i = 1:numel(fns)
    v = summary.(fns{i});
    if isnumeric(v), v = num2str(v, '%.6g'); end
    fprintf(fid, '%s & %s \\\\\n', strrep(fns{i},'_','\\_'), v);
end
fprintf(fid, '\\bottomrule\n\\end{tabular}\n');
end

function write_machine_params(gen_buses, H, D, Xdp, source, path)
fid = fopen(path,'w'); z = onCleanup(@()fclose(fid)); %#ok<NASGU>
fprintf(fid, '%% Generated by report_table_helpers. Do not edit by hand.\n');
fprintf(fid, '\\begin{tabular}{r llll l}\\toprule\n');
fprintf(fid, '{Bus} & {$H$} & {$D$} & {$X''_d$} & {Source} \\\\ \n');
fprintf(fid, '{} & {(s)} & {(pu)} & {(pu)} & {} \\\\ \\midrule\n');
for k = 1:numel(gen_buses)
    src = ''; if numel(source) >= k, src = source{k}; end
    fprintf(fid, '%g & %.4f & %.4f & %.4f & %s \\\\\n', ...
        gen_buses(k), H(k), D(k), Xdp(k), src);
end
fprintf(fid, '\\bottomrule\n\\end{tabular}\n');
end

function write_fault_event(sc, path)
fid = fopen(path,'w'); z = onCleanup(@()fclose(fid)); %#ok<NASGU>
fprintf(fid, '%% Generated by report_table_helpers. Do not edit by hand.\n');
fprintf(fid, '\\begin{tabular}{ll}\\toprule Field & Value \\\\ \\midrule\n');
fprintf(fid, 'Fault bus & %g \\\\\n', sc.fault_bus);
fprintf(fid, 'Fault impedance $Z_f$ & %.4g %+.4gj pu \\\\\n', real(sc.Zf), imag(sc.Zf));
fprintf(fid, 'Fault application time & %.4f s \\\\\n', sc.t_fault);
fprintf(fid, 'Fault clearing time & %.4f s \\\\\n', sc.t_clear);
fprintf(fid, 'Simulation end time & %.4f s \\\\\n', sc.t_end);
fprintf(fid, 'Time step $h$ & %.4f s \\\\\n', sc.dt);
fprintf(fid, '\\bottomrule\n\\end{tabular}\n');
end

function write_sssa_eig(eigs_ours, eigs_ref, ref_label, path)
fid = fopen(path,'w'); z = onCleanup(@()fclose(fid)); %#ok<NASGU>
fprintf(fid, '%% Generated by report_table_helpers. Do not edit by hand.\n');
fprintf(fid, '\\begin{longtable}{r cc cc ll}\\toprule\n');
fprintf(fid, 'No. & {$\\lambda_{ours}$} & {$\\lambda_{%s}$} & {$f_{ours}$ (Hz)} & {$\\zeta_{ours}$ (\\%%)} & Mode \\\\ \\midrule\n', ref_label);
n = max(numel(eigs_ours), numel(eigs_ref));
for k = 1:n
    lo = eigs_ours(k); lr = eigs_ref(k);
    fo = abs(imag(lo))/(2*pi); zo = -real(lo)/(abs(lo)+eps)*100;
    if abs(imag(lo))<1e-9, so = sprintf('%.4f',real(lo)); else, so = sprintf('%.4f%+.4fj',real(lo),imag(lo)); end
    if abs(imag(lr))<1e-9, sr = sprintf('%.4f',real(lr)); else, sr = sprintf('%.4f%+.4fj',real(lr),imag(lr)); end
    fprintf(fid, '%d & $%s$ & $%s$ & %.4f & %.3f & \\\\\n', k, so, sr, fo, zo);
end
fprintf(fid, '\\bottomrule\n\\end{longtable}\n');
end

function write_ts_metrics(metrics, path)
fid = fopen(path,'w'); z = onCleanup(@()fclose(fid)); %#ok<NASGU>
fprintf(fid, '%% Generated by report_table_helpers. Do not edit by hand.\n');
fprintf(fid, '\\begin{tabular}{lrrrr}\\toprule Metric & Unit & Ours & PSAT & PGAz \\\\ \\midrule\n');
fns = fieldnames(metrics);
for i = 1:numel(fns)
    m = metrics.(fns{i});
    fprintf(fid, '%s & %s & %.4e & %.4e & %.4e \\\\\n', ...
        strrep(fns{i},'_','\\_'), m.unit, m.ours, m.psat, m.pgaz);
end
fprintf(fid, '\\bottomrule\n\\end{tabular}\n');
end

function write_fixed_adaptive_diag(diag, path)
fid = fopen(path,'w'); z = onCleanup(@()fclose(fid)); %#ok<NASGU>
fprintf(fid, '%% Generated by report_table_helpers. Do not edit by hand.\n');
fprintf(fid, '\\begin{tabular}{lr}\\toprule Diagnostic & Value \\\\ \\midrule\n');
fprintf(fid, 'Accepted steps & %d \\\\\n', diag.accepted_steps);
fprintf(fid, 'Rejected steps & %d \\\\\n', diag.rejected_steps);
fprintf(fid, 'dt min & %.4e s \\\\\n', diag.dt_min);
fprintf(fid, 'dt max & %.4e s \\\\\n', diag.dt_max);
fprintf(fid, 'dt mean & %.4e s \\\\\n', diag.dt_mean);
fprintf(fid, 'Error estimator max & %.4e \\\\\n', diag.lte_max);
fprintf(fid, 'Max $\\Delta\\delta_{COI}$ & %.4e deg \\\\\n', diag.max_dcoi);
fprintf(fid, 'Max pairwise angle diff & %.4e deg \\\\\n', diag.max_pairwise);
fprintf(fid, 'Max $\\Delta\\omega$ & %.4e pu \\\\\n', diag.max_domega);
fprintf(fid, 'Max $\\Delta P_e$ & %.4e pu \\\\\n', diag.max_dpe);
fprintf(fid, 'Max $\\Delta V_{bus}$ & %.4e pu \\\\\n', diag.max_dvbus);
fprintf(fid, 'Readiness label & %s \\\\\n', diag.readiness_label);
fprintf(fid, '\\bottomrule\n\\end{tabular}\n');
end

function write_cross_case(rows, path)
fid = fopen(path,'w'); z = onCleanup(@()fclose(fid)); %#ok<NASGU>
fprintf(fid, '%% Generated by report_table_helpers. Do not edit by hand.\n');
fprintf(fid, '\\begin{longtable}{lrrrrr l}\\toprule\n');
fprintf(fid, 'Case & PF max mismatch & PF ext. err & Dominant mode & TS bounded & Fixed/Adaptive diff & Status \\\\ \\midrule\n');
for i = 1:numel(rows)
    r = rows(i);
    fprintf(fid, '%s & %.2e & %.2e & %s & %s & %.2e & %s \\\\\n', ...
        r.case_name, r.pf_max_mismatch, r.pf_ext_err, r.dominant_mode, ...
        r.ts_bounded, r.fa_diff, r.status);
end
fprintf(fid, '\\bottomrule\n\\end{longtable}\n');
end

function write_input_contract(fp, path)
fid = fopen(path,'w'); z = onCleanup(@()fclose(fid)); %#ok<NASGU>
fprintf(fid, '%% Generated by report_table_helpers. Do not edit by hand.\n');
fprintf(fid, '\\begin{tabular}{ll}\\toprule Field & Value \\\\ \\midrule\n');
fns = fieldnames(fp);
for i = 1:numel(fns)
    v = fp.(fns{i});
    if isnumeric(v), v = mat2str(v(:).'); end
    if ischar(v) && strlen(v) > 60, v = [v(1:60) '...']; end
    fprintf(fid, '%s & %s \\\\\n', strrep(fns{i},'_','\\_'), v);
end
fprintf(fid, '\\bottomrule\n\\end{tabular}\n');
end

function n = strlen(s)
n = numel(s);
end
