function write_pf_tables(pf,outdir,lim)
%WRITE_PF_TABLES Publish bus/line power-flow tables (CSV + LaTeX).
%   WRITE_PF_TABLES(PF,OUTDIR) writes the standard tables.  The optional
%   third argument LIM is the per-bus limit table from pf_limit_table; its
%   Pmax_pu column is joined in, and Q_min/Q_max always come from the PF
%   struct itself (SOURCE_DEFINED).  Presentation only: numbers are the
%   solved PF values and the case-defined limits, never tuned.
if nargin<3, lim=[]; end
bus=table(pf.external_bus_ids(:),pf.bus_type(:),pf.bus_voltage(:), ...
    pf.bus_angle_deg(:),pf.P_generation(:),pf.Q_generation(:), ...
    pf.P_load(:),pf.Q_load(:),'VariableNames', ...
    {'bus','type','V_pu','angle_deg','Pg_pu','Qg_pu','Pl_pu','Ql_pu'});
bus.Qmin_pu=pf.Q_min(:); bus.Qmax_pu=pf.Q_max(:);
bus.Pmax_pu=NaN(height(bus),1);
if ~isempty(lim)
    for k=1:height(bus)
        j=find(lim.bus==bus.bus(k),1);
        if ~isempty(j), bus.Pmax_pu(k)=lim.Pmax_pu(j); end
    end
end
bus.Qmin_pu(~isfinite(bus.Qmin_pu))=NaN; bus.Qmax_pu(~isfinite(bus.Qmax_pu))=NaN;
writetable(bus,fullfile(outdir,'pf_bus_results.csv'));
fid=fopen(fullfile(outdir,'table_pf_bus_results.tex'),'w'); cleaner=onCleanup(@()fclose(fid));
fprintf(fid,'%% Generated by scripts/reporting/write_pf_tables.m.\n');
fprintf(fid,'\\begin{tabular*}{\\textwidth}{@{\\extracolsep{\\fill}}rlrrrrrrrrr@{}}\\toprule\n');
fprintf(fid,'Bus & Type & $|V|$ & $\\theta$ (deg) & $P_g$ & $Q_g$ & $P_L$ & $Q_L$ & $Q_{min}$ & $Q_{max}$ & $P_{max}$ \\\\ \\midrule\n');
for k=1:height(bus)
    v=[bus.V_pu(k),bus.angle_deg(k),bus.Pg_pu(k),bus.Qg_pu(k),bus.Pl_pu(k),bus.Ql_pu(k)];
    v(abs(v)<0.5e-5)=0; % suppress signed zero at the published precision
    fprintf(fid,'%d & %s & %.5f & %.4f & %.5f & %.5f & %.5f & %.5f & %s & %s & %s \\\\\n', ...
        bus.bus(k),type_name(bus.type(k)),v(1),v(2),v(3),v(4),v(5),v(6), ...
        fmt_limit(bus.Qmin_pu(k)),fmt_limit(bus.Qmax_pu(k)),fmt_limit(bus.Pmax_pu(k)));
end
fprintf(fid,'\\bottomrule\\end{tabular*}\n'); clear cleaner

ep=pf.line_endpoints; line=table((1:size(ep,1)).',ep(:,1),ep(:,2), ...
    pf.line_flow_P(:),pf.line_flow_Q(:),pf.line_loss_P(:),pf.line_loss_Q(:), ...
    'VariableNames',{'line','from_bus','to_bus','P_from_pu','Q_from_pu','P_loss_pu','Q_loss_pu'});
writetable(line,fullfile(outdir,'pf_line_results.csv'));
fid=fopen(fullfile(outdir,'table_pf_line_results.tex'),'w'); cleaner=onCleanup(@()fclose(fid));
fprintf(fid,'%% Generated by scripts/reporting/write_pf_tables.m.\n');
fprintf(fid,'\\begin{tabular*}{\\textwidth}{@{\\extracolsep{\\fill}}rrrrrrr@{}}\\toprule\nLine & From & To & $P_{from}$ & $Q_{from}$ & $P_{loss}$ & $Q_{loss}$ \\\\ \\midrule\n');
for k=1:height(line)
    v=[line.P_from_pu(k),line.Q_from_pu(k),line.P_loss_pu(k),line.Q_loss_pu(k)];
    v(abs(v)<0.5e-6)=0; % suppress signed zero at the published precision
    fprintf(fid,'%d & %d & %d & %.6f & %.6f & %.6f & %.6f \\\\\n', ...
        line.line(k),line.from_bus(k),line.to_bus(k),v(1),v(2),v(3),v(4));
end
fprintf(fid,'\\bottomrule\\end{tabular*}\n'); clear cleaner
end

function s=type_name(t)
if t==1, s='REF'; elseif t==2, s='PV'; elseif t==3, s='PQ'; else, s='?'; end
end

function s=fmt_limit(x)
if ~isfinite(x) || isnan(x), s='--'; else, s=sprintf('%.4g',x); end
end
