pf_init_paths;
outdir = fullfile(pwd, 'output', 'gui_capture', 'all_graphs');
if ~exist(outdir,'dir'); mkdir(outdir); end

% GUI captures generated by same capture script used for visual smoke checks.
capture_gui;
copyfile(fullfile(pwd,'output','gui_capture','04_analysis.png'), fullfile(outdir,'gui_01_analysis.png'));
copyfile(fullfile(pwd,'output','gui_capture','05_nr_results.png'), fullfile(outdir,'gui_02_nr_results.png'));
copyfile(fullfile(pwd,'output','gui_capture','02_smib_tab.png'), fullfile(outdir,'gui_03_smib_light.png'));
copyfile(fullfile(pwd,'output','gui_capture','03_smib_dark.png'), fullfile(outdir,'gui_04_smib_dark.png'));

% Standalone SMIB figures through the same GUI actions users click.
app = struct();
app.last_result=[]; app.last_cpf=[]; app.last_suite=[]; app.last_opf=[];
app.last_smib=[]; app.last_case_data=[]; app.progress_dialog=[]; app.fig=[];
[app.case_labels, app.case_loaders] = pfapp.make_case_registry();
app.case_labels{end+1}='Custom n-bus: (none)'; app.case_loaders{end+1}=[];
[fig, app] = pfapp.create_gui_layout(app); app.fig=fig; fig.Visible='off'; drawnow; fig.UserData.app=app;
pfapp.wire_callbacks(app, fig);

% Classical: root locus, step response, power response.
app = fig.UserData.app;
idx = find(~cellfun(@isempty, regexpi(app.case_dropdown.Items,'kundur smib classical')),1);
app.case_dropdown.Value = app.case_dropdown.Items{idx};
app = pfapp.on_case_changed(app);
app = pfapp.run_selected_action(app, fig); fig.UserData.app = app;
before = findall(0,'Type','figure');
pfapp.open_smib_figure(app); drawnow; pause(0.5);
capture_new_figures(before, outdir, 'smib_classical');

% PSS: eigen comparison, step response, mode shape.
app = fig.UserData.app;
idx = find(~cellfun(@isempty, regexpi(app.case_dropdown.Items,'kundur smib pss')),1);
app.case_dropdown.Value = app.case_dropdown.Items{idx};
app = pfapp.on_case_changed(app);
app = pfapp.run_selected_action(app, fig); fig.UserData.app = app;
before = findall(0,'Type','figure');
pfapp.open_smib_figure(app); drawnow; pause(0.5);
capture_new_figures(before, outdir, 'smib_pss');

% Power-flow standalone for Kundur Ex12.6.
pf = pfsolver.powerflow_newton_raphson(cases.case_kundur_two_area_classical(), struct('plot_results',false,'verbose',false,'max_iter',50,'tolerance',1e-8,'enforce_q_limits',false));
before = findall(0,'Type','figure');
pfapp.open_powerflow_figure(pf); drawnow; pause(0.5);
capture_new_figures(before, outdir, 'pf_kundur_ex126');

close(allchild(0));
if isvalid(fig); delete(fig); end
fprintf('captured all graphs to %s\n', outdir);

function capture_new_figures(before, outdir, prefix)
after = findall(0,'Type','figure');
newfigs = setdiff(after, before);
for i = 1:numel(newfigs)
    h = newfigs(i);
    if ~isvalid(h); continue; end
    name = regexprep(char(h.Name), '[^A-Za-z0-9_ -]', '');
    name = regexprep(strtrim(name), '\s+', '_');
    if isempty(name); name = sprintf('figure_%02d', i); end
    path = fullfile(outdir, sprintf('%s_%02d_%s.png', prefix, i, name));
    exportgraphics(h, path, 'Resolution', 180);
end
close(newfigs);
end
