function audit=audit_ne39_voltage_dispatch_run(raw_file)
%AUDIT_NE39_VOLTAGE_DISPATCH_RUN ตรวจ raw ของ short SG-cycle production arm.
% อ่าน accepted samples เท่านั้น ไม่แก้ state หรือให้ transition commit authority.
arguments
    raw_file (1,1) string
end
pf_init_paths(); data=load(raw_file,'request','result');
r=data.result; request=data.request; s=request.scenario; c=s.case_data;
audit=struct('artifact',char(raw_file),'scope','SHORT_SG_CYCLE_ACCEPTED_SAMPLES', ...
    'status','NO_TRAJECTORY','samples_checked',0,'snapshot_failures',0, ...
    'snapshot_unknowns',0,'first_snapshot_failure_time',NaN, ...
    'first_snapshot_failure_reason','','max_full_kcl',NaN, ...
    'trip_committed',false,'trip_atomic_samples',false,'private_trial_pass',false, ...
    'target_modes_match',false,'sg_state_continuous',false, ...
    'dc_state_continuous',false,'max_transfer_current_jump',NaN, ...
    'strict_lte_pass',false,'horizon_reached',false, ...
    'actual_reclose_time',r.actual_reclose_time,'reclose_status',r.reclose_status);
if isempty(r.t), return; end
if ~strcmp(request.options.ibr_events.event_profile,'sg_cycle') || ...
        ~all(strcmp(r.topology_history,'pre'))
    error('audit_ne39_voltage_dispatch_run:scope', ...
        'audit นี้รองรับ short SG-cycle ที่ไม่เปลี่ยน network เท่านั้น');
end
[devices,~]=stability.build_mixed_resource_devices(c,s.resources,s.scenario_opt);
dae=stability.composite_dae(c,devices,struct('load_model','cz_p_cz_q'));
bounds=struct('v_min',.9,'v_max',1.1, ...
    'f_min',c.base_values.frequency_Hz-.5,'f_max',c.base_values.frequency_Hz+.5);
kcl=zeros(1,numel(r.t));
for k=1:numel(r.t)
    ec=r.event_context_history{k}; x=r.x_traj(:,k); y=r.y_traj(:,k); u=r.u_history(:,k);
    V=complex(y(1:2:end),y(2:2:end));
    kcl(k)=norm(dae.Ynet*V-dae.current_injection(r.t(k),x,y,u,ec),inf);
    e=stability.ne39_transition_snapshot(r.t(k),x,y,u,ec,dae,s.resources,c,bounds);
    audit.samples_checked=audit.samples_checked+1;
    audit.snapshot_failures=audit.snapshot_failures+strcmp(e.status,'FAIL');
    audit.snapshot_unknowns=audit.snapshot_unknowns+~any(strcmp(e.status,{'PASS','FAIL'}));
    if ~strcmp(e.status,'PASS') && isnan(audit.first_snapshot_failure_time)
        audit.first_snapshot_failure_time=r.t(k);
        audit.first_snapshot_failure_reason=e.reason;
        audit.first_snapshot_failure_records=e.records;
    end
end
audit.max_full_kcl=max(kcl);
audit.strict_lte_pass=isfield(r,'adaptive_strict_lte') && r.adaptive_strict_lte && ...
    r.floor_accepted_steps==0 && all(isfinite(r.lte_history)) && all(r.lte_history<=1);
audit.horizon_reached=r.converged && abs(r.t(end)-request.options.t_end)<=1e-12;
if isfield(r,'controller_audit') && isfield(r.controller_audit,'ne39_transition')
    a=r.controller_audit.ne39_transition;
    audit.private_trial_pass=strcmp(a.status,'PASS') && ~a.commit_authorized && ...
        numel(a.passes)==2 && a.refinement_samples==a.passes{1}.steps && ...
        a.refinement_error<=1e-5 && ...
        all(cellfun(@(p)strcmp(p.reason,'TRIAL_COMPLETE') && ...
            abs(p.t_reached-a.horizon_s)<=1e-12 && p.energy_error_pu_s<=1e-6,a.passes));
end
trips=find(strcmp({r.event_log.type},'sg_trip'));
if isscalar(trips)
    log=r.event_log(trips); audit.trip_committed=log.applied;
    at=find(abs(r.t-log.t)<=1e-12);
    audit.trip_atomic_samples=log.applied && numel(at)==2 && ...
        isequal(r.sample_side(at),{'left','right'}) && ...
        all(r.transaction_id(at)==log.transaction_id);
    if audit.trip_atomic_samples
        left=at(1); right=at(2); sg=find(strcmp({devices.device_type},'sg_classical'));
        ib=find(strcmp({s.resources.resource_type},'ibr'));
        audit.target_modes_match=isequal(sort(log.selected_gfm_indices(:)),sort(ib(:))) && ...
            all(strcmpi(r.device_modes_history(ib,right),'gfm')) && ...
            all(~r.device_online_history(sg,right));
        sgx=[]; dcx=[]; jumps=zeros(size(ib));
        for k=sg(:)'
            sgx=[sgx,dae.device_offsets(k)+(1:devices(k).nx)]; %#ok<AGROW>
        end
        for q=1:numel(ib)
            k=ib(q); d=devices(k); xr=dae.device_offsets(k)+(1:d.nx);
            ur=dae.u_offsets(k)+(1:d.nu);
            dcx=[dcx,xr(3),xr(strcmp(d.state_names,'I_dc'))]; %#ok<AGROW>
            yl=r.y_traj(:,left);
            Il=d.current_injection(log.t,r.x_traj(xr,left),yl, ...
                r.u_history(ur,left),r.event_context_history{left});
            Ir=d.current_injection(log.t,r.x_traj(xr,right),yl, ...
                r.u_history(ur,right),r.event_context_history{right});
            jumps(q)=abs(Ir-Il);
        end
        audit.sg_state_continuous=isequal(r.x_traj(sgx,left),r.x_traj(sgx,right));
        audit.dc_state_continuous=isequal(r.x_traj(dcx,left),r.x_traj(dcx,right));
        audit.max_transfer_current_jump=max(jumps);
    end
end
passed=audit.horizon_reached && audit.strict_lte_pass && audit.private_trial_pass && ...
    audit.trip_atomic_samples && ...
    audit.target_modes_match && audit.sg_state_continuous && audit.dc_state_continuous && ...
    audit.max_transfer_current_jump<=1e-10 && audit.max_full_kcl<=1e-6 && ...
    audit.snapshot_failures==0 && audit.snapshot_unknowns==0;
audit.status='SHORT_PRODUCTION_ARM_NOT_VERIFIED';
if passed, audit.status='SHORT_PRODUCTION_ARM_VERIFIED_NOT_FULL_CHRONOLOGY'; end
folder=fileparts(raw_file);
audit_file=fullfile(folder,['audit_' char(datetime('now','Format','yyyyMMdd_HHmmss_SSS')) '.mat']);
save(audit_file,'audit','-v7.3');
fprintf(['PRODUCTION_AUDIT status=%s samples=%d snapshots_fail=%d unknown=%d ' ...
    'kcl=%.9g trip=%d atomic=%d target=%d sg_cont=%d dc_cont=%d ' ...
    'current_jump=%.9g strict_lte=%d private_trial=%d horizon=%d\n'], ...
    audit.status,audit.samples_checked,audit.snapshot_failures,audit.snapshot_unknowns, ...
    audit.max_full_kcl,audit.trip_committed,audit.trip_atomic_samples,audit.target_modes_match, ...
    audit.sg_state_continuous,audit.dc_state_continuous,audit.max_transfer_current_jump, ...
    audit.strict_lte_pass,audit.private_trial_pass,audit.horizon_reached);
end
