restoredefaultpath;
cd(fileparts(fileparts(fileparts(mfilename('fullpath')))));
pf_init_paths;
s = cases.scenario_ieee14_1sg_4ibr(struct('case_profile','eecon49_figure4'));
ev = struct('enabled',true,'event_profile','chronology', ...
    'sg_trip',20,'load_step',50,'load_step_factor',0.20, ...
    'fault_on',85,'fault_clear',85.15,'fault_bus',9,'Zf',0.01+0.01i, ...
    'line_trip',110,'line_from_bus',6,'line_to_bus',13, ...
    'restore_time',145,'sg_on',145, ...
    'coordinated_handback',true, ...
    'selected_gfm_indices',2:5,'reference_resource_index',2, ...
    'automatic_gfm_switching',true, ...
    'delays_overrides',struct('timeout_s',5,'dwell_s',0.5));
opt = struct('t_end',160,'dt',0.0125,'verbose',false, ...
    'ibr_events',ev,'plot_results',false);
tic;
r = stability.run_hybrid_case(s,opt);
elapsed = toc;
save('output/diagnostics/regfm_post_trip_probe.mat','r','elapsed','-v7.3');
accepted_max = NaN;
if isfield(r,'accepted_residual_per_step') && any(isfinite(r.accepted_residual_per_step))
    accepted_max = max(r.accepted_residual_per_step(isfinite(r.accepted_residual_per_step)));
end
fprintf(['DONE conv=%d tend=%.6f elapsed=%.2f fail=%s accepted=%.3g ' ...
    'attempted=%.3g steps=%d sub=%d\n'], ...
    r.converged,r.t(end),elapsed,string(r.failure_id), ...
    accepted_max,max(r.residual_per_step),numel(r.residual_per_step),r.subdivision_depth);
