function out = run_locked_gfl_diag_250s(varargin)
%RUN_LOCKED_GFL_DIAG_250S  Diagnostic continuation of the all-GFL island past
% the SG trip.
%
% Optional name-value overrides (numerical-method knobs for probing only; the
% defaults reproduce the delivered arm's discretization):
%   'TEnd'      (default 250)   'Dt'        (default 0.05)
%   'Stepper'   (default 'adaptive')   'Predictor' (default 'linear_kcl')
%   'OutFile'   (default 'locked_gfl_diag_250s.mat')
%
% The delivered locked_gfl arm (run_ieee14_gfm_lock_comparison.m) fails closed
% at t=20 s with noVoltageFormingSource: the per-island voltage-forming check
% refuses the SG-off island in which every converter is locked grid-following.
% That refusal is the PRODUCTION contract and is unchanged here.
%
% This script re-runs the SAME arm with the opt-in diagnostic option
% allow_no_vf_island=true so the trajectory shows how the four-GFL island
% actually behaves past the trip (large PLL-driven oscillations expected).
% Classification: ASSUMED_DIAGNOSTIC. It may be used for presentation
% figures only; it is not a readiness claim.
%
% Option and arm provenance: the option set below is copied verbatim from
% run_ieee14_gfm_lock_comparison.m base_request(dt=0.05, t_end=250) plus
% arms(5).locked_gfl overrides (events.automatic_gfm_switching=false,
% opt.automatic_support_supervision=true). The ONLY addition is
% opt.allow_no_vf_island=true.
%
% Output: output/diagnostics/ieee14_locked_gfl_diag/locked_gfl_diag_250s.mat
%   .result / .elapsed / .classification / .note / .option / .generated

pf_init_paths();

ip = inputParser;
ip.addParameter('TEnd',250); ip.addParameter('Dt',0.05);
ip.addParameter('Stepper','adaptive'); ip.addParameter('Predictor','linear_kcl');
ip.addParameter('OutFile','locked_gfl_diag_250s.mat');
ip.parse(varargin{:});

% --- base_request(t_end=250, dt=0.05), copied verbatim ---------------------
sys = ibr.build_ieee14_switch_system(index_mode='agsi_pp', ...
    case_profile='eecon49_figure4',sg_H=2.5,sg_D=1.0, ...
    T_d_on=0.10,T_d_off=1.0);

scenario = cases.scenario_ieee14_1sg_4ibr( ...
    struct('case_profile','eecon49_figure4'));

selector_table = stability.ibr_selector_table(scenario.case_data, ...
    scenario.resources,scenario,struct());

events = struct('enabled',true,'event_profile','chronology', ...
    'sg_trip',20,'load_step',50,'load_step_factor',0.20, ...
    'fault_on',85,'fault_clear',85.15,'fault_bus',9,'Zf',0.01+0.01i, ...
    'line_trip',110,'line_from_bus',6,'line_to_bus',13, ...
    'restore_time',145,'sg_on',145,'coordinated_handback',false, ...
    'delays_overrides',struct('timeout_s',20,'dwell_s',0.5));

opt = struct( ...
    't_end',ip.Results.TEnd,'dt',ip.Results.Dt,'verbose',false,'plot_results',false, ...
    'max_step_subdivisions',12,'state_predictor',ip.Results.Predictor, ...
    'severity_gamma_on',0.65,'severity_gamma_off',0.35, ...
    'severity_T_d_on',0.10,'severity_T_d_off',1.00, ...
    'healthy_pf_V',sys.pf.bus_voltage(:).', ...
    'healthy_pf_bus_ids',sys.pf.external_bus_ids(:).', ...
    'stepper',ip.Results.Stepper,'reject_limit',20, ...
    'support_transition_certificate',true, ...
    'handback_efd_timescale','control', ...
    'agsi_reference',true, ...
    'selector_table',selector_table);

% --- arms(5).locked_gfl overrides -----------------------------------------
events.automatic_gfm_switching = false;
opt.automatic_support_supervision = true;

% --- the diagnostic addition (the only difference from the delivered arm) --
opt.allow_no_vf_island = true;
opt.ibr_events = events;
% Phase-gauge pin (slack-gauge fix): with the SG gone and every converter
% grid-following, the island has no absolute-angle reference, so the coupled
% Newton Jacobian is rank-deficient by exactly one (the rotation gauge) and
% Newton diverges at any step size (the t=22.08 s wall, identical across
% steppers/predictors and independent of the DC closure). Pinning
% imag(V_bus1)=0 after the trip selects the gauge member the delivered
% reference bus already used; the replaced KCL row holds identically on that
% member, and the observables (|V|, P, Q, frequency) are gauge-invariant.
opt.angle_gauge_bus = 1;
opt.angle_gauge_after = events.sg_trip + 0.25;

% Comparison-only cloned devices (ASSUMED_DIAGNOSTIC): the four IBRs are built
% by ibr.eecon49_dual_mode_ideal_dc, a clone of eecon49_dual_mode_model whose
% DC closure reverts to the retired ideal EECON49 law
% (dVdc/dt=(Vdc0-Vdc)/Tdc, Tdc=0.10 s) -- the model the EECON49 paper's
% Fixed-GFL figure used. Under the delivered Thevenin closure the all-GFL
% island's Vdc was NOT the binding wall (a clone run with the ideal closure
% still stopped at t=22.075); the real blocker was the phase gauge, fixed by
% the angle_gauge_bus pin below. The ideal closure is kept anyway so the
% diagnostic arm matches the paper's DC model and Vdc cannot wander toward
% the Pac/Vdc singularity during long violent oscillations. Production builds
% are untouched: the override reaches the device factory only through
% scenario_opt.ibr_factory_override, which no production caller sets.
scenario.scenario_opt.ibr_factory_override = struct();
scenario.scenario_opt.ibr_factory_override.IBR2 = @ibr.eecon49_dual_mode_ideal_dc;
scenario.scenario_opt.ibr_factory_override.IBR3 = @ibr.eecon49_dual_mode_ideal_dc;
scenario.scenario_opt.ibr_factory_override.IBR6 = @ibr.eecon49_dual_mode_ideal_dc;
scenario.scenario_opt.ibr_factory_override.IBR8 = @ibr.eecon49_dual_mode_ideal_dc;

fprintf('running locked_gfl diagnostic arm (allow_no_vf_island=true) ...\n');
t0 = tic;
r = stability.run_hybrid_case(scenario,opt);
elapsed = toc(t0);

outdir = fullfile('output','diagnostics','ieee14_locked_gfl_diag');
if ~isfolder(outdir), mkdir(outdir); end
S = struct( ...
    'result',r, ...
    'elapsed',elapsed, ...
    'classification','ASSUMED_DIAGNOSTIC', ...
    'note',['locked_gfl arm re-run with allow_no_vf_island=true ' ...
            '(opt-in diagnostic suspension of the noVoltageFormingSource ' ...
            'refusal; the production refusal is unchanged) and with the four ' ...
            'IBRs built by the comparison-only clone ' ...
            'ibr.eecon49_dual_mode_ideal_dc (retired ideal DC closure, ' ...
            'ASSUMED_DIAGNOSTIC)'], ...
    'option',['events.automatic_gfm_switching=false; ' ...
              'opt.automatic_support_supervision=true; ' ...
              'opt.allow_no_vf_island=true; scenario_opt.ibr_factory_override=' ...
              '@ibr.eecon49_dual_mode_ideal_dc for IBR2/3/6/8; otherwise ' ...
              'identical to run_ieee14_gfm_lock_comparison ' ...
              'base_request(dt=0.05,t_end=250)'], ...
    'generated',char(datetime('now')));
cache = fullfile(outdir,ip.Results.OutFile);
save(cache,'-struct','S','-v7.3');
fid = fullfile(outdir,'provenance.txt');
f = fopen(fid,'w');
fprintf(f,'Generated by scripts/diagnostics/run_locked_gfl_diag_250s.m\n');
fprintf(f,'Date: %s\n',char(datetime('now')));
fprintf(f,'Classification: ASSUMED_DIAGNOSTIC\n');
fprintf(f,['Option: allow_no_vf_island=true (opt-in diagnostic suspension of\n' ...
            'the per-island voltage-forming refusal at the SG trip).\n' ...
            'The production refusal is unchanged: with the option absent the\n' ...
            'F2 transaction is byte-identical to the delivered contract.\n' ...
            'Devices: the four IBRs are built by the comparison-only clone\n' ...
            'ibr.eecon49_dual_mode_ideal_dc -- retired ideal DC closure\n' ...
            'dVdc/dt=(Vdc0-Vdc)/Tdc, Tdc=0.10 s (the model the EECON49\n' ...
            'paper Fixed-GFL figure used). The SG device is unchanged.\n' ...
            'Arm provenance: run_ieee14_gfm_lock_comparison arms(5) locked_gfl\n' ...
            'on base_request(dt=0.05, t_end=250), eecon49_figure4 profile.\n']);
fclose(f);
fprintf(['DONE elapsed=%.1f s  converged=%d  t_end=%.6f  failure=%s\n' ...
         'wrote %s\n'],elapsed,logical(r.converged),r.t(end), ...
         char(string(r.failure_id)),cache);
out = struct('result',r,'cache',cache,'elapsed',elapsed);
end
