function out = run_locked_gfl_thevenin_250s(varargin)
%RUN_LOCKED_GFL_THEVENIN_250S  All-GFL island past the SG trip, on the
% DELIVERED Thevenin DC closure.
%
% This is run_locked_gfl_diag_250s with ONE difference: the four IBRs are the
% production ibr.eecon49_dual_mode_model devices, so the non-ideal Thevenin DC
% link with its overvoltage chopper is retained.  Every other option, event
% time and gauge setting is copied from that script verbatim.
%
% Why this arm exists.  run_locked_gfl_diag_250s substitutes the retired ideal
% DC closure (dVdc/dt=(Vdc0-Vdc)/Tdc) through scenario_opt.ibr_factory_override.
% Its own comment records that BOTH closures hit the same t=22.075 s wall
% before the phase-gauge pin was added, and that the pin -- not the DC model --
% is what let the arm run.  The combination "gauge pin + delivered Thevenin
% closure" was therefore never tried.  It removes one of the three diagnostic
% opt-ins, which makes the resulting arm strictly closer to production, and the
% DC dynamics it restores are the ones that can actually be excited by a long
% ungoverned oscillation.
%
% Classification remains ASSUMED_DIAGNOSTIC: allow_no_vf_island=true and the
% angle_gauge_bus=1 pin are still opt-in, and the production
% noVoltageFormingSource refusal at t=20 s is unchanged.  Comparative
% statements only; never a readiness claim.
%
% Output: output/diagnostics/ieee14_locked_gfl_diag/<OutFile>

pf_init_paths();

ip = inputParser;
ip.addParameter('TEnd',250); ip.addParameter('Dt',0.05);
ip.addParameter('Stepper','adaptive'); ip.addParameter('Predictor','linear_kcl');
ip.addParameter('DtMax',[]);
ip.addParameter('OutFile','locked_gfl_diag_gauge_thevenin_250s.mat');
ip.parse(varargin{:});

sys = ibr.build_ieee14_switch_system(index_mode='agsi_pp', ...
    case_profile='eecon49_figure4',sg_H=2.5,sg_D=1.0, ...
    T_d_on=0.10,T_d_off=1.0);

scenario = cases.scenario_ieee14_1sg_4ibr( ...
    struct('case_profile','eecon49_figure4'));

selector_table = stability.ibr_selector_table(scenario.case_data, ...
    scenario.resources,scenario,struct());

events = struct('enabled',true,'event_profile','chronology', ...
    'sg_trip',20,'load_step',50,'load_step_factor',0.20, ...
    'fault_on',85,'fault_clear',85.15,'fault_bus',9,'Zf',0.01+0.01i, ...
    'line_trip',110,'line_from_bus',6,'line_to_bus',13, ...
    'restore_time',145,'sg_on',145,'coordinated_handback',false, ...
    'delays_overrides',struct('timeout_s',20,'dwell_s',0.5));

opt = struct( ...
    't_end',ip.Results.TEnd,'dt',ip.Results.Dt,'verbose',false,'plot_results',false, ...
    'max_step_subdivisions',12,'state_predictor',ip.Results.Predictor, ...
    'severity_gamma_on',0.65,'severity_gamma_off',0.35, ...
    'severity_T_d_on',0.10,'severity_T_d_off',1.00, ...
    'healthy_pf_V',sys.pf.bus_voltage(:).', ...
    'healthy_pf_bus_ids',sys.pf.external_bus_ids(:).', ...
    'stepper',ip.Results.Stepper,'reject_limit',20, ...
    'support_transition_certificate',true, ...
    'handback_efd_timescale','control', ...
    'agsi_reference',true, ...
    'selector_table',selector_table);

events.automatic_gfm_switching = false;
opt.automatic_support_supervision = true;
opt.allow_no_vf_island = true;
opt.ibr_events = events;
opt.angle_gauge_bus = 1;
opt.angle_gauge_after = events.sg_trip + 0.25;

% dt_max ceiling.  The adaptive controller defaults to dt_max = 10*dt, so the
% base dt alone fixes how coarse an ACCEPTED sample may be.  Passing DtMax
% explicitly lets a probe hold the output grid fine while leaving every
% tolerance at its declared value: the error controller still decides which
% trial steps pass, it simply may not stretch the accepted spacing past this
% ceiling.  This is a NUMERICAL_METHOD knob, not a model change.
if ~isempty(ip.Results.DtMax)
    opt.dt_max = ip.Results.DtMax;
    opt.dt_max_armed = min(ip.Results.DtMax,opt.dt_max);
end

% NO ibr_factory_override: the devices are the production dual-mode model, so
% the Thevenin DC source and its chopper stay in the loop.

fprintf('running locked_gfl on the DELIVERED Thevenin DC closure ...\n');
t0 = tic;
r = stability.run_hybrid_case(scenario,opt);
elapsed = toc(t0);

outdir = fullfile('output','diagnostics','ieee14_locked_gfl_diag');
if ~isfolder(outdir), mkdir(outdir); end
S = struct( ...
    'result',r, ...
    'elapsed',elapsed, ...
    'classification','ASSUMED_DIAGNOSTIC', ...
    'note',['locked_gfl arm with allow_no_vf_island=true and the ' ...
            'angle_gauge_bus=1 pin, on the DELIVERED Thevenin DC closure ' ...
            '(no ibr_factory_override).  The production ' ...
            'noVoltageFormingSource refusal is unchanged.'], ...
    'option',['events.automatic_gfm_switching=false; ' ...
              'opt.automatic_support_supervision=true; ' ...
              'opt.allow_no_vf_island=true; opt.angle_gauge_bus=1; ' ...
              'opt.angle_gauge_after=20.25; NO ibr_factory_override; ' ...
              'otherwise identical to run_ieee14_gfm_lock_comparison ' ...
              'base_request(dt=0.05,t_end=250)'], ...
    'generated',char(datetime('now')));
cache = fullfile(outdir,ip.Results.OutFile);
save(cache,'-struct','S','-v7.3');
fprintf(['DONE elapsed=%.1f s  converged=%d  t_end=%.6f  failure=%s\n' ...
         'wrote %s\n'],elapsed,logical(r.converged),r.t(end), ...
         char(string(r.failure_id)),cache);
out = struct('result',r,'cache',cache,'elapsed',elapsed);
end
