function report = verify_ne39_tamu_migration()
%VERIFY_NE39_TAMU_MIGRATION ตรวจสองเคสโดยไม่ bypass physical-capability gate.
pf_init_paths();
root = fileparts(fileparts(fileparts(mfilename('fullpath'))));
rows = struct([]);
for ns = [5 1]
    if ns == 5
        s = cases.scenario_ne39_5sg_5ibr();
    else
        s = cases.scenario_ne39_1sg_9ibr();
    end
    c = s.case_data;
    pf = pfsolver.powerflow_newton_raphson(c,struct('verbose',false, ...
        'plot_results',false,'tolerance',1e-10,'enforce_q_limits',true));
    [devices,~] = stability.build_mixed_resource_devices(c,s.resources,s.scenario_opt);
    eq = stability.mixed_equilibrium_solve(c,struct('devices',devices),struct('verbose',false));
    % วิเคราะห์ linearized equations เป็น diagnostic เท่านั้น: eq.converged
    % ยัง false เพราะไม่ทราบ physical active capability ห้ามใช้อนุมัติ switching.
    m = stability.composite_sssa_model(eq.devices,eq.x0,eq.y0,c, ...
        struct('full_kcl',true,'u_eq',eq.u_eq,'event_context',eq.equilibrium_context, ...
        'active_state_indices',eq.active_state_indices,'fd_eps',3e-6, ...
        'reference_device_index',eq.reference.device_index));
    scr = stability.ibr_scr_metrics(c,s.resources,struct(), ...
        struct('scr_source_model','source_aware','bus_voltages',pf.bus_voltage));
    r = struct('scenario_id',s.scenario_id,'source_variant',c.source_variant.id, ...
        'source_sha256',c.source_detail.transcription_sha256, ...
        'sg_buses',c.sg_buses,'ibr_buses',c.ibr_buses, ...
        'pf_converged',pf.converged,'pf_max_mismatch',pf.max_mismatch, ...
        'slack_P_MW',pf.P_generation(31)*100,'slack_Q_MVAr',pf.Q_generation(31)*100, ...
        'load_MW',sum(pf.P_load)*100,'losses_MW',sum(pf.P_generation-pf.P_load)*100, ...
        'ibr_schedule',c.ibr_scheduled,'ibr_ratings_MVA',c.ibr_ratings_MVA, ...
        'state_count',sum([devices.nx]),'equilibrium_residual',eq.residual_norm, ...
        'physical_kcl_residual',eq.physical_kcl_norm, ...
        'physical_capability_certified',eq.converged, ...
        'capability_status',c.dispatch_contract.feasibility_status, ...
        'equilibrium_failure_reason',eq.failure_reason, ...
        'sssa_diagnostic_only',true,'sssa_physical_max_real',max(real(m.physical_eigenvalues)), ...
        'sssa_physical_dimension',numel(m.physical_eigenvalues), ...
        'scr_method',scr.method,'scr',scr_json_rows(scr.per_resource), ...
        'ts_run',false,'switching_certified',false);
    rows = [rows;r]; %#ok<AGROW>
end
report = struct('source','New England IEEE 39-Bus System, Texas A&M distribution', ...
    'migration_scope','source and mixed-case profiles', ...
    'dynamics_model','declared classical reduction of source GENROU; not full GENROU', ...
    'cases',rows);
out = fullfile(root,'output','diagnostics','ne39_tamu');
if ~exist(out,'dir'), mkdir(out); end
file = fullfile(out,'migration_verification.json');
fid = fopen(file,'w');
if fid<0, error('ne39Tamu:reportWrite','ไม่สามารถเขียน verification report'); end
cleanup = onCleanup(@()fclose(fid));
fwrite(fid,jsonencode(report,PrettyPrint=true),'char');
for k = 1:numel(rows)
    r = rows(k);
    fprintf('%s: PF=%d, mismatch=%.3g, KCL=%.3g, states=%d, physical capability=%d, maxRe=%.6g\n', ...
        r.scenario_id,r.pf_converged,r.pf_max_mismatch,r.physical_kcl_residual, ...
        r.state_count,r.physical_capability_certified,r.sssa_physical_max_real);
end
end

function rows = scr_json_rows(per_resource)
rows = struct([]);
for k = 1:numel(per_resource)
    p = per_resource(k);
    if ~p.is_gfl, continue; end
    rows = [rows;struct('resource_id',p.resource_id,'bus',p.bus_id, ...
        'SCR',p.SCR,'Ssc_MVA',p.Ssc_MVA,'rating_MVA',p.rating_MVA, ...
        'Zth_real',real(p.Zth),'Zth_imag',imag(p.Zth), ...
        'reason',p.reason)]; %#ok<AGROW>
end
end
