function case_data = case_kundur_smib_pss()
%CASE_KUNDUR_SMIB_PSS Kundur Example 12.6 - SMIB with AVR and PSS.
%   Single-machine infinite-bus system including field-circuit dynamics, a
%   thyristor exciter with AVR, and a power system stabilizer (6 states:
%   delta_omega_r, delta_delta, delta_psi_fd, delta_v1, delta_v2, delta_vs).
%
%   Same machine and operating point as Example 12.3, so the K-constants
%   match Example 12.3 (with K5, K6 for this terminal-voltage condition).
%
%   Reference: P. Kundur, "Power System Stability and Control",
%   Chapter 12, Section 12.5, Example 12.6, printed pages 776-778.

case_data = struct();
case_data.system_name = 'Kundur SMIB - AVR + PSS (Example 12.6)';
case_data.model = 'D';
case_data.reference = struct( ...
    'source', 'Kundur, Power System Stability and Control, Sec 12.5, Example 12.6', ...
    'pdf_file', 'prabha_kundur_power_system_stability_an.pdf', ...
    'printed_pages', '776-778');

case_data.base_values = struct( ...
    'S_base_MVA', 2220, ...
    'V_base_kV', 24, ...
    'frequency_Hz', 60);

case_data.machine = struct('H', 3.5, 'KD', 0.0);

% K-constants (Example 12.6 = Example 12.3 machine + this voltage condition)
case_data.k_constants = struct( ...
    'K1', 0.7643, ...
    'K2', 0.8649, ...
    'K3', 0.3230, ...
    'K4', 1.4187, ...
    'K5', -0.1463, ...
    'K6', 0.4168, ...
    'T3', 2.365);

case_data.exciter = struct( ...
    'KA', 200, ...
    'TR', 0.02);

% Power system stabilizer parameters (Example 12.6)
case_data.pss = struct( ...
    'KSTAB', 9.5, ...
    'Tw', 1.4, ...
    'T1', 0.154, ...
    'T2', 0.033);

% Golden reference: eigenvalues from Example 12.6
case_data.reference_solution = struct( ...
    'avr_only_unstable_Hz', 1.15, ...
    'avr_only_eig_osc', [0.504 + 7.23i; 0.504 - 7.23i], ...
    'avr_only_eig_real', [-20.202; -31.230], ...
    'pss_eig_real1', -39.097, ...
    'pss_eig_swing', [-1.005 + 6.607i; -1.005 - 6.607i], ...
    'pss_swing_Hz', 1.05, ...
    'pss_swing_zeta', 0.15, ...
    'pss_eig_real2', -0.739, ...
    'pss_eig_exciter', [-19.797 + 12.822i; -19.797 - 12.822i], ...
    'pss_exciter_Hz', 2.04, ...
    'pss_exciter_zeta', 0.84);
end
