function case_data = case_saadat_opf_example_7_6()
%CASE_SAADAT_OPF_EXAMPLE_7_6 Saadat economic dispatch with MW limits.
%   Three-generator, one-bus equivalent dispatch with generator limits.
%   Reference: Hadi Saadat, Chapter 7, Example 7.6, printed pages 277-279.

case_data = cases.case_saadat_opf_example_7_4();
case_data.system_name = 'Saadat Example 7.6 - Economic Dispatch With Limits';
case_data.reference = struct( ...
    'source', 'Power System Analysis, Hadi Saadat, Chapter 7, Example 7.6', ...
    'pdf_file', 'power system analysis - hadi saadat_320503100.pdf', ...
    'printed_pages', '277-279');
case_data.opf_data.P_demand_MW = 975;
case_data.opf_data.P_min_MW = [200; 150; 100];
case_data.opf_data.P_max_MW = [450; 350; 225];
case_data.reference_solution = struct( ...
    'lambda', 9.4, ...
    'P_generation_MW', [450; 325; 200], ...
    'total_cost', 8236.25);
end
