function case_data = case_kundur_smib_avr()
%CASE_KUNDUR_SMIB_AVR Kundur Section 12.4 - SMIB with exciter / AVR.
%   Single-machine infinite-bus system including field-circuit dynamics and
%   a thyristor exciter with automatic voltage regulator (4 states:
%   delta_omega_r, delta_delta, delta_psi_fd, delta_v1).
%
%   The K-constants are supplied directly (as listed by Kundur for this
%   example) since the worked example specifies them rather than the raw
%   d-q machine parameters.
%
%   Reference: P. Kundur, "Power System Stability and Control",
%   Chapter 12, Section 12.4, Example 12.4 / Table 12.1, printed pages 762-765.

case_data = struct();
case_data.system_name = 'Kundur SMIB - Exciter/AVR (Sec 12.4)';
case_data.model = 'C';
case_data.reference = struct( ...
    'source', 'Kundur, Power System Stability and Control, Sec 12.4, Table 12.1', ...
    'pdf_file', 'prabha_kundur_power_system_stability_an.pdf', ...
    'printed_pages', '762-765');

case_data.base_values = struct( ...
    'S_base_MVA', 2220, ...
    'V_base_kV', 24, ...
    'frequency_Hz', 60);

case_data.machine = struct('H', 3.0, 'KD', 0.0);

% K-constants and exciter parameters (Kundur Sec 12.4 example)
case_data.k_constants = struct( ...
    'K1', 1.591, ...
    'K2', 1.5, ...
    'K3', 0.333, ...
    'K4', 1.8, ...
    'K5', -0.12, ...
    'K6', 0.3, ...
    'T3', 1.91);          % = K3 * Td0'

case_data.exciter = struct( ...
    'KA', 200, ...        % AVR gain (swept: 0, 15, 25, 200)
    'TR', 0.02);          % terminal-voltage transducer time constant

% Golden reference: Table 12.1 torque components evaluated at the rotor
% oscillation frequency omega_n = sqrt(K1*w0/(2H)) ~ 10 rad/s.
case_data.reference_solution = struct( ...
    'omega_eval', 10.0, ...
    'KA_list',        [0,       15,      25,      200], ...
    'Ks_dpsifd_list', [-0.0025, -0.0093, -0.0098, 0.2804], ...
    'Ks_total_list',  [1.5885,  1.5817,  1.5812,  1.8714], ...
    'KD_dpsifd_list', [1.772,   0.024,  -1.166,  -12.272]);
end
