function case_data = case_saadat_opf_example_7_4()
%CASE_SAADAT_OPF_EXAMPLE_7_4 Saadat economic dispatch benchmark.
%   Three-generator, one-bus equivalent dispatch with no losses and no
%   generator MW limits. Reference: Hadi Saadat, Chapter 7, Example 7.4,
%   printed pages 271-274.

case_data = struct();
case_data.system_name = 'Saadat Example 7.4 - Economic Dispatch No Limits';
case_data.reference = struct( ...
    'source', 'Power System Analysis, Hadi Saadat, Chapter 7, Example 7.4', ...
    'pdf_file', 'power system analysis - hadi saadat_320503100.pdf', ...
    'printed_pages', '271-274');
case_data.opf_data = struct( ...
    'equivalent_bus_count', 1, ...
    'generator_ids', [1; 2; 3], ...
    'P_demand_MW', 800, ...
    'cost', [ ...
        500 5.3 0.004; ...
        400 5.5 0.006; ...
        200 5.8 0.009], ...
    'P_min_MW', [-Inf; -Inf; -Inf], ...
    'P_max_MW', [Inf; Inf; Inf]);
case_data.reference_solution = struct( ...
    'lambda', 8.5, ...
    'P_generation_MW', [400; 250; 150], ...
    'total_cost', 6682.5);
end
