function ref = kundur_e123_reference()
%KUNDUR_E123_REFERENCE Exact scanned Table E12.3 targets (comparison only).
% Source: Kundur, PSSC, p. 815, Table E12.3.  This function contains no
% model equations and must never be called from a DAE/RHS/Jacobian builder.

ref = struct();
ref.source = 'Kundur PSSC p. 815, Table E12.3';
ref.tolerance_component_percent = 0.5;
ref.zero_absolute_note = 'Near-zero roots use absolute distance, never relative percent error.';
ref.families = [ ...
    family('zero_jordan',[-.76e-3+1i*.22e-2;-.76e-3-1i*.22e-2], ...
        'Delta omega of G1--G4'); ...
    family('common_real',-.096,'Delta omega of G1--G4'); ...
    family('interarea',[-.111+1i*3.43;-.111-1i*3.43], ...
        'Delta omega of G1--G4'); ...
    family('common_real_2',-.117,'Delta omega of G1--G4'); ...
    family('field',[-.265;-.276],'Delta psi_fd'); ...
    family('local_area_1',[-.492+1i*6.82;-.492-1i*6.82], ...
        'Delta omega delta of G1 G2'); ...
    family('local_area_2',[-.506+1i*7.02;-.506-1i*7.02], ...
        'Delta omega delta of G3 G4'); ...
    family('q_amortisseur',[-3.428;-4.139;-5.287;-5.303], ...
        'd and q axis amortisseur flux linkages'); ...
    family('d_amortisseur_real',[-31.03;-32.45;-34.07;-35.53], ...
        'd and q axis amortisseur flux linkages'); ...
    family('d_amortisseur_pair_1',[-37.89+1i*.142;-37.89-1i*.142], ...
        'd and q axis amortisseur flux linkages'); ...
    family('d_amortisseur_pair_2',[-38.01+1i*.038;-38.01-1i*.038], ...
        'd and q axis amortisseur flux linkages')];
ref.eigenvalues = vertcat(ref.families.eigenvalues);
end

function s = family(name,eigenvalues,dominant_states)
s = struct('name',name,'eigenvalues',eigenvalues(:), ...
    'dominant_states',dominant_states);
end
