function [strat, events, hybrid_state, x0, y0, opt, t_span] = ...
    synthetic_guard_fixture(variant)
%SYNTHETIC_GUARD_FIXTURE  Phase 2 synthetic fixture for generic event tests.
%   [strat, events, hybrid_state, x0, y0, opt, t_span] = ...
%       synthetic_guard_fixture(variant) builds a minimal SHO (simple harmonic
%       oscillator) strategy + a generic events struct for Phase 2 synthetic
%       tests. ALL guard thresholds/dwell values carry assumed_diagnostic=true
%       and are EXCLUDED from production claims (PROJECT_DERIVED test
%       scaffolding).
%
%   Variants:
%     'scheduled_only'         3 scheduled transitions at t=0.5,1.0,1.5
%     'scheduled_plus_guard'    2 scheduled + 1 guard (|x(1)|>0.8, dwell=0.05)
%     'coincident_ordered'      2 transitions at t=1.0, orders 1 and 2
%     'ambiguous_order'         2 transitions at t=1.0, SAME order (FAIL)
%     'guard_timeout'           guard with timeout=0.01, dwell=0.5 (FAIL)
%     'guard_disarm'            guard threshold met 0.03s then drops (RESET)
%     'priority_deterministic'  2 guards fire simultaneously, distinct priority
%     'priority_ambiguous'      2 guards fire with SAME priority (FAIL)
%
%   Source: project Phase 2 design. Synthetic test scaffolding only.
%   SHO: dx1/dt = x2; dx2/dt = -x1 (standard ODE theory). No algebraic
%   states (needs_algebraic_solve=false). Topologies are identity (SHO has
%   no network Y); topology_id maps to a 1x1 identity matrix for the
%   schema contract.

arguments
    variant (1,1) string
end

% SHO strategy (no Y, no algebraic solve, no provider).
strat = struct();
strat.model = 'sho_synthetic';
strat.dae_f = @(x,~,~) [x(2); -x(1)];
strat.dae_g = [];
strat.jac_y = @(~,~,~) [];
strat.needs_jyy = false;
strat.needs_algebraic_solve = false;
strat.electrical_power = @(~,~,~) 0;
strat.state_split = struct('ng',1,'ns',2,'delta_idx',1,'omega_idx',2);
strat.reconstruct = @(x,~,~) struct('delta',x(1),'omega',x(2),'Pe',0,'Vbus',zeros(0,1));
strat.provider = [];

x0 = [1.0; 0.0];   % SHO: amplitude 1, zero initial speed.
y0 = zeros(0,1);   % No algebraic states.
t_span = [0, 2.0];

% Identity topology (SHO has no network; topology_id must exist in map).
Id = 1;
events = struct();
events.topologies = struct('pre', Id, 'fault', Id, 'post', Id, 'A', Id, 'B', Id);
events.guards = struct([]);

% Hybrid state: two synthetic devices IBR2, IBR3 in 'gfl'.
devices = struct('device_id', {'IBR2','IBR3'}, 'initial_mode', {'gfl','gfl'});
hybrid_state = stability.ts_hybrid_state_init(devices);

switch variant
case 'scheduled_only'
    events.transitions = make_transitions({ ...
        struct('event_id','ev1','time',0.5,'order',1,'topology_id','pre'), ...
        struct('event_id','ev2','time',1.0,'order',1,'topology_id','fault'), ...
        struct('event_id','ev3','time',1.5,'order',1,'topology_id','post')});
case 'scheduled_plus_guard'
    events.transitions = make_transitions({ ...
        struct('event_id','ev1','time',0.5,'order',1,'topology_id','pre'), ...
        struct('event_id','ev2','time',1.0,'order',1,'topology_id','fault')});
    events.guards = make_guards({struct( ...
        'guard_id','g1','source_id','IBR2','priority',1, ...
        'threshold',struct('value',0.8,'source','synthetic_amp','assumed_diagnostic',true), ...
        'dwell',struct('value',0.05,'source','synthetic_dwell','assumed_diagnostic',true), ...
        'timeout',5.0,'localization','device', ...
        'measurement_fn',@(t,x,~,~) abs(x(1)), ...
        'transition',struct('event_id','guard_g1','topology_id','post', ...
            'hybrid_commit',struct('device_modes',struct('IBR2','GFM'))))});
case 'coincident_ordered'
    events.transitions = make_transitions({ ...
        struct('event_id','evA','time',1.0,'order',1,'topology_id','A'), ...
        struct('event_id','evB','time',1.0,'order',2,'topology_id','B')});
case 'ambiguous_order'
    events.transitions = make_transitions({ ...
        struct('event_id','evA','time',1.0,'order',1,'topology_id','A'), ...
        struct('event_id','evB','time',1.0,'order',1,'topology_id','B')});
case 'guard_timeout'
    events.transitions = make_transitions({struct('event_id','ev1','time',0.5,'order',1,'topology_id','pre')});
    events.guards = make_guards({struct( ...
        'guard_id','g1','source_id','IBR2','priority',1, ...
        'threshold',struct('value',0.8,'source','synthetic_amp','assumed_diagnostic',true), ...
        'dwell',struct('value',0.5,'source','synthetic_long_dwell','assumed_diagnostic',true), ...
        'timeout',0.01,'localization','device', ...
        'measurement_fn',@(t,x,~,~) abs(x(1)), ...
        'transition',struct('event_id','guard_g1','topology_id','post', ...
            'hybrid_commit',struct('device_modes',struct('IBR2','GFM'))))});
case 'guard_disarm'
    % Threshold met for 0.03s (dwell=0.05), then drops below -> RESET.
    events.transitions = make_transitions({struct('event_id','ev1','time',0.5,'order',1,'topology_id','pre')});
    events.guards = make_guards({struct( ...
        'guard_id','g1','source_id','IBR2','priority',1, ...
        'threshold',struct('value',0.8,'source','synthetic_amp','assumed_diagnostic',true), ...
        'dwell',struct('value',0.05,'source','synthetic_dwell','assumed_diagnostic',true), ...
        'timeout',5.0,'localization','device', ...
        'measurement_fn',@(t,x,~,~) abs(x(1)), ...
        'transition',struct('event_id','guard_g1','topology_id','post', ...
            'hybrid_commit',struct('device_modes',struct('IBR2','GFM'))))});
case 'priority_deterministic'
    events.transitions = make_transitions({struct('event_id','ev1','time',0.5,'order',1,'topology_id','pre')});
    events.guards = make_guards({struct( ...
        'guard_id','g1','source_id','IBR2','priority',1, ...
        'threshold',struct('value',0.8,'source','synthetic_amp','assumed_diagnostic',true), ...
        'dwell',struct('value',0.01,'source','synthetic_dwell','assumed_diagnostic',true), ...
        'timeout',5.0,'localization','device', ...
        'measurement_fn',@(t,x,~,~) abs(x(1)), ...
        'transition',struct('event_id','guard_g1','topology_id','post', ...
            'hybrid_commit',struct('device_modes',struct('IBR2','GFM')))); struct( ...
        'guard_id','g2','source_id','IBR3','priority',2, ...
        'threshold',struct('value',0.8,'source','synthetic_amp','assumed_diagnostic',true), ...
        'dwell',struct('value',0.01,'source','synthetic_dwell','assumed_diagnostic',true), ...
        'timeout',5.0,'localization','device', ...
        'measurement_fn',@(t,x,~,~) abs(x(1)), ...
        'transition',struct('event_id','guard_g2','topology_id','post', ...
            'hybrid_commit',struct('device_modes',struct('IBR3','GFM'))))});
case 'priority_ambiguous'
    events.transitions = make_transitions({struct('event_id','ev1','time',0.5,'order',1,'topology_id','pre')});
    events.guards = make_guards({struct( ...
        'guard_id','g1','source_id','IBR2','priority',1, ...
        'threshold',struct('value',0.8,'source','synthetic_amp','assumed_diagnostic',true), ...
        'dwell',struct('value',0.01,'source','synthetic_dwell','assumed_diagnostic',true), ...
        'timeout',5.0,'localization','device', ...
        'measurement_fn',@(t,x,~,~) abs(x(1)), ...
        'transition',struct('event_id','guard_g1','topology_id','post', ...
            'hybrid_commit',struct('device_modes',struct('IBR2','GFM')))); struct( ...
        'guard_id','g2','source_id','IBR3','priority',1, ...
        'threshold',struct('value',0.8,'source','synthetic_amp','assumed_diagnostic',true), ...
        'dwell',struct('value',0.01,'source','synthetic_dwell','assumed_diagnostic',true), ...
        'timeout',5.0,'localization','device', ...
        'measurement_fn',@(t,x,~,~) abs(x(1)), ...
        'transition',struct('event_id','guard_g2','topology_id','post', ...
            'hybrid_commit',struct('device_modes',struct('IBR3','GFM'))))});
otherwise
    error('synthetic_guard_fixture:unknownVariant', 'Unknown variant "%s".', variant);
end

opt = struct('dt',0.01, 't_end', t_span(2), 'corrector_mode','fixed', ...
    'max_corrector_iter',1, 'corrector_abs_tol',1e-12, 'corrector_rel_tol',1e-10, ...
    'algebraic_tolerance',1e-12, 'verbose',false);
end

% =========================================================================
function tr = make_transitions(specs)
tr = repmat(struct('event_id',"",'time',NaN,'order',0,'topology_id',"", ...
    'atomic_updates',struct(),'hybrid_commit',struct(),'source','synthetic_fixture'), ...
    0, 1);
for k = 1:numel(specs)
    s = specs{k};
    if ~isfield(s,'hybrid_commit') || isempty(s.hybrid_commit)
        hc = struct();
    else
        hc = s.hybrid_commit;
    end
    tr(end+1, 1) = struct('event_id',string(s.event_id),'time',s.time, ...
        'order',s.order,'topology_id',string(s.topology_id), ...
        'atomic_updates',struct(),'hybrid_commit',hc, ...
        'source','synthetic_fixture'); %#ok<AGROW>
end
end

% =========================================================================
function g = make_guards(specs)
g = repmat(struct('guard_id',"",'source_id',"",'priority',0, ...
    'threshold',struct(),'dwell',struct(),'timeout',NaN,'localization',"", ...
    'measurement_fn',[],'transition',struct()), 0, 1);
for k = 1:numel(specs)
    s = specs{k};
    g(end+1, 1) = s; %#ok<AGROW>
end
end
