function result = compare(method_a, results_a, method_b, results_b)
%COMPARE  Compare two solver results and get AI recommendation.
%
%   result = ai_client.compare(method_a, results_a, method_b, results_b)
%
%   method_a, method_b — solver name strings
%   results_a, results_b — structs (see ai_client.analyze for field definitions)
%
%   Returns struct with:
%       .analysis         — free-form comparison text
%       .winner           — recommended method (or 'tie')
%       .comparison_table — side-by-side metrics

data = struct(...
    'method_a', method_a, ...
    'results_a', pack_results(results_a), ...
    'method_b', method_b, ...
    'results_b', pack_results(results_b) ...
);

[resp, ok] = ai_client.call_api('/compare', data);
if ok
    result = resp;
else
    result = resp;
end
end

function s = pack_results(r)
    s = struct(...
        'method',       char_or(r, 'method', ''), ...
        'system_name',  char_or(r, 'system_name', 'Unknown'), ...
        'num_buses',    num_or(r, 'num_buses', 0), ...
        'num_lines',    num_or(r, 'num_lines', 0), ...
        'iterations',   num_or(r, 'iterations', 0), ...
        'converged',    logical_or(r, 'converged', true), ...
        'P_loss_total', num_or(r, 'P_loss_total', 0), ...
        'Q_loss_total', num_or(r, 'Q_loss_total', 0), ...
        'bus_data',     value_or(r, 'bus_data', []), ...
        'mismatch_history', value_or(r, 'mismatch_history', []) ...
    );
end
