function result = report(req)
%REPORT  Generate a comprehensive power system analysis report.
%
%   result = ai_client.report(req)
%
%   req — struct with fields:
%       .system_name            (char)
%       .methods                (struct array, each like ai_client.analyze input)
%       .cpf_result             (struct or [], optional)
%       .opf_result             (struct or [], optional)
%       .include_recommendations (logical, default true)
%       .language               ('en' or 'th', default 'en')
%
%   Returns struct with:
%       .report — full markdown report text

% Pack methods as cell array of structs
method_structs = {};
if isfield(req, 'methods') && ~isempty(req.methods)
    methods = req.methods;
    if iscell(methods)
        methods = [methods{:}];
    end
    for i = 1:numel(methods)
        m = methods(i);
        method_structs{end+1} = struct(...
            'method',       char_or(m, 'method', ''), ...
            'system_name',  char_or(m, 'system_name', 'Unknown'), ...
            'num_buses',    num_or(m, 'num_buses', 0), ...
            'num_lines',    num_or(m, 'num_lines', 0), ...
            'iterations',   num_or(m, 'iterations', 0), ...
            'converged',    logical_or(m, 'converged', true), ...
            'P_loss_total', num_or(m, 'P_loss_total', 0), ...
            'Q_loss_total', num_or(m, 'Q_loss_total', 0), ...
            'bus_data',     value_or(m, 'bus_data', []), ...
            'mismatch_history', value_or(m, 'mismatch_history', []) ...
        );
    end
end

% Pack CPF if provided
cpf_data = struct([]);
if isfield(req, 'cpf_result') && ~isempty(req.cpf_result)
    c = req.cpf_result;
    cpf_data = struct(...
        'method',        char_or(c, 'method', 'CPF'), ...
        'system_name',   char_or(c, 'system_name', 'Unknown'), ...
        'num_buses',     num_or(c, 'num_buses', 0), ...
        'target_bus',    num_or(c, 'target_bus', 0), ...
        'num_points',    num_or(c, 'num_points', 0), ...
        'nose_detected', logical_or(c, 'nose_detected', false), ...
        'lambda_min',    num_or(c, 'lambda_min', 0), ...
        'lambda_max',    num_or(c, 'lambda_max', 0), ...
        'voltage_min',   num_or(c, 'voltage_min', 0), ...
        'voltage_max',   num_or(c, 'voltage_max', 0), ...
        'stop_reason',   char_or(c, 'stop_reason', '') ...
    );
end

% Pack OPF if provided
opf_data = struct([]);
if isfield(req, 'opf_result') && ~isempty(req.opf_result)
    o = req.opf_result;
    gen_arr = {};
    if isfield(o, 'generators') && ~isempty(o.generators)
        for i = 1:numel(o.generators)
            g = o.generators(i);
            lim = value_or(g, 'limit', 'free');
            if isnumeric(lim)
                lim = num2str(lim);
            end
            gen_arr{end+1} = struct(...
                'id',    char_or(g, 'id', num2str(i)), ...
                'P_MW',  num_or(g, 'P_MW', 0), ...
                'cost',  num_or(g, 'cost', 0), ...
                'limit', lim ...
            );
        end
    end
    opf_data = struct(...
        'system_name',      char_or(o, 'system_name', 'Unknown'), ...
        'demand_MW',        num_or(o, 'demand_MW', 0), ...
        'total_cost',       num_or(o, 'total_cost', 0), ...
        'lambda_cost',      num_or(o, 'lambda_cost', 0), ...
        'balance_residual', num_or(o, 'balance_residual', 0), ...
        'generators',       {gen_arr} ...
    );
end

data = struct(...
    'system_name',            char_or(req, 'system_name', 'Unknown'), ...
    'methods',                {method_structs}, ...
    'cpf_result',             cpf_data, ...
    'opf_result',             opf_data, ...
    'include_recommendations', logical_or(req, 'include_recommendations', true), ...
    'language',               char_or(req, 'language', 'en') ...
);

[resp, ok] = ai_client.call_api('/report', data);
if ok
    result = resp;
else
    result = resp;
end
end
