function meta = device_contract_metadata(dev)
%DEVICE_CONTRACT_METADATA  Strict IBR-owned Section H state/input metadata registry.
%
%   meta = ibr.device_contract_metadata(dev) returns the frozen Section H
%   metadata (state_symbol, equation_source, equation_classification, unit,
%   frame, state_branch) for a supported IBR device struct. The function is
%   a PURE lookup keyed by the immutable (device_type, nx, nu, state_names,
%   input_names) identity of the device. It does NOT call dev.f,
%   current_injection, equilibrium_initialize, any equilibrium solver, SSSA,
%   or any external routine. It invents no equations, no parameters, and no
%   page citations.
%
%   This registry exists because the shared builder
%   (+stability/build_mixed_resource_devices.m) vertically concatenates
%   heterogeneous SG and IBR device structs, so IBR-only top-level fields
%   cannot be attached to the device struct without breaking mixed SG/IBR
%   construction. The registry is the IBR-owned, single-source-of-truth
%   metadata layer consumed by ibr.state_inventory_snapshot.
%
%   Supported contracts (exact-match dispatch):
%     'gfm_regfm_b1'             device_type='ibr_gfm',          nx=13, nu=2
%     'gfl_wecc_regca_reeca'     device_type='ibr_gfl_wecc_regca_reeca', nx=7,  nu=2
%     'gfl_rms10'                device_type='ibr_gfl_rms10',     nx=10, nu=2
%     'dual_mode_ibr'            device_type='ibr_dual_mode',    nx=20, nu=3
%     'dual_mode_ibr_rms10'      device_type='ibr_dual_mode_rms10', nx=23, nu=3
%
%   Unknown device_type, wrong nx/nu, reordered/duplicate state_names, or
%   mismatched input_names fail closed with stable ibr:device_contract_metadata:*
%   identifiers. No WECC state is ever labelled as a PLL state.
%
%   Citation policy: GFM equation_source strings carry page+equation/figure
%   citations frozen in docs/project/IEEE14_IBR_GFM_PHASE6_PROVENANCE.md
%   (Eq.1-13, Fig.2-6 -> NREL/TP-5D00-90260 pp.1-5). GFL equation_source
%   strings carry block-level citations frozen in
%   docs/project/IEEE14_IBR_GFL_WECC_PROVENANCE.md (WECC Second Generation
%   Generic Models 2014, Sec.3.2/3.3). GFL page-level citations are NOT
%   invented: the WECC PDFs are external URLs (not cached in docs/text/);
%   the frozen provenance doc establishes block-level source only. Each GFL
%   row carries citation_status='BLOCK_LEVEL_NOT_PAGE_CITED' so consumers
%   never mistake block-level provenance for page-level.
%
%   See: docs/project/IEEE14_IBR_DYNAMIC_EQUATION_CONTRACT.md (Section H).
%   Status: SOURCE_IMPLEMENTED_PENDING_INTEGRATION_GATES. Read-only metadata
%   layer; no production numerical equation, state order, or ABI change.

arguments
    dev struct
end

if ~isfield(dev,'device_type') || ~isfield(dev,'nx') || ~isfield(dev,'nu') ...
        || ~isfield(dev,'state_names') || ~isfield(dev,'input_names')
    error('ibr:device_contract_metadata:badDevice', ...
        'dev must have device_type, nx, nu, state_names, input_names.');
end

state_names = cellstr(string(dev.state_names));
input_names = cellstr(string(dev.input_names));
device_type = char(dev.device_type);

if strcmp(device_type,'ibr_gfm') && dev.nx == 13 && dev.nu == 2 && ...
        isequal(state_names, gfm_state_names()) && ...
        isequal(input_names, {'P_ref','V_ref'})
    meta = gfm_metadata();
elseif strcmp(device_type,'ibr_gfl_wecc_regca_reeca') && dev.nx == 7 && ...
        dev.nu == 2 && isequal(state_names, gfl_state_names()) && ...
        isequal(input_names, {'P_ref','Q_ref'})
    meta = gfl_metadata();
elseif strcmp(device_type,'ibr_gfl_rms10') && dev.nx == 10 && ...
        dev.nu == 2 && isequal(state_names, gfl_rms10_state_names()) && ...
        isequal(input_names, {'P_ref','Q_ref'})
    meta = gfl_rms10_metadata();
elseif strcmp(device_type,'ibr_dual_mode') && dev.nx == 20 && dev.nu == 3 && ...
        isequal(state_names, dual_state_names()) && ...
        isequal(input_names, {'P_ref','Q_ref','V_ref'})
    meta = dual_metadata();
elseif strcmp(device_type,'ibr_dual_mode_rms10') && dev.nx == 23 && dev.nu == 3 && ...
        isequal(state_names, dual_rms10_state_names()) && ...
        isequal(input_names, {'P_ref','Q_ref','V_ref'})
    meta = dual_rms10_metadata();
else
    error('ibr:device_contract_metadata:unknownContract', ...
        ['Unknown IBR device contract: device_type=%s nx=%d nu=%d. ' ...
         'Registry supports ibr_gfm(13,2), ibr_gfl_wecc_regca_reeca(7,2), ' ...
         'ibr_gfl_rms10(10,2), ibr_dual_mode(20,3), ibr_dual_mode_rms10(23,3) ' ...
         'with exact state/input order.'], ...
        device_type, dev.nx, dev.nu);
end
end

% =========================================================================
function meta = gfm_metadata()
%GFM_METADATA  REGFM_B1 G2 13-state contract (NREL/TP-5D00-90260).
rows = repmat(state_row_template(), 0);

src = 'docs/project/IEEE14_IBR_GFM_PHASE6_PROVENANCE.md';
defs = { ...
    'omega_m','omega_m','NREL/TP-5D00-90260 p.1 Fig.2 (VSM swing)','SOURCE_TRANSFORMED','pu','VSG DQ','gfm','PAGE_LEVEL',src; ...
    'delta_IT','delta_IT','NREL/TP-5D00-90260 pp.1,4 Figs.2,6 (PLL-relative VSM angle)','SOURCE_TRANSFORMED','rad','VSG DQ','gfm','PAGE_LEVEL',src; ...
    'x_washout','x_washout','NREL/TP-5D00-90260 p.1 Fig.2 D2*s/(s+omegaD)','SOURCE_DEFINED','pu','VSG DQ','gfm','PAGE_LEVEL',src; ...
    'x_Eint','x_Eint','NREL/TP-5D00-90260 p.2 Fig.3 (voltage PI integral)','SOURCE_TRANSFORMED','pu*s','VSG DQ','gfm','PAGE_LEVEL',src; ...
    'delta_PLL','delta_PLL','NREL/TP-5D00-90260 p.2 Fig.4 (PLL angle)','SOURCE_DEFINED','rad','PLL DQ','gfm','PAGE_LEVEL',src; ...
    'x_PLL_int','x_PLL_int','NREL/TP-5D00-90260 p.2 Fig.4 (PLL PI integrator)','SOURCE_DEFINED','pu*s','PLL DQ','gfm','PAGE_LEVEL',src; ...
    'Pinv_f','P_inv,f','NREL/TP-5D00-90260 p.1 Eq.1 (filtered active power)','SOURCE_DEFINED','pu inverter base','device-local','gfm','PAGE_LEVEL',src; ...
    'Idinv_f','I_d,inv,f','NREL/TP-5D00-90260 p.1 Eq.2 (filtered active current)','SOURCE_DEFINED','pu inverter-base current','PLL DQ','gfm','PAGE_LEVEL',src; ...
    'Qinv_f','Q_inv,f','NREL/TP-5D00-90260 p.2 Eq.3 (filtered reactive power)','SOURCE_DEFINED','pu inverter base','device-local','gfm','PAGE_LEVEL',src; ...
    'Vinv_f','V_inv,f','NREL/TP-5D00-90260 p.2 Eq.4 (filtered voltage magnitude)','SOURCE_DEFINED','pu voltage','device-local','gfm','PAGE_LEVEL',src; ...
    'Iqinv_f','I_q,inv,f','NREL/TP-5D00-90260 p.2 Eq.5 (filtered reactive current)','SOURCE_DEFINED','pu inverter-base current','PLL DQ','gfm','PAGE_LEVEL',src; ...
    'delta_ITmax','delta_IT,max','NREL/TP-5D00-90260 p.4 Fig.6, Eq.12 (positive angle bound)','SOURCE_TRANSFORMED','rad','VSG DQ','gfm','PAGE_LEVEL',src; ...
    'delta_ITmin','delta_IT,min','NREL/TP-5D00-90260 p.4 Fig.6, Eq.12 (negative angle bound)','SOURCE_TRANSFORMED','rad','VSG DQ','gfm','PAGE_LEVEL',src};
for k = 1:size(defs,1)
    rows(k) = make_state_row(k, defs(k,:));
end
meta = struct( ...
    'contract_id','gfm_regfm_b1', ...
    'contract_version','phase_g2_r3', ...
    'scope','IBR_ONLY', ...
    'source_model','REGFM_B1 G2 VSG (NREL/TP-5D00-90260)', ...
    'state_metadata',rows, ...
    'input_metadata',gfm_input_metadata());
end

function meta = gfl_metadata()
%GFL_METADATA  WECC REGC_A/REEC_A 7-state contract.
rows = repmat(state_row_template(), 0);

src = 'docs/project/IEEE14_IBR_GFL_WECC_PROVENANCE.md';
doc = 'WECC Second Generation Generic WTG Models (2014) Sec.3.2/3.3';
defs = { ...
    'Vt_f','V_t,f',sprintf('%s — REEC_A terminal-voltage filter',doc),'SOURCE_TRANSFORMED','pu voltage','device-local','gfl','BLOCK_LEVEL_NOT_PAGE_CITED',src; ...
    'P_f','P_f',sprintf('%s — REEC_A electrical-power filter',doc),'SOURCE_TRANSFORMED','pu inverter base','device-local','gfl','BLOCK_LEVEL_NOT_PAGE_CITED',src; ...
    'Iq_cmd_f','I_q,cmd,f',sprintf('%s — REEC_A reactive-current command lag',doc),'SOURCE_TRANSFORMED','pu inverter-base current','device-local','gfl','BLOCK_LEVEL_NOT_PAGE_CITED',src; ...
    'Pord','P_ord',sprintf('%s — REEC_A active-power order/rate limiter',doc),'SOURCE_TRANSFORMED','pu inverter-base power','device-local','gfl','BLOCK_LEVEL_NOT_PAGE_CITED',src; ...
    'Vlvpl_f','V_LVPL,f',sprintf('%s — REGC_A LVPL voltage filter',doc),'SOURCE_TRANSFORMED','pu voltage','device-local','gfl','BLOCK_LEVEL_NOT_PAGE_CITED',src; ...
    'Ip_reg','I_p,reg',sprintf('%s — REGC_A active-current lag/runback limiter',doc),'SOURCE_TRANSFORMED','pu inverter-base current','device-local','gfl','BLOCK_LEVEL_NOT_PAGE_CITED',src; ...
    'Iq_reg','I_q,reg',sprintf('%s — REGC_A reactive-current lag/directional limiter',doc),'SOURCE_TRANSFORMED','pu inverter-base current','device-local','gfl','BLOCK_LEVEL_NOT_PAGE_CITED',src};
for k = 1:size(defs,1)
    rows(k) = make_state_row(k, defs(k,:));
end
meta = struct( ...
    'contract_id','gfl_wecc_regca_reeca', ...
    'contract_version','d15_frozen', ...
    'scope','IBR_ONLY', ...
    'source_model','WECC REGC_A/REEC_A positive-sequence GFL (D15 canonical)', ...
    'state_metadata',rows, ...
    'input_metadata',gfl_input_metadata());
end

function meta = dual_metadata()
%DUAL_METADATA  Composed 20-state dual-mode contract (GFM 1:13 + GFL 14:20).
gfm = gfm_metadata();
gfl = gfl_metadata();
rows = repmat(state_row_template(), 0);

% GFM branch 1:13 — prefix names, keep source symbol/citation unchanged.
for k = 1:numel(gfm.state_metadata)
    r = gfm.state_metadata(k);
    rows(end+1) = struct( ...
        'local_state_index',k, ...
        'state_name',sprintf('gfm_%s',r.state_name), ...
        'state_symbol',r.state_symbol, ...
        'equation_source',r.equation_source, ...
        'equation_classification',r.equation_classification, ...
        'unit',r.unit, ...
        'frame',r.frame, ...
        'state_branch','gfm', ...
        'citation_status',r.citation_status, ...
        'source_doc',r.source_doc); %#ok<AGROW>
end
% GFL branch 14:20.
for k = 1:numel(gfl.state_metadata)
    r = gfl.state_metadata(k);
    rows(end+1) = struct( ...
        'local_state_index',13+k, ...
        'state_name',sprintf('gfl_%s',r.state_name), ...
        'state_symbol',r.state_symbol, ...
        'equation_source',r.equation_source, ...
        'equation_classification',r.equation_classification, ...
        'unit',r.unit, ...
        'frame',r.frame, ...
        'state_branch','gfl', ...
        'citation_status',r.citation_status, ...
        'source_doc',r.source_doc); %#ok<AGROW>
end
meta = struct( ...
    'contract_id','dual_mode_ibr', ...
    'contract_version','d16_frozen_layout', ...
    'scope','IBR_ONLY', ...
    'source_model','REGFM_B1 G2 (1:13) + WECC REGC_A/REEC_A (14:20) dual-mode superset', ...
    'state_metadata',rows, ...
    'input_metadata',dual_input_metadata());
end

function meta = gfl_rms10_metadata()
%GFL_RMS10_METADATA  10-state GFL-RMS10 contract (PROJECT_DERIVED composite).
rows = repmat(state_row_template(), 0);

src = 'docs/project/IEEE14_IBR_GFL_RMS10_PROVENANCE.md';
doc = 'Yazdani 2010 + Teodorescu 2011 + Bacha 2014 (PROJECT_DERIVED composite)';
defs = { ...
    'delta_PLL','delta_PLL',sprintf('%s — SRF-PLL angle (Yazdani eq 8.22-8.25, Teodorescu eq 4.31)','A'),'SOURCE_DEFINED','rad','PLL DQ','gfl','PAGE_LEVEL',src; ...
    'xi_PLL','xi_PLL',sprintf('%s — SRF-PLL PI integrator (Yazdani Fig 8.4, Teodorescu eq 4.30)','A'),'SOURCE_DEFINED','pu*s','PLL DQ','gfl','PAGE_LEVEL',src; ...
    'P_f','P_f',sprintf('%s — filtered active power (REGFM_B1 Eq.1 pattern)','A'),'PROJECT_DERIVED','pu inverter','device-local','gfl','PAGE_LEVEL',src; ...
    'Q_f','Q_f',sprintf('%s — filtered reactive power (REGFM_B1 Eq.3 pattern)','A'),'PROJECT_DERIVED','pu inverter','device-local','gfl','PAGE_LEVEL',src; ...
    'xi_P','xi_P',sprintf('%s — active-power PI integrator (user §5.4)','A'),'PROJECT_DERIVED','pu*s','PLL DQ','gfl','PAGE_LEVEL',src; ...
    'xi_Q','xi_Q',sprintf('%s — reactive-power PI integrator (user §5.4)','A'),'PROJECT_DERIVED','pu*s','PLL DQ','gfl','PAGE_LEVEL',src; ...
    'xi_id','xi_id',sprintf('%s — d-axis current PI integrator (Yazdani eq 8.53)','A'),'SOURCE_DEFINED','pu*s','PLL DQ','gfl','PAGE_LEVEL',src; ...
    'xi_iq','xi_iq',sprintf('%s — q-axis current PI integrator (Yazdani eq 8.53)','A'),'SOURCE_DEFINED','pu*s','PLL DQ','gfl','PAGE_LEVEL',src; ...
    'i_d','i_d',sprintf('%s — d-axis current plant (Yazdani eq 8.45)','A'),'SOURCE_DEFINED','pu inverter-base current','PLL DQ','gfl','PAGE_LEVEL',src; ...
    'i_q','i_q',sprintf('%s — q-axis current plant (Yazdani eq 8.46)','A'),'SOURCE_DEFINED','pu inverter-base current','PLL DQ','gfl','PAGE_LEVEL',src};
for k = 1:size(defs,1)
    rows(k) = make_state_row(k, defs(k,:));
end
meta = struct( ...
    'contract_id','gfl_rms10', ...
    'contract_version','rms10_frozen', ...
    'scope','IBR_ONLY', ...
    'source_model','GFL-RMS10 PROJECT_DERIVED composite (Yazdani+Teodorescu+Bacha)', ...
    'state_metadata',rows, ...
    'input_metadata',gfl_rms10_input_metadata());
end

function meta = dual_rms10_metadata()
%DUAL_RMS10_METADATA  Composed 23-state dual-mode contract (GFM 1:13 + GFL-RMS10 14:23).
gfm = gfm_metadata();
gfl = gfl_rms10_metadata();
rows = repmat(state_row_template(), 0);

% GFM branch 1:13 — prefix names, keep source symbol/citation unchanged.
for k = 1:numel(gfm.state_metadata)
    r = gfm.state_metadata(k);
    rows(end+1) = struct( ...
        'local_state_index',k, ...
        'state_name',sprintf('gfm_%s',r.state_name), ...
        'state_symbol',r.state_symbol, ...
        'equation_source',r.equation_source, ...
        'equation_classification',r.equation_classification, ...
        'unit',r.unit, ...
        'frame',r.frame, ...
        'state_branch','gfm', ...
        'citation_status',r.citation_status, ...
        'source_doc',r.source_doc); %#ok<AGROW>
end
% GFL-RMS10 branch 14:23.
for k = 1:numel(gfl.state_metadata)
    r = gfl.state_metadata(k);
    rows(end+1) = struct( ...
        'local_state_index',13+k, ...
        'state_name',sprintf('gfl_%s',r.state_name), ...
        'state_symbol',r.state_symbol, ...
        'equation_source',r.equation_source, ...
        'equation_classification',r.equation_classification, ...
        'unit',r.unit, ...
        'frame',r.frame, ...
        'state_branch','gfl', ...
        'citation_status',r.citation_status, ...
        'source_doc',r.source_doc); %#ok<AGROW>
end
meta = struct( ...
    'contract_id','dual_mode_ibr_rms10', ...
    'contract_version','d18_rms10_frozen_layout', ...
    'scope','IBR_ONLY', ...
    'source_model','REGFM_B1 G2 (1:13) + GFL-RMS10 (14:23) dual-mode superset', ...
    'state_metadata',rows, ...
    'input_metadata',dual_input_metadata());
end

% --- Input metadata -------------------------------------------------------
function rows = gfm_input_metadata()
src = 'docs/project/IEEE14_IBR_GFM_PHASE6_PROVENANCE.md';
rows = make_input_rows({ ...
    'P_ref','pu system base','REGFM_B1/project ABI P_ref mapping (system->inverter base via kappa)','SOURCE_TRANSFORMED','NOT_ESTABLISHED',src; ...
    'V_ref','pu voltage','REGFM_B1/project ABI V_ref mapping','SOURCE_TRANSFORMED','NOT_ESTABLISHED',src});
end

function rows = gfl_input_metadata()
src = 'docs/project/IEEE14_IBR_GFL_WECC_PROVENANCE.md';
rows = make_input_rows({ ...
    'P_ref','pu system base','WECC constant-P REEC_A option + system/inverter-base boundary mapping','SOURCE_TRANSFORMED','NOT_ESTABLISHED',src; ...
    'Q_ref','pu system base','WECC constant-Q REEC_A option + system/inverter-base boundary mapping','SOURCE_TRANSFORMED','NOT_ESTABLISHED',src});
end

function rows = gfl_rms10_input_metadata()
src = 'docs/project/IEEE14_IBR_GFL_RMS10_PROVENANCE.md';
rows = make_input_rows({ ...
    'P_ref','pu system base','GFL-RMS10 active-power reference + system/inverter-base boundary mapping (kappa=Sbase/Mbase)','SOURCE_TRANSFORMED','NOT_ESTABLISHED',src; ...
    'Q_ref','pu system base','GFL-RMS10 reactive-power reference + system/inverter-base boundary mapping','SOURCE_TRANSFORMED','NOT_ESTABLISHED',src});
end

function rows = dual_input_metadata()
src = 'docs/project/IEEE14_IBR_FROZEN_CONTRACT.md';
rows = make_input_rows({ ...
    'P_ref','pu system base','branch-shared external input (GFM and GFL both consume P_ref)','SOURCE_TRANSFORMED','NOT_ESTABLISHED',src; ...
    'Q_ref','pu system base','GFL branch input','SOURCE_TRANSFORMED','NOT_ESTABLISHED',src; ...
    'V_ref','pu voltage','GFM branch input','SOURCE_TRANSFORMED','NOT_ESTABLISHED',src});
end

% --- Builders ------------------------------------------------------------
function r = state_row_template()
r = struct('local_state_index',0,'state_name','', ...
    'state_symbol','','equation_source','', ...
    'equation_classification','','unit','','frame','', ...
    'state_branch','','citation_status','','source_doc','');
end

function r = make_state_row(idx, d)
% d is a 1x9 (or Nx9) cell row; pick its 9 entries.
v = cell(1,9);
for j = 1:9
    v{j} = d{1,j};
end
r = struct( ...
    'local_state_index',idx, ...
    'state_name',v{1}, ...
    'state_symbol',v{2}, ...
    'equation_source',v{3}, ...
    'equation_classification',v{4}, ...
    'unit',v{5}, ...
    'frame',v{6}, ...
    'state_branch',v{7}, ...
    'citation_status',v{8}, ...
    'source_doc',v{9});
end

function rows = make_input_rows(defs)
rows = repmat(input_row_template(), 0);
for k = 1:size(defs,1)
    d = defs(k,:);
    rows(k) = struct( ...
        'local_input_index',k, ...
        'input_name',d{1,1}, ...
        'unit',d{1,2}, ...
        'source',d{1,3}, ...
        'equation_classification',d{1,4}, ...
        'event_mutability',d{1,5}, ...
        'source_doc',d{1,6});
end
end

function r = input_row_template()
r = struct('local_input_index',0,'input_name','','unit','', ...
    'source','','equation_classification','','event_mutability','', ...
    'source_doc','');
end

% --- Frozen name lists (single source of truth for dispatch) -------------
function s = gfm_state_names()
s = {'omega_m','delta_IT','x_washout','x_Eint','delta_PLL','x_PLL_int', ...
     'Pinv_f','Idinv_f','Qinv_f','Vinv_f','Iqinv_f','delta_ITmax','delta_ITmin'};
end

function s = gfl_state_names()
s = {'Vt_f','P_f','Iq_cmd_f','Pord','Vlvpl_f','Ip_reg','Iq_reg'};
end

function s = gfl_rms10_state_names()
s = {'delta_PLL','xi_PLL','P_f','Q_f','xi_P','xi_Q','xi_id','xi_iq','i_d','i_q'};
end

function s = dual_state_names()
s = [strcat('gfm_',gfm_state_names()), strcat('gfl_',gfl_state_names())];
end

function s = dual_rms10_state_names()
s = [strcat('gfm_',gfm_state_names()), strcat('gfl_',gfl_rms10_state_names())];
end
