function meta = device_contract_metadata(dev)
%DEVICE_CONTRACT_METADATA  Strict IBR-owned Section H state/input metadata registry.
%
%   meta = ibr.device_contract_metadata(dev) returns the frozen Section H
%   metadata (state_symbol, equation_source, equation_classification, unit,
%   frame, state_branch) for a supported IBR device struct. The function is
%   a PURE lookup keyed by the immutable (device_type, nx, nu, state_names,
%   input_names) identity of the device. It does NOT call dev.f,
%   current_injection, equilibrium_initialize, any equilibrium solver, SSSA,
%   or any external routine. It invents no equations, no parameters, and no
%   page citations.
%
%   This registry exists because the shared builder
%   (+stability/build_mixed_resource_devices.m) vertically concatenates
%   heterogeneous SG and IBR device structs, so IBR-only top-level fields
%   cannot be attached to the device struct without breaking mixed SG/IBR
%   construction. The registry is the IBR-owned, single-source-of-truth
%   metadata layer consumed by ibr.state_inventory_snapshot.
%
%   Supported contracts (exact-match dispatch):
%     'gfl_rms10'                device_type='ibr_gfl_rms10',     nx=10, nu=2
%     'eecon49_dual'             device_type='ibr_eecon49_dual', nx=16, nu=3
%     'eecon49_dual_source_state' device_type='ibr_eecon49_dual', nx=17, nu=3
%       (the 16 controller/plant states plus the DC-source current I_dc
%        appended at plant index 17 when source_state is enabled; the DC state
%        is carried explicitly, never dropped and never merged into 16)
%
%   Retired 2026-10-08 with their model families: 'gfm_regfm_b1'
%   (device_type='ibr_gfm', 13-state, REGFM_B1) and 'gfl_wecc_regca_reeca'
%   (device_type='ibr_gfl_wecc_regca_reeca', 7-state, WECC). No surviving
%   device publishes those device_types, so the registry no longer carries them.
%
%   Unknown device_type, wrong nx/nu, reordered/duplicate state_names, or
%   mismatched input_names fail closed with stable ibr:device_contract_metadata:*
%   identifiers. No WECC state is ever labelled as a PLL state.
%
%   Citation policy: every remaining contract's equation_source strings carry
%   page+equation citations frozen in docs/project/ (EECON49 GFL/GFM source
%   contract, EECON49-P4 Eqs.(6)-(29); GFL-RMS10 PROJECT_DERIVED composite).
%   No page citation is invented where the source is only established at block
%   level.
%
%   See: docs/project/IEEE14_IBR_DYNAMIC_EQUATION_CONTRACT.md (Section H).
%   Status: SOURCE_IMPLEMENTED_PENDING_INTEGRATION_GATES. Read-only metadata
%   layer; no production numerical equation, state order, or ABI change.

arguments
    dev struct
end

if ~isfield(dev,'device_type') || ~isfield(dev,'nx') || ~isfield(dev,'nu') ...
        || ~isfield(dev,'state_names') || ~isfield(dev,'input_names')
    error('ibr:device_contract_metadata:badDevice', ...
        'dev must have device_type, nx, nu, state_names, input_names.');
end

state_names = cellstr(string(dev.state_names));
input_names = cellstr(string(dev.input_names));
device_type = char(dev.device_type);

if strcmp(device_type,'ibr_gfl_rms10') && dev.nx == 10 && ...
        dev.nu == 2 && isequal(state_names, gfl_rms10_state_names()) && ...
        isequal(input_names, {'P_ref','Q_ref'})
    meta = gfl_rms10_metadata();
elseif strcmp(device_type,'ibr_eecon49_dual') && dev.nx == 16 && dev.nu == 3 && ...
        isequal(state_names, eecon49_dual_state_names()) && ...
        isequal(input_names, {'P_ref','Q_ref','E_ref'})
    meta = eecon49_dual_metadata();
elseif strcmp(device_type,'ibr_eecon49_dual') && dev.nx == 17 && dev.nu == 3 && ...
        isequal(state_names, eecon49_dual_source_state_names()) && ...
        isequal(input_names, {'P_ref','Q_ref','E_ref'})
    meta = eecon49_dual_source_state_metadata();
else
    error('ibr:device_contract_metadata:unknownContract', ...
        ['Unknown IBR device contract: device_type=%s nx=%d nu=%d. ' ...
         'Registry supports ibr_gfl_rms10(10,2), ibr_eecon49_dual(16,3), ' ...
         'ibr_eecon49_dual(17,3) with exact state/input order.'], ...
        device_type, dev.nx, dev.nu);
end
end

function meta = eecon49_dual_metadata()
%EECON49_DUAL_METADATA  Shared-plant 16-state GFL/GFM contract.
src='docs/project/EECON49_GFL_GFM_SOURCE_CONTRACT.md';
doc='EECON49-P4 Eqs.(6)-(29) and Fig.2';
defs={ ...
    'i_d','I_d',sprintf('%s: common AC-filter d-axis current, Eq.(6)',doc),'SOURCE_TRANSFORMED','pu device-base current','active controller DQ','common','PAGE_LEVEL',src; ...
    'i_q','I_q',sprintf('%s: common AC-filter q-axis current, Eq.(7)',doc),'SOURCE_TRANSFORMED','pu device-base current','active controller DQ','common','PAGE_LEVEL',src; ...
    'V_dc','V_dc',sprintf('%s: Eq.(8) energy balance + project DC current-source regulator',doc),'PROJECT_DERIVED','pu dc voltage','dc link','common','PAGE_LEVEL_PLUS_PROJECT_DERIVATION',src; ...
    'gfl_delta_PLL','theta_PLL',sprintf('%s: GFL PLL angle, Eqs.(9)-(10)',doc),'SOURCE_TRANSFORMED','rad','PLL DQ','gfl','PAGE_LEVEL',src; ...
    'gfl_xi_PLL','xi_PLL',sprintf('%s: GFL PLL integrator, Eq.(11)',doc),'SOURCE_MAPPED','pu*s','PLL DQ','gfl','PAGE_LEVEL',src; ...
    'gfl_xi_P','xi_P',sprintf('%s: GFL active-power PI integrator, Eq.(12)',doc),'SOURCE_MAPPED','pu*s','PLL DQ','gfl','PAGE_LEVEL',src; ...
    'gfl_xi_Q','xi_Q',sprintf('%s: GFL reactive-power PI integrator, Eq.(13)',doc),'SOURCE_TRANSFORMED','pu*s','PLL DQ','gfl','PAGE_LEVEL',src; ...
    'gfl_xi_Id','xi_Id',sprintf('%s: GFL d-current PI integrator, Eq.(16)',doc),'SOURCE_MAPPED','pu*s','PLL DQ','gfl','PAGE_LEVEL',src; ...
    'gfl_xi_Iq','xi_Iq',sprintf('%s: GFL q-current PI integrator, Eq.(17)',doc),'SOURCE_MAPPED','pu*s','PLL DQ','gfl','PAGE_LEVEL',src; ...
    'gfm_delta_VSG','theta',sprintf('%s: GFM VSG angle, Eq.(22)',doc),'SOURCE_TRANSFORMED','rad','VSG DQ','gfm','PAGE_LEVEL',src; ...
    'gfm_omega_VSG','omega',sprintf('%s: GFM virtual swing, Eq.(23)',doc),'SOURCE_TRANSFORMED','pu frequency','VSG DQ','gfm','PAGE_LEVEL',src; ...
    'gfm_E','E',sprintf('%s: GFM voltage-forming amplitude, Eq.(24)',doc),'SOURCE_MAPPED','pu voltage','VSG DQ','gfm','PAGE_LEVEL',src; ...
    'gfm_xi_Vd','xi_Vd',sprintf('%s: GFM d-voltage PI integrator, Eq.(26)',doc),'SOURCE_MAPPED','pu*s','VSG DQ','gfm','PAGE_LEVEL',src; ...
    'gfm_xi_Vq','xi_Vq',sprintf('%s: GFM q-voltage PI integrator, Eq.(27)',doc),'SOURCE_MAPPED','pu*s','VSG DQ','gfm','PAGE_LEVEL',src; ...
    'gfm_xi_Id','xi_Id',sprintf('%s: shared inner d-current PI structure, Eq.(16)/Fig.2',doc),'SOURCE_MAPPED','pu*s','VSG DQ','gfm','PAGE_LEVEL',src; ...
    'gfm_xi_Iq','xi_Iq',sprintf('%s: shared inner q-current PI structure, Eq.(17)/Fig.2',doc),'SOURCE_MAPPED','pu*s','VSG DQ','gfm','PAGE_LEVEL',src};
rows=repmat(state_row_template(),0);
for k=1:size(defs,1), rows(k)=make_state_row(k,defs(k,:)); end
meta=struct('contract_id','eecon49_dual','contract_version','production_r1', ...
    'scope','IBR_ONLY','source_model','shared-plant GFL(PLL)/GFM(VSG without PLL)', ...
    'state_metadata',rows,'input_metadata',eecon49_dual_input_metadata());
end

% =========================================================================
function meta = eecon49_dual_source_state_metadata()
%EECON49_DUAL_SOURCE_STATE_METADATA  Shared-plant 17-state GFL/GFM contract.
%   Same device_type and controller blocks as the 16-state contract, with the
%   DC-source current appended as an explicit plant coordinate at index 17.
%   The model (ibr.eecon49_dual_mode_model) appends this state after the two
%   controller blocks when source_state is enabled, so the inventory MUST carry
%   it explicitly rather than drop it; it is never merged into a 16-state key.
meta = eecon49_dual_metadata();
src = 'docs/project/EECON49_GFL_GFM_SOURCE_CONTRACT.md';
doc = 'EECON49-P4 Eqs.(6)-(29) and Fig.2';
meta.state_metadata(17) = make_state_row(17, { ...
    'I_dc','I_dc',sprintf(['%s: project DC current-source regulator plant ' ...
    'coordinate (appended at superset index 17 when source_state is enabled)'],doc), ...
    'PROJECT_DERIVED','pu dc current','dc link','common', ...
    'PAGE_LEVEL_PLUS_PROJECT_DERIVATION',src});
meta.contract_id = 'eecon49_dual_source_state';
meta.contract_version = 'production_r1_source_state';
end

% =========================================================================
function meta = gfl_rms10_metadata()
%GFL_RMS10_METADATA  10-state GFL-RMS10 contract (PROJECT_DERIVED composite).
rows = repmat(state_row_template(), 0);

src = 'docs/project/IEEE14_IBR_GFL_RMS10_PROVENANCE.md';
doc = 'Yazdani 2010 + Teodorescu 2011 + Bacha 2014 (PROJECT_DERIVED composite)';
defs = { ...
    'delta_PLL','delta_PLL',sprintf('%s — SRF-PLL angle (Yazdani eq 8.22-8.25, Teodorescu eq 4.31)','A'),'SOURCE_DEFINED','rad','PLL DQ','gfl','PAGE_LEVEL',src; ...
    'xi_PLL','xi_PLL',sprintf('%s — SRF-PLL PI integrator (Yazdani Fig 8.4, Teodorescu eq 4.30)','A'),'SOURCE_DEFINED','pu*s','PLL DQ','gfl','PAGE_LEVEL',src; ...
    'P_f','P_f',sprintf('%s — filtered active power (REGFM_B1 Eq.1 pattern)','A'),'PROJECT_DERIVED','pu inverter','device-local','gfl','PAGE_LEVEL',src; ...
    'Q_f','Q_f',sprintf('%s — filtered reactive power (REGFM_B1 Eq.3 pattern)','A'),'PROJECT_DERIVED','pu inverter','device-local','gfl','PAGE_LEVEL',src; ...
    'xi_P','xi_P',sprintf('%s — active-power PI integrator (user §5.4)','A'),'PROJECT_DERIVED','pu*s','PLL DQ','gfl','PAGE_LEVEL',src; ...
    'xi_Q','xi_Q',sprintf('%s — reactive-power PI integrator (user §5.4)','A'),'PROJECT_DERIVED','pu*s','PLL DQ','gfl','PAGE_LEVEL',src; ...
    'xi_id','xi_id',sprintf('%s — d-axis current PI integrator (Yazdani eq 8.53)','A'),'SOURCE_DEFINED','pu*s','PLL DQ','gfl','PAGE_LEVEL',src; ...
    'xi_iq','xi_iq',sprintf('%s — q-axis current PI integrator (Yazdani eq 8.53)','A'),'SOURCE_DEFINED','pu*s','PLL DQ','gfl','PAGE_LEVEL',src; ...
    'i_d','i_d',sprintf('%s — d-axis current plant (Yazdani eq 8.45)','A'),'SOURCE_DEFINED','pu inverter-base current','PLL DQ','gfl','PAGE_LEVEL',src; ...
    'i_q','i_q',sprintf('%s — q-axis current plant (Yazdani eq 8.46)','A'),'SOURCE_DEFINED','pu inverter-base current','PLL DQ','gfl','PAGE_LEVEL',src};
for k = 1:size(defs,1)
    rows(k) = make_state_row(k, defs(k,:));
end
meta = struct( ...
    'contract_id','gfl_rms10', ...
    'contract_version','rms10_frozen', ...
    'scope','IBR_ONLY', ...
    'source_model','GFL-RMS10 PROJECT_DERIVED composite (Yazdani+Teodorescu+Bacha)', ...
    'state_metadata',rows, ...
    'input_metadata',gfl_rms10_input_metadata());
end

% --- Input metadata -------------------------------------------------------
function rows = gfl_rms10_input_metadata()
src = 'docs/project/IEEE14_IBR_GFL_RMS10_PROVENANCE.md';
rows = make_input_rows({ ...
    'P_ref','pu system base','GFL-RMS10 active-power reference + system/inverter-base boundary mapping (kappa=Sbase/Mbase)','SOURCE_TRANSFORMED','NOT_ESTABLISHED',src; ...
    'Q_ref','pu system base','GFL-RMS10 reactive-power reference + system/inverter-base boundary mapping','SOURCE_TRANSFORMED','NOT_ESTABLISHED',src});
end

function rows = eecon49_dual_input_metadata()
src='docs/project/EECON49_GFL_GFM_SOURCE_CONTRACT.md';
rows=make_input_rows({ ...
    'P_ref','pu system base','active-power reference consumed by both GFL and GFM branches','SOURCE_TRANSFORMED','EVENT_MUTABLE',src; ...
    'Q_ref','pu system base','reactive-power reference consumed by both GFL and GFM branches','SOURCE_TRANSFORMED','EVENT_MUTABLE',src; ...
    'E_ref','pu voltage','external terminal-voltage reference consumed by the GFM amplitude-state equation','SOURCE_MAPPED','NOT_MUTABLE',src});
end

% --- Builders ------------------------------------------------------------
function r = state_row_template()
r = struct('local_state_index',0,'state_name','', ...
    'state_symbol','','equation_source','', ...
    'equation_classification','','unit','','frame','', ...
    'state_branch','','citation_status','','source_doc','');
end

function r = make_state_row(idx, d)
% d is a 1x9 (or Nx9) cell row; pick its 9 entries.
v = cell(1,9);
for j = 1:9
    v{j} = d{1,j};
end
r = struct( ...
    'local_state_index',idx, ...
    'state_name',v{1}, ...
    'state_symbol',v{2}, ...
    'equation_source',v{3}, ...
    'equation_classification',v{4}, ...
    'unit',v{5}, ...
    'frame',v{6}, ...
    'state_branch',v{7}, ...
    'citation_status',v{8}, ...
    'source_doc',v{9});
end

function rows = make_input_rows(defs)
rows = repmat(input_row_template(), 0);
for k = 1:size(defs,1)
    d = defs(k,:);
    rows(k) = struct( ...
        'local_input_index',k, ...
        'input_name',d{1,1}, ...
        'unit',d{1,2}, ...
        'source',d{1,3}, ...
        'equation_classification',d{1,4}, ...
        'event_mutability',d{1,5}, ...
        'source_doc',d{1,6});
end
end

function r = input_row_template()
r = struct('local_input_index',0,'input_name','','unit','', ...
    'source','','equation_classification','','event_mutability','', ...
    'source_doc','');
end

% --- Frozen name lists (single source of truth for dispatch) -------------
function s = gfl_rms10_state_names()
s = {'delta_PLL','xi_PLL','P_f','Q_f','xi_P','xi_Q','xi_id','xi_iq','i_d','i_q'};
end

function s = eecon49_dual_state_names()
s={'i_d','i_q','V_dc', ...
    'gfl_delta_PLL','gfl_xi_PLL','gfl_xi_P','gfl_xi_Q', ...
    'gfl_xi_Id','gfl_xi_Iq', ...
    'gfm_delta_VSG','gfm_omega_VSG','gfm_E','gfm_xi_Vd','gfm_xi_Vq', ...
    'gfm_xi_Id','gfm_xi_Iq'};
end

function s = eecon49_dual_source_state_names()
% The 16 controller/plant names plus the DC-source current appended at index 17.
s = [eecon49_dual_state_names(), {'I_dc'}];
end
