function case_data = case_ibr_smib_gfm_reduced6()
%CASE_IBR_SMIB_GFM_REDUCED6  6-state reduced grid-forming VSG inverter (EECON49-P4)
%   single-infinite-bus verification case.
%
%   Source-frozen diagnostic fixture (schema smib_verification/1.0). The 6-state
%   reduced GFM VSG model (ibr.gfm_reduced6_model; blocks IBR+VSG+GFM, 2 states
%   each, NO PLL) is connected to an ideal algebraic infinite bus through Z_line
%   and evaluated by the project-owned SMIB equilibrium, SSSA, and TDS oracles.
case_data = struct();
case_data.schema_version = 'smib_verification/1.0';
case_data.system_name = 'GFM 6-state (reduced VSG, EECON49) - Single Infinite Bus Verification';
case_data.source = ['Source-frozen diagnostic fixture used by ', ...
    'ibr.smib_sssa_oracle and ibr.smib_tds_oracle; device ', ...
    'ibr.gfm_reduced6_model (EECON49-P4 GFM/VSG formulation)'];
case_data.base_values = struct('S_base_MVA',100.0,'frequency_Hz',60.0);
case_data.smib_verification = struct( ...
    'kind','gfm_reduced6', 'device_type','ibr_gfm_reduced6', ...
    'device_id','GFM_REDUCED6', ...
    'V_terminal',1.0+0i, 'P_terminal_pu',0.40, ...
    'Q_terminal_pu',0.10, 'Z_line_pu',0.02+0.20i, ...
    'classification','ASSUMED_DIAGNOSTIC_SOURCE_FROZEN_FIXTURE', ...
    'events_supported',false);
end
