function case_data = case_kundur_smib_detailed()
%CASE_KUNDUR_SMIB_DETAILED Kundur Example 12.3 - SMIB with field circuit dynamics.
%   Single-machine infinite-bus system with a detailed synchronous machine
%   model including field-circuit dynamics (3 states: delta_omega_r,
%   delta_delta, delta_psi_fd). K-constants are derived from the machine
%   d-q parameters (not supplied directly).
%
%   Reference: P. Kundur, "Power System Stability and Control",
%   Chapter 12, Section 12.3.2 / 12.6, Example 12.3, printed pages 753-757.

case_data = struct();
case_data.system_name = 'Kundur SMIB - Field Circuit Dynamics (Example 12.3)';
case_data.model = 'B';
case_data.reference = struct( ...
    'source', 'Kundur, Power System Stability and Control, Sec 12.3.2, Example 12.3', ...
    'pdf_file', 'prabha_kundur_power_system_stability_an.pdf', ...
    'printed_pages', '753-757');

case_data.base_values = struct( ...
    'S_base_MVA', 2220, ...
    'V_base_kV', 24, ...
    'frequency_Hz', 60);

% Synchronous machine parameters (per unit, machine base).
% Fundamental (unsaturated) mutual inductances and leakage.
case_data.machine = struct( ...
    'H', 3.5, ...
    'KD', 0.0, ...
    'Ladu', 1.65, ...     % unsaturated d-axis mutual inductance
    'Laqu', 1.60, ...     % unsaturated q-axis mutual inductance
    'Ll', 0.16, ...       % stator leakage inductance
    'Ra', 0.003, ...      % armature resistance
    'Lfd', 0.153, ...     % field leakage inductance
    'Rfd', 0.0006, ...    % field resistance
    'Asat', 0.031, ...    % saturation coefficient A
    'Bsat', 6.93, ...     % saturation coefficient B
    'psi_T1', 0.8);       % saturation threshold flux psi_TI

% External network: transformer + line to infinite bus
case_data.network = struct( ...
    'RE', 0.0, ...
    'XE', 0.65);

% Operating point (terminal conditions)
case_data.operating = struct( ...
    'P', 0.9, ...
    'Q', 0.3, ...
    'Et_mag', 1.0, ...
    'Et_ang_deg', 36.0, ...
    'EB_mag', 0.995, ...
    'EB_ang_deg', 0.0);

% Golden reference solution (Kundur Example 12.3, pages 753-756)
case_data.reference_solution = struct( ...
    'Ksd_total', 0.8491, ...
    'Ksd_incr', 0.434, ...
    'delta_i_deg', 43.13, ...
    'ed0', 0.6836, ...
    'eq0', 0.7298, ...
    'id0', 0.8342, ...
    'iq0', 0.4518, ...
    'delta0_deg', 79.13, ...
    'Efd0', 2.395, ...
    'm1', 1.0437, 'n1', 0.1268, 'm2', 0.8802, 'n2', 0.0018, ...
    'K1', 0.7643, 'K2', 0.8649, 'K3', 0.3230, 'K4', 1.4187, ...
    'T3', 2.365, ...
    'A_matrix', [0, -0.1092, -0.1236; 376.991, 0, 0; 0, -0.1938, -0.4229], ...
    'eig_osc', [-0.110 + 6.41i; -0.110 - 6.41i], ...
    'eig_real', -0.204, ...
    'fn_Hz', 1.02, ...
    'zeta_osc', 0.017);
case_data=cases.standardize_study_case(case_data,'smib');
end
