function case_data = case_ieee5bus()
%CASE_IEEE5BUS Example case packaged for the generic n-bus solver.

case_data = struct();
case_data.system_name = 'IEEE 5-Bus System';
case_data.base_values = struct( ...
    'S_base_MVA', 100, ...
    'V_base_kV', 230, ...
    'frequency_Hz', 60);
case_data.bus_data = cases.case_ieee5bus_bus_data();
case_data.line_data = cases.case_ieee5bus_line_data();
case_data.opf_data.ac = struct( ...
    'generator_ids', [1; 2], ...
    'generator_bus_ids', [1; 2], ...
    'cost', [ ...
        0 12.0 0.020; ...
        0 14.0 0.025], ...
    'P_min_MW', [0; 0], ...
    'P_max_MW', [220; 140], ...
    'Q_min_MVAr', [-120; -100], ...
    'Q_max_MVAr', [160; 100], ...
    'V_min', 0.95, ...
    'V_max', 1.08, ...
    'S_line_max_MVA', 200 * ones(size(case_data.line_data, 1), 1));
case_data = cases.standardize_case(case_data);
end
