function case_data = case_ibr_smib_loaded_gfl_rms10()
%CASE_IBR_SMIB_LOADED_GFL_RMS10  Single GFL-RMS10 to infinite bus, loaded.
%   Returns a smib_loaded_ibr/1.0 case: one GFL-RMS10 converter connected to
%   an ideal algebraic infinite bus through Z_line, with a shunt load at the
%   IBR terminal bus that the SSSA load sweep scales at constant power factor.
%
%   This is a DIAGNOSTIC verification case (schema smib_loaded_ibr/1.0), NOT
%   the source-frozen smib_verification/1.0 ideal fixture. The ideal fixture
%   has no load-demand field and stays bit-identical; this loaded schema is
%   the load-sweep target.
%
%   Source: GFL-RMS10 device (ibr.gfl_rms10_model); Sakimoto/Teodorescu RMS
%   average-value model. f=60 Hz.

case_data = struct();
case_data.schema_version = 'smib_loaded_ibr/1.0';
case_data.system_name = 'GFL-RMS10 Loaded SMIB (single converter to infinite bus)';
case_data.source = ['Diagnostic loaded-IBR fixture for stability.sssa_load_sweep; ', ...
    'GFL-RMS10 device connected to an ideal infinite bus through Z_line ', ...
    'with a shunt load at the IBR terminal bus.'];
case_data.base_values = struct('S_base_MVA',100.0,'frequency_Hz',60.0);
case_data.smib_loaded_ibr = struct( ...
    'kind','gfl_rms10', ...
    'device_type','ibr_gfl_rms10', ...
    'device_id','GFL_RMS10', ...
    'V_infinite_pu',1.0+0i, ...
    'Z_line_pu',0.02+0.20i, ...
    'P_load_base_pu',0.40, ...
    'Q_load_base_pu',0.10, ...
    'P_ibr_base_pu',0.40, ...
    'Q_ibr_base_pu',0.10, ...
    'load_bus_id',1.0, ...
    'classification','ASSUMED_DIAGNOSTIC_SMIB_LOADED_IBR', ...
    'events_supported',false);
end
