function case_data = case_ibr_smib_loaded_gfm_no_pll()
%CASE_IBR_SMIB_LOADED_GFM_NO_PLL  Single GFM-VSG-no-PLL to infinite bus, loaded.
%   Returns a smib_loaded_ibr/1.0 case: one GFM-VSG-no-PLL converter connected
%   to an ideal algebraic infinite bus through Z_line, with a shunt load at
%   the IBR terminal bus that the SSSA load sweep scales at constant power
%   factor.
%
%   This is a DIAGNOSTIC verification case (schema smib_loaded_ibr/1.0), NOT
%   the source-frozen smib_verification/1.0 ideal fixture. The ideal fixture
%   has no load-demand field and stays bit-identical; this loaded schema is
%   the load-sweep target.
%
%   Source: GFM-VSG-no-PLL device (ibr.gfm_vsg_no_pll_model); Sakimoto 2015 /
%   Avila-Martinez 2025 / PNNL-35110. f=50 Hz.

case_data = struct();
case_data.schema_version = 'smib_loaded_ibr/1.0';
case_data.system_name = 'GFM-VSG-no-PLL Loaded SMIB (single converter to infinite bus)';
case_data.source = ['Diagnostic loaded-IBR fixture for stability.sssa_load_sweep; ', ...
    'GFM-VSG-no-PLL device connected to an ideal infinite bus through Z_line ', ...
    'with a shunt load at the IBR terminal bus.'];
case_data.base_values = struct('S_base_MVA',100.0,'frequency_Hz',50.0);
case_data.smib_loaded_ibr = struct( ...
    'kind','gfm_no_pll', ...
    'device_type','ibr_gfm_vsg_no_pll', ...
    'device_id','GFM_NO_PLL', ...
    'V_infinite_pu',1.0+0i, ...
    'Z_line_pu',0.02+0.20i, ...
    'P_load_base_pu',0.40, ...
    'Q_load_base_pu',0.10, ...
    'P_ibr_base_pu',0.40, ...
    'Q_ibr_base_pu',0.10, ...
    'load_bus_id',1.0, ...
    'classification','ASSUMED_DIAGNOSTIC_SMIB_LOADED_IBR', ...
    'events_supported',false);
end
