function case_data = case_ieee14_1sg_4ibr_auto_vsg()
%CASE_IEEE14_1SG_4IBR_AUTO_VSG  IEEE14 1-SG + 4-IBR automatic GFL/VSG mission case.
%   One synchronous generator (SG1 at bus 1) and four switchable inverter-
%   based resources (IBR2 bus 2, IBR3 bus 3, IBR6 bus 6, IBR8 bus 8), each
%   with GFL and GFM (VSG) capabilities. Modes: 'gfl' | 'GFM' | 'tripped'.
%
%   Network/base data: preserved EXACTLY from MATPOWER 6.0 case14 (via
%   case_matpower6_case14). No network/base mutation.
%
%   SG1 dynamic data (item 7 of the decision ledger): CASE_DEFINED from
%   Kodsi (U.Waterloo TR 2003-3) Table A.2 (page 46 / printed p.38), 60 Hz,
%   Gen1 bus 1, 615 MVA. The ONLY SG; buses 2,3,6,8 become IBRs. No dataset
%   mixing (Demetriou 50 Hz rejected; classical defaults H=5/D=0/X'd=0.30
%   rejected as UNSOURCED). Per IEEE 1110-2002 Clause 5.1 (p.18), typical
%   data sized by machine type is authorized for planning; Kodsi provides
%   exactly that for IEEE14 at 60 Hz. Base conversion to the 100 MVA
%   system base is performed INTERNALLY by synchronous_emf6_ssa
%   (scale = Sbase/Sm; H_system = H/scale), so this case file stores values
%   on the MACHINE base (615 MVA) as Kodsi published them.
%
%   Dispatch contract (item 8): pre-fault SG1 Pg=232.4 MW, IBR2 Pg=40 MW,
%   IBR3/6/8 Pg=0; post-trip Pmax-proportional participation (IBR2 69.7,
%   IBR3/6/8 49.8 each) covering the 219 MW deficit. Feasibility verified
%   in Phase 4 (mixed equilibrium solver) BEFORE TS.
%
%   Synchronism thresholds (item 5) + delays (item 6): CASE_DEFINED from
%   verified standard ranges, frozen before results (decision ledger).
%
%   gamma_req (item 9): 0.1 rad/s (a-priori 5% damping at 1 Hz, conservative).
%
%   Source: docs/project/IEEE14_IBR_DECISION_LEDGER.md (frozen contracts).
%   No ASSUMED_DIAGNOSTIC production values.

% --- Preserve the EXACT MATPOWER14 network/base data --------------------
base_case = cases.case_matpower6_case14();
case_data = base_case;
case_data.system_name = 'IEEE14 1-SG + 4-IBR Auto VSG (mission case)';
case_data.source = 'MATPOWER 6.0 case14 network/base + Kodsi TR 2003-3 SG dynamics + mission dispatch contract';
case_data.reference = struct();
case_data.reference.network = 'MATPOWER 6.0 case14.m (IEEE CDF)';
case_data.reference.sg_dynamics = 'Kodsi, U.Waterloo TR 2003-3, Table A.2 p.46 (printed p.38), 60Hz, Gen1 bus1 615MVA';
case_data.reference.sg_model = 'IEEE Std 1110-2002 Model 2.2 (round-rotor 6th-order subtransient)';
case_data.reference.provenance_doc = 'docs/project/IEEE14_IBR_DECISION_LEDGER.md';

% --- SG1 dynamic data (Kodsi Gen1, machine base 615 MVA) -----------------
% Only SG1 (bus 1) retains SG dynamics. Buses 2,3,6,8 become IBRs.
% Values verbatim from Kodsi Table A.2 (verified 2026-07-13).
sg1_unit = struct('gen_id','SG1','bus',1,'H',5.148,'D',2);
case_data.machines = struct( ...
    'model','emf6', ...
    'base',struct('S_MVA',615,'V_kV',0,'f_Hz',60), ...
    'reactances',struct( ...
        'Xl',0.2396, 'Ra',0.0, ...
        'Xd',0.8979, 'Xdp',0.2995, 'Xdpp',0.23, ...
        'Xq',0.646,  'Xqp',0.646,  'Xqpp',0.4), ...
    'time_constants',struct( ...
        'Tpd0',7.4, 'Tppd0',0.03, ...
        'Tpq0',0.0, 'Tppq0',0.033), ...
    'exciter',struct('model','single_time_constant_avr','KA',200,'TA',0.02), ...
    'units',sg1_unit);

% --- Device map (SG1 + 4 IBRs at buses 1,2,3,6,8) ------------------------
case_data.devices = struct( ...
    'SG1',  struct('type','sg',    'bus',1, 'initial_mode','sg',   'initial_online',true), ...
    'IBR2', struct('type','ibr',   'bus',2, 'initial_mode','gfl',  'initial_online',true), ...
    'IBR3', struct('type','ibr',   'bus',3, 'initial_mode','gfl',  'initial_online',true), ...
    'IBR6', struct('type','ibr',   'bus',6, 'initial_mode','gfl',  'initial_online',true), ...
    'IBR8', struct('type','ibr',   'bus',8, 'initial_mode','gfl',  'initial_online',true));

% --- Dispatch contract (item 8): Pmax-proportional post-trip participation
% Pre-fault (SG_ON): SG1 Pg=232.4, IBR2 Pg=40, IBR3/6/8 Pg=0. Load=259 MW.
% Post-trip (SG_OFF): deficit = 259 - 40 = 219 MW, distributed by Pmax:
%   IBR2 (Pmax 140): 219*140/440 = 69.7 MW  -> total 109.7 MW
%   IBR3 (Pmax 100): 219*100/440 = 49.8 MW
%   IBR6 (Pmax 100): 219*100/440 = 49.8 MW
%   IBR8 (Pmax 100): 219*100/440 = 49.8 MW
%   Sum = 259.1 MW ~ load (losses within 400 MW headroom). No load-shed.
pmax = struct('IBR2',140,'IBR3',100,'IBR6',100,'IBR8',100);
deficit = 219.0;
total_pmax = 140 + 100 + 100 + 100;   % 440
participation = struct( ...
    'IBR2', pmax.IBR2/total_pmax, ...
    'IBR3', pmax.IBR3/total_pmax, ...
    'IBR6', pmax.IBR6/total_pmax, ...
    'IBR8', pmax.IBR8/total_pmax);
case_data.dispatch_contract = struct( ...
    'policy','pmax_proportional', ...
    'pre_fault', struct( ...
        'SG1_Pg_MW',232.4, 'IBR2_Pg_MW',40.0, ...
        'IBR3_Pg_MW',0.0, 'IBR6_Pg_MW',0.0, 'IBR8_Pg_MW',0.0), ...
    'post_trip', struct( ...
        'deficit_MW', deficit, ...
        'participation', participation, ...
        'post_trip_Pg_MW', struct( ...
            'IBR2', 40.0 + deficit*participation.IBR2, ...
            'IBR3', deficit*participation.IBR3, ...
            'IBR6', deficit*participation.IBR6, ...
            'IBR8', deficit*participation.IBR8)), ...
    'pmax_MW', pmax, ...
    'load_shed_MW', 0.0, ...
    'aggregate_headroom_MW', total_pmax - 40.0, ...   % 400 MW
    'feasibility_gate', 'Phase 4 mixed equilibrium solver (PF convergence before TS)');

% --- Current limits (REGFM_B1 Table 1 example values, CASE_DEFINED) -----
% ImaxSS <= ImaxF (REGFM_B1 spec). On each IBR's machine base.
case_data.ibr_limits = struct( ...
    'ImaxSS_pu', 1.0, ...   % steady-state (REGFM_B1 Table 1 example)
    'ImaxF_pu',  1.5, ...   % transient (REGFM_B1 Table 1 example)
    'kf',        0.9, ...   % priority factor (REGFM_B1 Table 1 example)
    'PQFlag',    1, ...     % P-priority (REGFM_B1 Table 1 example)
    'source', 'REGFM_B1 NREL 90260 Table 1 (example/default values)');

% --- Synchronism thresholds (item 5): CASE_DEFINED, conservative --------
case_data.synchronism = struct( ...
    'dV_max_pu',       0.05, ...   % 5% magnitude difference
    'df_max_pu',       0.001, ...  % ~0.06 Hz on 60 Hz base (slip)
    'dtheta_max_deg',  10.0, ...   % conservative within 10-20 deg range
    'dwell_s',         0.5, ...    % confirm stable sync
    'timeout_s',       5.0, ...    % after which SG stays disconnected (SYNC_TIMEOUT)
    'breaker_close_time_prediction', 'deferred', ...  % dwell compensates conservatively
    'source', 'verified standard synchronism-check ranges (TR-121 full-text deferred)');

% --- Delays (item 6): CASE_DEFINED, conservative -------------------------
case_data.delays = struct( ...
    'T_detect_s',        0.05, ...
    'T_logic_s',         0.02, ...
    'T_controller_s',    0.05, ...
    'T_up_s',            0.12, ...   % = T_detect + T_logic + T_controller
    'T_sg_min_off_s',    0.5, ...
    'rho',               0.05, ...   % 5% residual envelope
    'T_minimum_hold_s',  1.0, ...
    'T_guard_s',         0.3, ...
    'T_lockout_s',       2.0, ...
    'T_settle_formula', 'ln(1/rho)/(-Omega_current)', ...  % runtime-computed
    'source', 'verified standard protection/control ranges (specific standard deferred)');

% --- Selection margin (item 9): gamma_req, a-priori ---------------------
case_data.selector = struct( ...
    'gamma_req_rad_per_s', 0.1, ...
    'derivation', '0.1 rad/s = conservative of 2*pi*1*0.05 = 0.31 (5% damping at 1 Hz electromechanical mode)', ...
    'frozen_before_candidate_eval', true, ...
    'reference_reduction', 'COI T-matrix (machine-1 angle/speed removed); no manual zero-eigenvalue deletion');

% --- Event chronology (canonical plan §10) -------------------------------
case_data.event_chronology = struct( ...
    'vocabulary', {'fault_on','sg_trip_request','ibr_gfm_enable_request', ...
     'sg_open_and_gfm_mode_commit','fault_off','sg_reconnect_enable', ...
     'sg_sync_pass','sg_reclose_and_mode_commit','ibr_mode_reselection_request', ...
     'ibr_mode_commit'}, ...
    'convention', 'generic events.transitions (Phase 2); legacy fault_on/off via ts_transitions_from_legacy adapter');

% --- Inactive-state rule (item 3, PROJECT_DERIVED) -----------------------
case_data.inactive_state_rule = struct( ...
    'policy','frozen', ...   % inactive branch states held, NOT evolved
    'transfer_map', 'PROJECT_DERIVED from state + current continuity + algebraic-residual minimization (decision ledger item 3)', ...
    'zero_eigenvalue_handling', 'active-state reduction in SSSA selector (no manual deletion)');

end
