function c = network_case_catalog()
%NETWORK_CASE_CATALOG Authoritative list of runnable network case loaders.
%   Every entry is a zero-argument loader returning power_case/1.0 and is
%   exposed by solve_case for PF, SSSA and TS.  Raw-data helpers, catalogs,
%   converters and study_case/1.0 loaders are intentionally not entries.

base=struct('t_end',15,'dt',0.01,'t_fault',1,'t_clear',1.1, ...
    'Zf',1i*0.1,'method','trapezoidal', ...
    'stepper','fixed', ...
    'corrector_mode','adaptive','corrector_iter',[], ...
    'corrector_abs_tol',1e-10,'corrector_rel_tol',1e-8, ...
    'max_corrector_iter',10,'corrector_failure','error', ...
    'verbose',true,'plot_results',true,'model','classical');
c=[net('ieee5','IEEE 5-bus',@cases.case_ieee5bus,3,base); ...
   net('ieee14','IEEE 14-bus',@cases.case_ieee14bus,4,base); ...
   net('ieee300','IEEE 300-bus',@cases.case_ieee300bus,3,base); ...
   net('rts24','IEEE RTS 24-bus (RTS-1996)',@cases.case_ieee_rts24_pgaz,15,base); ...
   net('padiyar_two_area','Padiyar two-area model 1.1 + AVR',@cases.case_padiyar_two_area_4m_avr,3,base); ...
   net('kundur_two_area','Kundur two-area classical',@cases.case_kundur_two_area_classical,8,base); ...
   net('matpower14','MATPOWER case14',@cases.case_matpower6_case14,4,base); ...
   net('case9','WSCC/MATPOWER case9',@cases.case_matpower6_case9,7,base); ...
   net('matpower30','MATPOWER IEEE 30-bus',@cases.case_matpower_ieee30bus,30,base); ...
   net('saadat67','Saadat Example 6.7',@cases.case_saadat_example_6_7,3,base); ...
   net('saadat68','Saadat Example 6.8',@cases.case_saadat_example_6_8,3,base); ...
   net('ieee30','IEEE 30-bus (Saadat)',@cases.case_saadat_ieee30bus,30,base); ...
   net('template','N-bus case template',@cases.case_template_nbus,3,base); ...
   net('kundur','Kundur Example 12.6',@cases.kundur_ex126_book_case,8,base)];

% This case has published sixth-order dynamics; select operational EMF6 by
% default.  Users can still request its classical model explicitly.
pk=find(strcmp({c.id},'padiyar_two_area'),1);
c(pk).sssa_options=struct('model','padiyar_1_1_avr');
c(pk).ts_options.model='padiyar_1_1_avr';
c(pk).ts_options.dt=0.005; c(pk).ts_options.t_end=3;
c(pk).ts_options.Zf=1i*0.5;

kk=find(strcmp({c.id},'kundur'),1);
c(kk).sssa_options=struct('model','emf6');
c(kk).ts_options.model='emf6';
c(kk).ts_options.corrector_mode='fixed';
c(kk).ts_options.corrector_iter=3;
end

function s=net(id,label,loader,fault_bus,base)
t=base; t.fault_bus=fault_bus;
s=struct('id',id,'label',label,'loader',loader, ...
    'pf_options',struct(),'sssa_options',struct('model','classical'), ...
    'ts_options',t);
end
