function catalog = saadat_reference_catalog()
%SAADAT_REFERENCE_CATALOG Inventory of implemented Saadat reference cases.
%   Bus counts are based on the network represented in the case. Economic
%   dispatch examples in Chapter 7 are one-bus equivalent OPF cases.

catalog = struct('id', {}, 'chapter', {}, 'label', {}, 'type', {}, ...
    'bus_count', {}, 'generator_count', {}, 'loader', {}, 'status', {}, 'note', {});

add('ex6_7', '6', 'Example 6.7 - Three-Bus PQ Load Flow', 'PF', 3, 1, 'case_saadat_example_6_7', 'implemented', 'Gauss-Seidel load-flow reference.');
add('ex6_8', '6', 'Example 6.8 - Three-Bus PV Load Flow', 'PF', 3, 2, 'case_saadat_example_6_8', 'implemented', 'PV bus with net generation/load support.');
add('ex6_9', '6', 'Example 6.9 - IEEE 30-Bus Load Flow', 'PF', 30, 6, 'case_saadat_ieee30bus', 'implemented', 'IEEE 30-bus data used by Examples 6.11 and 6.13 too.');
add('ex6_10', '6', 'Example 6.10 - Newton-Raphson Three-Bus', 'PF', 3, 2, 'case_saadat_example_6_8', 'same_data', 'Uses the same 3-bus data as Example 6.8.');
add('ex6_11', '6', 'Example 6.11 - IEEE 30-Bus Newton-Raphson', 'PF', 30, 6, 'case_saadat_ieee30bus', 'same_data', 'Uses the same IEEE 30-bus data as Example 6.9.');
add('ex6_13', '6', 'Example 6.13 - IEEE 30-Bus Fast Decoupled', 'PF', 30, 6, 'case_saadat_ieee30bus', 'same_data', 'Uses the same IEEE 30-bus data as Example 6.9.');
add('ex7_4', '7', 'Example 7.4 - Economic Dispatch No Limits', 'OPF', 1, 3, 'case_saadat_opf_example_7_4', 'implemented', 'One-bus equivalent dispatch, no losses and no generator limits.');
add('ex7_5', '7', 'Example 7.5 - Dispatch Program No Limits', 'OPF', 1, 3, 'case_saadat_opf_example_7_5', 'implemented', 'Same input as Example 7.4, verifies dispatch-program output.');
add('ex7_6', '7', 'Example 7.6 - Economic Dispatch With Limits', 'OPF', 1, 3, 'case_saadat_opf_example_7_6', 'implemented', 'One-bus equivalent dispatch with generator MW limits.');

    function add(id, chapter, label, type, bus_count, generator_count, loader, status, note)
        catalog(end + 1, 1) = struct( ...
            'id', id, ...
            'chapter', chapter, ...
            'label', label, ...
            'type', type, ...
            'bus_count', bus_count, ...
            'generator_count', generator_count, ...
            'loader', loader, ...
            'status', status, ...
            'note', note);
    end
end
