function catalog = sauer_pai_reference_catalog()
%SAUER_PAI_REFERENCE_CATALOG Published dynamic benchmark references.
%
% These are not generated by this codebase. They are golden values copied
% from Sauer and Pai, Power System Dynamics and Stability, Example 8.3,
% Table 8.1, for the numerical 3-machine system of Example 7.1.

catalog = struct();

ex = struct();
ex.name = 'Sauer-Pai Example 8.3 / Table 8.2';
ex.system = 'WSCC 3-machine 9-bus system from Sauer-Pai Example 7.1';
ex.model = '21-state small-signal model with exciters, constant-power loads, D_i = 0';
ex.source = ['P. W. Sauer and M. A. Pai, Power System Dynamics and Stability, ', ...
    'Example 8.3.  Eigenvalues from Table 8.2 (participation factor table), ', ...
    'which gives the correct real/complex assignment.  Table 8.1 has a ', ...
    'typo: it lists -3.3995 +/- j1.2104 as a complex pair, but Table 8.2 ', ...
    'shows -3.3995 as a real eigenvalue and -0.4445 +/- j1.2104 as the ', ...
    'complex pair.  The Table 8.2 assignment is confirmed by our ', ...
    'analytical Jacobian reproduction.'];
ex.eigenvalues = [
    -0.7209 + 1i*12.7486;
    -0.7209 - 1i*12.7486;
    -0.1908 + 1i*8.3672;
    -0.1908 - 1i*8.3672;
    -5.4875 + 1i*7.9487;
    -5.4875 - 1i*7.9487;
    -5.3236 + 1i*7.9220;
    -5.3236 - 1i*7.9220;
    -5.2218 + 1i*7.8161;
    -5.2218 - 1i*7.8161;
    -5.1761 + 0i;
    -3.3995 + 0i;
    -0.4445 + 1i*1.2104;
    -0.4445 - 1i*1.2104;
    -0.4394 + 1i*0.7392;
    -0.4394 - 1i*0.7392;
    -0.4260 + 1i*0.4960;
    -0.4260 - 1i*0.4960;
     0.0000 + 0i;
     0.0000 + 0i;
    -3.2258 + 0i];
ex.notes = ['Use this as the next non-Kundur dynamic benchmark. ', ...
    'The codebase still needs a Sauer-Pai Example 7.1 dynamic model before ', ...
    'a numerical solver comparison test can be enabled.'];

catalog.example_8_3_table_8_1 = ex;
end
