function strategy = pf_method_strategy(name)
%PF_METHOD_STRATEGY  Return a PF method strategy (CORE_ONLY, NOT_ROUTED).
%   STRATEGY = PF_METHOD_STRATEGY(NAME) returns a struct with fields:
%     .name        - canonical method name (lower case)
%     .capability  - 'production' or 'diagnostic'
%     .solve       - function handle @(case_data, opt) result
%     .method_source - 'production' (NR) etc.
%
%   P0 scope (package-only): only 'newton_raphson' is registered. The factory
%   returns a strategy whose .solve wraps the EXISTING canonical solver
%   verbatim, so a direct call through the factory is bit-identical (AbsTol=0)
%   to calling pfsolver.powerflow_newton_raphson directly. solve_case.m is NOT
%   modified; this is CORE_ONLY / NOT_ROUTED. Production routing readiness is
%   NOT_READY until the single-owner integration files are separately resolved.
%
%   fdpf_xb / fdpf_bx / bfs are registered ONLY when their phase lands AND
%   their source gate passes. Before then, requesting them ERRORS.
%
%   Fail-closed: unknown names ERROR (no silent default, no fallback).

if nargin < 1 || isempty(name)
    error('pf_method_strategy:missingName', ...
        'A method name is required. P0 allows only ''newton_raphson''.');
end

name = lower(strtrim(char(name)));

switch name
    case 'newton_raphson'
        strategy = struct( ...
            'name', 'newton_raphson', ...
            'capability', 'production', ...
            'method_source', 'in-house canonical (powerflow_newton_raphson.m)', ...
            'solve', @(case_data, opt) pfsolver.powerflow_newton_raphson(case_data, opt));
    case 'fdpf_xb'
        strategy = struct( ...
            'name', 'fdpf_xb', ...
            'capability', 'production', ...
            'method_source', 'in-house FDPF-XB (Stott-Alsac 1974)', ...
            'solve', @(case_data, opt) pfsolver.powerflow_fdpf_xb(case_data, opt));
    case 'fdpf_bx'
        strategy = struct( ...
            'name', 'fdpf_bx', ...
            'capability', 'production', ...
            'method_source', 'in-house FDPF-BX (van Amerongen 1989)', ...
            'solve', @(case_data, opt) pfsolver.powerflow_fdpf_bx(case_data, opt));
    case 'bfs'
        strategy = struct( ...
            'name', 'bfs', ...
            'capability', 'production', ...
            'method_source', 'in-house BFS (Shirmohammadi 1988) Phase-1 radial', ...
            'solve', @(case_data, opt) pfsolver.powerflow_bfs(case_data, opt));
    otherwise
        error('pf_method_strategy:unknownMethod', ...
            ['Unknown PF method "%s". Registered: newton_raphson, fdpf_xb, ' ...
             'fdpf_bx, bfs. No silent fallback.'], name);
end
end
